### ISSUE TITLE
2.1.5版本拍照成功 上传服务器 显示图片空白

### ISSUE THREAD

**Issue by PengJiang520** [SilenceLove/HXPhotoPicker#101]

**Comment by PengJiang520** [comment]
UIScrollView *scrollView = [[UIScrollView alloc] initWithFrame:self.bounds];
    scrollView.alwaysBounceVertical = YES;
    scrollView.scrollEnabled = NO;
    [self.image_pho_view addSubview:scrollView];
    self.scrollView = scrollView;
    
    CGFloat width = scrollView.frame.size.width;
   
    HXPhotoView *photoView = [[HXPhotoView alloc] initWithFrame:CGRectMake(kPhotoViewMargin, kPhotoViewMargin-5, (width - kPhotoViewMargin * 3)/1.5, 0) manager:self.manager];
    photoView.spacing = 4;
    photoView.lineCount = 4;
    photoView.spacing = kPhotoViewMargin;
    
    photoView.delegate = self;
    photoView.backgroundColor = [UIColor whiteColor];
    [photoView refreshView];
    [scrollView addSubview:photoView];
    self.photoView = photoView;

**Comment by LoveZYForever** [comment]
相机拍的照片直接用model.thumbPhoto  或者 model.previewPhoto  这个
