### ISSUE TITLE
拍摄时却访问麦克风权限，导致苹果审核不通过

### ISSUE THREAD

**Issue by zhou1043868875** [SilenceLove/HXPhotoPicker#102]
选择拍摄功能的时候，先弹出是否能访问相机相册权限的提示，选择之后又弹出是否访问麦克风权限的提示。苹果审核时，拍摄不使用麦克风却访问了麦克风的权限，被拒。

**Comment by yuanyedehuhuan** [comment]
微博不也是这样吗，麦克风权限是不是为了Live Photo功能啊

**Comment by zhou1043868875** [comment]
估计是，问题我已经解决了，使用的还是1.多的版本，我现在使用的是最新版
