### ISSUE TITLE
Demo2ViewController里怎么设置，1跟2互换。  还有就是3的文字怎么去掉，谢谢

### ISSUE THREAD

**Issue by xhzth7091** [SilenceLove/HXPhotoPicker#106]
![642da6c7-6dc8-4658-9520-ee5c8d568226](https://user-images.githubusercontent.com/13980546/41968599-7a28588c-7a37-11e8-9e26-6dc6b03535c4.png)

**Comment by SilenceLove** [comment]
/**
 照片列表按日期倒序 默认 NO
 */
@property (assign, nonatomic) BOOL reverseDate;
设置设个改变相机位置

**Comment by SilenceLove** [comment]
/**
 显示底部照片详细信息 default YES
 */
@property (assign, nonatomic) BOOL showBottomPhotoDetail;
