### ISSUE TITLE
NEW

### ISSUE THREAD

**Issue by CaiBaiLing** [SilenceLove/HXPhotoPicker#107]
单选不可编辑选择图片，图片不能显示哦！

**Comment by SilenceLove** [comment]
可以把步骤再说详情一点吗..

**Comment by CaiBaiLing** [comment]
Demo7  
<img width="305" alt="2018-06-29 10 05 17" src="https://user-images.githubusercontent.com/10629011/42069368-fa4ae7ee-7b83-11e8-82fb-636c302bd50a.png">
我加了这两句话。选择照片，点完成，图片显示不出来。
_manager.configuration.singleSelected = YES;
_manager.configuration.singleJumpEdit = NO;

**Comment by SilenceLove** [comment]
用单选的话就不要用HXPhotoView

**Comment by SilenceLove** [comment]
HXPhotoView不支持单选的那个
