### ISSUE TITLE
选中livePhoto后程序崩溃

### ISSUE THREAD

**Issue by WindsSunShine** [SilenceLove/HXPhotoPicker#11]
[两个demo中都有这种现象，就是当选择添加图片后并不点击下一步，而是继续滑动预览，在选择一张后再滑动预览程序就会崩溃；

错误日志：
 微博照片选择[1995:713665] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PHLivePhotoRequestOptions setVersion:]: unrecognized selector sent to instance 0x12c5e6a50'
*** First throw call stack:
(0x183285900 0x1828f3f80 0x18328c61c 0x1832895b8 0x18318d68c 0x1000d4e70 0x10009f040 0x1000f0f58 0x188132f78 0x188132a7c 0x1859cf814 0x1859cf6c8 0x1834fa1e8 0x1832271f8 0x18323d634 0x18323cd6c 0x18323aac4 0x183169680 0x184678088 0x187fe0d90 0x1000d110c 0x182d0a8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by LoveZYForever** [comment]
我这里没出现你说的问题. 你是什么型号,什么系统的

**Comment by WindsSunShine** [comment]
iPhone 6s 系统9.3.1

**Comment by LoveZYForever** [comment]
有几个人反应了这个情况,暂时还不清楚什么原因.. 可以先关闭livephoto功能..
