### ISSUE TITLE
获取图片Data卡主线程 9.x系统

### ISSUE THREAD

**Issue by JLLJHD** [SilenceLove/HXPhotoPicker#112]
+ (PHImageRequestID)getImageDataWithModel:(HXPhotoModel *)model startRequestIcloud:(void (^)(HXPhotoModel *model, PHImageRequestID cloudRequestId))startRequestIcloud progressHandler:(void (^)(HXPhotoModel *model, double progress))progressHandler completion:(void(^)(HXPhotoModel *model, NSData *imageData, UIImageOrientation orientation))completion failed:(void(^)(HXPhotoModel *model, NSDictionary *info))failed;

**Comment by droidsde** [comment]
me too
