### ISSUE TITLE
角标数字不显示问题

### ISSUE THREAD

**Issue by liuchunlao** [SilenceLove/HXPhotoPicker#117]
使用replace方法用最新拍照获取的照片替换已从相册选择的照片时，可以实现替换功能，
但出现的两个情况。
1、最新拍照图片没有自动保存到相册； 通过afterListAddCameraTakePicturesModel可以解决。
2、新增加的图片没有显示角标数字，求解决办法。

感谢！

**Comment by SilenceLove** [comment]
👌🏻，有时间我会解决的。
不现实角标应该是模型里的一个属性没赋值。。

**Comment by SilenceLove** [comment]
关于第二条问题，我这边试了几次并没有出现你说的这种情况

**Comment by liuchunlao** [comment]
谢谢！感谢大神带飞!!!哈哈~

**Comment by liuchunlao** [comment]
复述下问题
1、manager只支持选择图片.
2、从相册中选择了4张图片，确定后展示在app页面！
3、点击第2张图时，选择底部的拍照功能，然后调用自定义相机拍照，在拍照代理方法中进行图片替换操作，一切ok。
4、再次点击第2张图，选择相册，弹出相册后，，最新拍摄的图片没有展示在相册中。

在作者的指导下找到解决方案：
1、图片替换
[self.manager afterSelectedArrayReplaceModelAtModel:oldModel withModel:model];
2、将最新photo写入相册
[self.manager afterSelectedListAddEditPhotoModel:model];
3、重新set manager对应的afterArray
[self.manager setAfterSelectedPhotoArray:self..manager.afterSelectedArray];

ps:可参考photoView中的代理方法实现：
- (void)datePhotoPreviewSelectLaterDidEditClick:(HXDatePhotoPreviewViewController *)previewController beforeModel:(HXPhotoModel *)beforeModel afterModel:(HXPhotoModel *)afterModel

**Comment by WKDistinctive2018** [comment]
请问解决方法写在哪里

**Comment by liuchunlao** [comment]
<img width="1570" alt="屏幕快照 2019-09-04 上午9 59 29" src="https://user-images.githubusercontent.com/9844569/64220113-c42dea00-cefa-11e9-806c-44d8e9137011.png">
我是卸载这个回调里面了。
