### ISSUE TITLE
可以实现小图显示个数和左右滑动大图预览显示个数不一致吗

### ISSUE THREAD

**Issue by ziyanliu** [SilenceLove/HXPhotoPicker#125]
现在有个需求，有11张图，小图最多显示9张图片，多余九张在最后一张上添加蒙版查看更多图片，点击预览大图可以左右滑动查看11张图，我该怎么处理？查看源码[self.manager addNetworkingImageToAlbum:array selected:YES];这个方法赋值图片，这个array是小图大图张数一样，该怎么去扩展，多谢指教

**Comment by SilenceLove** [comment]
这样改的东西就比较多了。。
