### ISSUE TITLE
选择照片后回调方法里真机model.locationData和localIdentifier为null，模拟器上有值

### ISSUE THREAD

**Issue by GoroMajima** [SilenceLove/HXPhotoPicker#129]

**Comment by GoroMajima** [comment]
// 管理类设置如下已经设置保存到图库，看框架中HXPhotoModel中保存到图库应该有model.locationData，和localIdentifier，然而真机运行打印为null，测试机为5s，系统为11.4.1

- (HXPhotoManager *)manager {
    if (!_photoManager) {
        //初始化图片选择器属性
        _photoManager = [[HXPhotoManager alloc] initWithType:HXPhotoManagerSelectedTypePhoto];
        HXPhotoConfiguration *config = [[HXPhotoConfiguration alloc] init];//属性类初始化
        config.photoMaxNum = MAXPicNum;//最大选择相片数
        config.saveSystemAblum = YES;//是否保存视频照片到图库
        config.showDateSectionHeader = NO;//是否显示日期
        _photoManager.configuration = config;
    }
    return _photoManager;
}

返回选择的图片以及视频
- (void)albumListViewController:(HXAlbumListViewController *)albumListViewController didDoneAllList:(NSArray<HXPhotoModel *> *)allList photos:(NSArray<HXPhotoModel *> *)photoList videos:(NSArray<HXPhotoModel *> *)videoList original:(BOOL)original{
 NSSLog(@"回调image===%@   ID===%@",model.locationData,model.localIdentifier);}

**Comment by SilenceLove** [comment]
#130
