### ISSUE TITLE
相册里拍照后回调得到的照片中，asset.location和asset.creationDate为空

### ISSUE THREAD

**Issue by WIndFate** [SilenceLove/HXPhotoPicker#130]
点击➕进入相册，选择拍照按钮得到拍照的图片，在选择图片后获取刚拍照的图片模型，asset.location和asset.creationDate为空。如果第二次进入相册，选择刚才拍好的这张照片获得模型后，asset.location为空，asset.creationDate却有值。
如果获取手机自带相机拍照后的图片，asset.location和asset.creationDate都是有值的。

**Comment by SilenceLove** [comment]
请直接用 model.location 和 model.creationDate
