### ISSUE TITLE
我现在做一个仿发朋友圈的页面,  我需要读取本地相册,在photoView加载出来

### ISSUE THREAD

**Issue by xhzth7091** [SilenceLove/HXPhotoPicker#131]
我用数据库保留- (void)photoView:(HXPhotoView *)photoView imageChangeComplete:(NSArray<UIImage *> *)imageList里的imageList,  再次进入这个页面以后,我用HXPhotoView的imageList读取数据,不显示,如第三张图。
但是我用[self.manager addLocalImage:images selected:YES];读取同一个images,在相册里就默认选中图片了,如 第四张图

![1edad82d-587d-4e73-a2c2-fa551d84cf49](https://user-images.githubusercontent.com/13980546/44204229-65c58a80-a184-11e8-9554-f3f6e92d2d5f.png)
<img width="607" alt="6332dd9b-9017-4969-8a7f-c99d4a1022ab" src="https://user-images.githubusercontent.com/13980546/44204350-c5bc3100-a184-11e8-92f2-26a47158cd89.png">

<img width="467" alt="5a23e4b1-644a-4fd2-8884-986cd9b9b8c4" src="https://user-images.githubusercontent.com/13980546/44204402-fef4a100-a184-11e8-9202-570fe53241b0.png">
<img width="392" alt="ccc65d38-a3cb-4bf6-a36e-71db4e301cbc" src="https://user-images.githubusercontent.com/13980546/44204493-63affb80-a185-11e8-8d3f-a84fd67484b3.png">

**Comment by SilenceLove** [comment]
调用刷新HXPhotoView的方法


最新的demo里有保存草稿的功能
