### ISSUE TITLE
你好，发现如果手机内没有照片会Crash

### ISSUE THREAD

**Issue by dreamahui** [SilenceLove/HXPhotoPicker#133]
拍照->选择相册  会发生crash、并且相册内照片会重复显示；

直接选择相册 会发生crash;

**Comment by SilenceLove** [comment]
崩溃信息看一下

**Comment by dreamahui** [comment]
Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x1c02979d0 H:[MPKnockoutButton:0x1052ab3e0]-(34)-[MPDetailSlider:0x1052a8170](LTR)   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
AppDelegate.m:13	CRASH: *** -[__NSArrayM insertObject:atIndex:]: index 18446744073709551615 beyond bounds for empty array
AppDelegate.m:14	Stack Trace: (
	0   CoreFoundation                      0x0000000183fb6da4 <redacted> + 252
	1   libobjc.A.dylib                     0x00000001831705ec objc_exception_throw + 56
	2   CoreFoundation                      0x0000000183f4f750 _CFArgv + 0
	3   CoreFoundation                      0x0000000183e83038 <redacted> + 1376
	4   ÁÖßÁâáÈÄâÊã©Âô®                     0x000000010495f730 -[HXPhotoManager getPhotoListWithAlbumModel:complete:] + 11064
	5   ÁÖßÁâáÈÄâÊã©Âô®                     0x00000001049d909c __41-[HXDatePhotoViewController getPhotoList]_block_invoke + 288
	6   libdispatch.dylib                   0x0000000104c791dc _dispatch_call_block_and_release + 24
	7   libdispatch.dylib                   0x0000000104c7919c _dispatch_client_callout + 16
	8   libdispatch.dylib                   0x0000000104c85200 _dispatch_queue_override_invoke + 968
	9   libdispatch.dylib                   0x0000000104c8a7c8 _dispatch_root_queue_drain + 604
	10  libdispatch.dylib                   0x0000000104c8a500 _dispatch_worker_thread3 + 136
	11  libsystem_pthread.dylib             0x0000000183bdbfac _pthread_wqthread + 1176
	12  libsystem_pthread.dylib             0x0000000183bdbb08 start_wqthread + 4
)
2018-08-30 09:26:19.479658+0800 照片选择器[16998:1701626] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM insertObject:atIndex:]: index 18446744073709551615 beyond bounds for empty array'
*** First throw call stack:
(0x183fb6d8c 0x1831705ec 0x183f4f750 0x183e83038 0x10495f730 0x1049d909c 0x104c791dc 0x104c7919c 0x104c85200 0x104c8a7c8 0x104c8a500 0x183bdbfac 0x183bdbb08)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by dreamahui** [comment]
我给你大概说说场景：

**Comment by dreamahui** [comment]
我给你大概说说场景：
集成：拍照、选择照片两种功能，设置了照片存储功能；
1. 当手机内没有一张照片时，拍照；当完成拍照功能，切换到选择照片功能，进入相册，会重复出现两张一样的图片资源；
2. 当多拍几张照片时，在进入选择相片会出现Crash;
3. 我已经申请加群，希望通过下哈；QQ：1490815052
