### ISSUE TITLE
encodeKey 宏和七牛sdk的参数命名冲突了，建议换个长一点的名字

### ISSUE THREAD

**Issue by titer18** [SilenceLove/HXPhotoPicker#138]
pod Qiniu （https://github.com/qiniu/objc-sdk.git）

QNFileRecorder.h 
+ (instancetype)fileRecorderWithFolder:(NSString *)directory
                             encodeKey:(BOOL)encode
                                 error:(NSError *__autoreleasing *)error;

**Comment by SilenceLove** [comment]
👌
