### ISSUE TITLE
iPhone7Plus，定位权限请求弹框无法点击，严重时必须强制关机

### ISSUE THREAD

**Issue by baxiaxx** [SilenceLove/HXPhotoPicker#142]
用了你的demo，在进行拍照的时候会弹出“打开定位服务来允许照片确定您的位置”，但是在相机页面这个框会闪一下并消失，退出拍照后又会闪一下并消失，有一次居然弹框一直显示在屏幕上，点击也无效，导致我不得不强制重启。
bug重现条件：我的系统为ios11.0.1，设置隐私中定位服务完全关闭，机型为iPhone7Plus

**Comment by SilenceLove** [comment]
已解决 
在开始定位前判断下权限就好了..
if ([CLLocationManager authorizationStatus] != kCLAuthorizationStatusDenied) {
    [self.locationManager startUpdatingLocation];
}
