### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by zhaoychehe** [SilenceLove/HXPhotoPicker#146]
HXAlbumListViewController.m

self.cancelBlock(weakSelf);
self.doneBlock(allList, photoList, videoList, nil, original, weakSelf);
strongSelf.doneBlock(allList, photoList, videoList, imageList, original, strongSelf);
是否会更好

**Comment by SilenceLove** [comment]
嗯，最近看到了这个问题。以前写漏了。￣□￣｜｜
这里的逻辑已改，最近会提交一下的。
