### ISSUE TITLE
加载网络图片后，再删除其中一个，怎么获取剩余的图片数组

### ISSUE THREAD

**Issue by Azraeltulips** [SilenceLove/HXPhotoPicker#151]
加载网络图片后，再删除其中一个，怎么获取剩余的图片数组？- (void)photoView:(HXPhotoView *)photoView imageChangeComplete:(NSArray<UIImage *> *)imageList;这个代理虽然走了，但是imageList是空的。

**Comment by SilenceLove** [comment]
这个方法已移除
具体可以看readme
