### ISSUE TITLE
你这README过期了吧

### ISSUE THREAD

**Issue by beijiahiddink** [SilenceLove/HXPhotoPicker#152]
- (HXPhotoManager *)manager { // 懒加载管理类
    if (!_manager) { // 设置一些配置信息
        _manager = [[HXPhotoManager alloc] initWithType:HXPhotoManagerSelectedTypePhoto];
        //        _manager.openCamera = NO;
        _manager.showDeleteNetworkPhotoAlert = NO;
        _manager.saveSystemAblum = YES;
        _manager.photoMaxNum = 6;

你这Api有的都没有了啊

**Comment by SilenceLove** [comment]
这些没有更新...😓
