### ISSUE TITLE
有点疑惑

### ISSUE THREAD

**Issue by coderchou** [SilenceLove/HXPhotoPicker#153]
[HXWeiboPhotoPicker](https://github.com/KeenTeam1990/HXWeiboPhotoPicker) 这个库是copy自 **HXPhotoPicker** 吗？ 感觉一模一样😂

**Comment by SilenceLove** [comment]
HXWeiboPhotoPicker
这个是以前的版本

**Comment by coderchou** [comment]
膜拜大神
