### ISSUE TITLE
右导航栏“取消”按钮点击无法响应

### ISSUE THREAD

**Issue by snow-nwh** [SilenceLove/HXPhotoPicker#157]
作者您好，谢谢分享！
我这边遇到一个问题：应用本身是固定横屏的，然后调用相册时发现右导航栏取消按钮点击不响应，或者说无法点击到这个取消按钮，但左侧返回按钮可以点击和响应。开发环境是Xcode9，模拟器或者真机都是这个问题。
另外建议您弃用某个API时给旧API加个提示用xxx（新API）替换。如：
> NS_DEPRECATED_IOS(4_0, 10_0, "Use xxx")

**Comment by SilenceLove** [comment]
demo有这个问题吗?

**Comment by snow-nwh** [comment]
demo没有这个问题。
