### ISSUE TITLE
国际化问题

### ISSUE THREAD

**Issue by sun2483968** [SilenceLove/HXPhotoPicker#163]
本人真机测试，语言肯定是中文的，可是调用相册 全部都是英文的，看到往期回答会根据系统语言来判断，可是并没有 请问这个问题怎么处理？是我的使用方法有问题吗？

**Comment by sun2483968** [comment]
![wechatimg39](https://user-images.githubusercontent.com/13990779/48040460-fc1db100-e1b3-11e8-9a8a-29d9db445b2b.jpeg)

**Comment by SilenceLove** [comment]
Demo有这个问题吗...

**Comment by veenveenveen** [comment]
> 本人真机测试，语言肯定是中文的，可是调用相册 全部都是英文的，看到往期回答会根据系统语言来判断，可是并没有 请问这个问题怎么处理？是我的使用方法有问题吗？

![snip20181123_5](https://user-images.githubusercontent.com/18379028/48935493-df6ad280-ef42-11e8-95b1-5c86479cb2a5.png)

在自己的工程里添加支持的语言，如果为0的话移除之后重新添加
