### ISSUE TITLE
Swift通过XIB方式加载报错（详细请看截图）

### ISSUE THREAD

**Issue by JqyModi** [SilenceLove/HXPhotoPicker#166]
![wx20181107-184226](https://user-images.githubusercontent.com/19703476/48126858-39219a80-e2bd-11e8-9dee-39427fe7001c.png)
![wx20181107-184527](https://user-images.githubusercontent.com/19703476/48126983-a1707c00-e2bd-11e8-8a7c-fba35d0e3583.png)
![wx20181107-184540](https://user-images.githubusercontent.com/19703476/48126985-a1707c00-e2bd-11e8-8f09-b590f7464f2c.png)
![6d2cd8ac-b04b-453f-a3eb-dbbd268c438c](https://user-images.githubusercontent.com/19703476/48127006-ad5c3e00-e2bd-11e8-9ed3-5d3a58f009d8.png)

**Comment by SilenceLove** [comment]
Self.lineCount为0的原因。。

**Comment by JqyModi** [comment]
Self.lineCount设置为5了也出不来 还是空白 @SilenceLove

**Comment by JqyModi** [comment]
升级了最新版本可以了 @SilenceLove  能不能自定义Cell呢 有时候需求用的删除按钮和添加按钮图标不一样需要定制

**Comment by JqyModi** [comment]
xib_photoView.lineCount = 5
xib_photoView.spacing = 0 
加了这个无效，每行还是显示三个

**Comment by SilenceLove** [comment]
录个视频看一下

**Comment by JqyModi** [comment]
@SilenceLove 
![wx20181108-190702](https://user-images.githubusercontent.com/19703476/48195040-997e0e00-e389-11e8-9745-119688c01b4a.png)
![wx20181108-190733](https://user-images.githubusercontent.com/19703476/48195041-997e0e00-e389-11e8-87a4-0da8da9c3b96.png)
所有的都在这里了

**Comment by JqyModi** [comment]
是使用的方式不对吗

**Comment by SilenceLove** [comment]
设置完刷新一下 HXPhotoView 试一下

**Comment by JqyModi** [comment]
刷新还是不行呢  大佬能出个Swift的Demo吗？毕竟现在Swift用的很广了

**Comment by SilenceLove** [comment]
后面会考虑一下,
swift 先不要用xib加载了. 用代码的方式布局吧..
