### ISSUE TITLE
自定义themeColor后，原图按钮旁边的圆圈仍然是蓝色

### ISSUE THREAD

**Issue by noveleven** [SilenceLove/HXPhotoPicker#167]
<img width="404" alt="default" src="https://user-images.githubusercontent.com/6308830/48241540-5e73ed00-e412-11e8-9f3a-3e933b0e2340.png">

**Comment by SilenceLove** [comment]
![image](https://user-images.githubusercontent.com/18083149/48242081-7d737e80-e414-11e8-860a-4edc12a6d8b5.png)
这是一个图标，改了颜色这个图标也要跟着改
