### ISSUE TITLE
相册选择了图片,在用相机拍照,图片不变

### ISSUE THREAD

**Issue by xhzth70911** [SilenceLove/HXPhotoPicker#169]
我设置了HXPhotoManager的configuration.photoMaxNum = 1,图片的最大选择数量为1. 我设置头像, 我先选择相册,选中一张图片以后, 我的头像就是相册的这张图片,      我在用相机去拍张照片,  我的头像还是相册的图片,    怎么变成直接变成我后面拍照的图片.        图片的最大选择数量还是1,这是前提条件,求教

**Comment by SilenceLove** [comment]
是自己调转的相机界面吗？

**Comment by xhzth70911** [comment]
不是，我用的HXPhotoPicker自带调用相机的方法。
![caf63f63-7f8f-4729-81f0-b19f7736fa37](https://user-images.githubusercontent.com/24982706/48762780-bbab5080-ece6-11e8-8992-5eea264d8654.png)
![90321a8d-570a-4c87-b540-6f11219fb5ea](https://user-images.githubusercontent.com/24982706/48762798-c5cd4f00-ece6-11e8-8a6d-6fb7cd7e0a3b.png)
![1387a87c-ce13-4304-927b-b9b8ab8c75ad](https://user-images.githubusercontent.com/24982706/48762809-cbc33000-ece6-11e8-856e-4bdda62b315f.png)
![3dab5f2a-79a5-4d5e-b22b-44a2cd03b389](https://user-images.githubusercontent.com/24982706/48762825-d41b6b00-ece6-11e8-8e4d-e82b35c26c86.png)
