### ISSUE TITLE
iphone x 录制视频 上传后只有声音 无图像

### ISSUE THREAD

**Issue by cczufish** [SilenceLove/HXPhotoPicker#171]
iphone x 录制视频 上传后只有声音 无图像

**Comment by SilenceLove** [comment]
我用iphonex 试了下demo，没有出现你说的这种情况。

**Comment by cczufish** [comment]
> 我用iphonex 试了下demo，没有出现你说的这种情况。

应该是阿里云的问题，录制完视频上传到阿里云后，再去播放就只有声音没有图像
