### ISSUE TITLE
拍照后照片已保存到本地，但是fileUrl为空

### ISSUE THREAD

**Issue by lirylee7777777** [SilenceLove/HXPhotoPicker#174]
拍完照后，照片已经存在本地了。但是返回的hxphotomodel对象里的fileurl是空值。

**Comment by SilenceLove** [comment]
相机拍照的都是临时存的UIImage

**Comment by lirylee7777777** [comment]
HXPhotoTools文件里690行。
(void)savePhotoToCustomAlbumWithName:(NSString *)albumName photo:(UIImage *)photo model:(HXPhotoModel *)model方法。
拍完照后调用该方法存储照片到了自定义相册里。但是存完后没有把PHAsset对象取出来。所以我改了这个方法。加了一个参数 “model:(HXPhotoModel *)model” 然后加了两行代码：
PHFetchResult<PHAsset *> *phfetchResult = [PHAsset fetchAssetsWithLocalIdentifiers:@[createdAsset.localIdentifier] options:nil];
model.asset = [phfetchResult objectAtIndex:0];
把存储后照片的PHAsset对象取了出来。

**Comment by chilewen** [comment]
@lirylee7777777 我这样子改了没有效果。。。

**Comment by lirylee7777777** [comment]
> @lirylee7777777 我这样子改了没有效果。。。

这样只是把phasset对象放到了model里。如果你要用fileUrl，就要再从phasset对象里把fileUrl取出来。取法参考HXPhotoModel的fileUrl方法。

**Comment by SilenceLove** [comment]
拍照逻辑已改
