### ISSUE TITLE
为什么拍摄后的视频有VideoURL，拍照后照片没有可用的URL

### ISSUE THREAD

**Issue by WKDistinctive2018** [SilenceLove/HXPhotoPicker#176]
为什么拍摄后的视频有VideoURL，拍照后照片没有可用的URL，我是把控件写在cell中，外部控制器进来之前也会掉用这个控件，是否都要调用writeSelectModelListToTempPathWithList这个方法

**Comment by SilenceLove** [comment]
相册里的资源需要通过Model里的PHAsset获取

**Comment by WKDistinctive2018** [comment]
我目前的场景和demo6相似，但我在demo6Suv控制器中把HXPhotoView控件加载在tabview的cell中，出现的问题就是在demo6中用自定义相册中使用最后相机按钮拍的照片选中后，在打开demo6Suv中的自定义相册中没有显示，但完成中的序号是对的（比如demo6中只选中一张相册中拍摄的图片就是（1/9））只是看不到图片，而非拍摄选中的照片可以显示且选中的序号也是正确的。希望大神百忙中帮忙看下

**Comment by SilenceLove** [comment]
因为没有加到相机数组里。在相机拍照完成之后按demo8的方法添加进去

**Comment by SilenceLove** [comment]
因为没有加到相机数组里。在相机拍照完成之后按demo12的方法添加进去

**Comment by WKDistinctive2018** [comment]
以下修改方法还是无效
HXCustomCameraViewController.m
255行 didDoneBtnClick中
if (self.manager.configuration.saveSystemAblum) {
        if (model.type == HXPhotoModelMediaTypeCameraPhoto) {
            HXCustomAssetModel *assetModel = [HXCustomAssetModel assetWithLocalImage:model.previewPhoto selected:YES];
            [self.manager addCustomAssetModel:@[assetModel]];
            [HXPhotoTools savePhotoToCustomAlbumWithName:self.manager.configuration.customAlbumName photo:model.previewPhoto model:model];
        }else {
            [HXPhotoTools saveVideoToCustomAlbumWithName:self.manager.configuration.customAlbumName videoURL:model.videoURL];
        }
    }

**Comment by SilenceLove** [comment]
？？？不是你这样写。。

**Comment by WKDistinctive2018** [comment]
是在这里改吗？大神教我
