### ISSUE TITLE
iPhone XR的适配没有做好,正常选择图片的时候,第一行会被导航栏挡住一部分.

### ISSUE THREAD

**Issue by mumugongzhu** [SilenceLove/HXPhotoPicker#177]
iPhone XR的适配没有做好,正常选择图片的时候,第一行会被导航栏挡住一部分.

**Comment by mumugongzhu** [comment]
iPhone XS Max是没问题的

**Comment by SilenceLove** [comment]
![f4af1058d072b909e8e903f4c9e13873](https://user-images.githubusercontent.com/18083149/50037219-1025bf80-004a-11e9-942b-6b1100031fb0.jpg)
![cf44c4730c5247a88582011d81206143](https://user-images.githubusercontent.com/18083149/50037223-1320b000-004a-11e9-971e-393936d3cc57.jpg)
没问题啊
