### ISSUE TITLE
单独调用相机拍摄后的照片为什么没有编辑界面

### ISSUE THREAD

**Issue by 513494297** [SilenceLove/HXPhotoPicker#178]
hx_presentCustomCameraViewControllerWithManager这个方法调用相册拍摄后的照片不会出现编辑页面，而在hx_presentAlbumListViewControllerWithManager里的相机拍摄后的照片会有编辑页面，宽高比我设置过了。为什么不起作用呢。。。还请指点下

**Comment by SilenceLove** [comment]
#154
