### ISSUE TITLE
选择你那个demo2去掉了scrollview以后选择照片返回就会上移一个导航栏的高度怎么解决

### ISSUE THREAD

**Issue by zhangyutao12** [SilenceLove/HXPhotoPicker#180]

**Comment by SilenceLove** [comment]
已加属性恢复
/**
 如果选择完照片返回之后，
 原有界面继承UIScrollView的视图都往下偏移一个导航栏距离的话，
 那么请将这个属性设置为YES，即可恢复。
 */
@property (assign, nonatomic) BOOL restoreNavigationBar;
