### ISSUE TITLE
单选模式裁剪后的崩溃问题

### ISSUE THREAD

**Issue by Ning-Wang** [SilenceLove/HXPhotoPicker#184]
在demo9 的中 HXPhotoManager 添加如下设置：
_manager.configuration.singleSelected = YES;
_manager.configuration.singleJumpEdit = YES;
        _manager.configuration.movableCropBox = YES;
_manager.configuration.movableCropBoxCustomRatio = CGPointMake(1, 1);

当剪切图片后 点击刚剪切过的HXPhotoView会在如下位置数组越界崩溃：
#import "HXDatePhotoPreviewViewController.h" 中
- (void)changeSubviewFrame {
    UIInterfaceOrientation orientation = [[UIApplication sharedApplication] statusBarOrientation];
    HXPhotoModel *model = self.modelArray[self.currentModelIndex];
/****排查原因***/
在HXDatePhotoViewController.m中
#pragma mark - < HXDatePhotoEditViewControllerDelegate >
- (void)datePhotoEditViewControllerDidClipClick:(HXDatePhotoEditViewController *)datePhotoEditViewController beforeModel:(HXPhotoModel *)beforeModel afterModel:(HXPhotoModel *)afterModel {
    if (self.manager.configuration.singleSelected) {
        [self.manager beforeSelectedListAddPhotoModel:afterModel];
        /****此处没有向afterselectedListA中添加model****/
        [self.manager afterSelectedListAddPhotoModel:afterModel];
        [self datePhotoBottomViewDidDoneBtn];
        return;
    }

不知道是不是我对库使用理解有问题，如果没有为题希望系版本中有修改。

**Comment by Ning-Wang** [comment]
另一个问题，非单选模式，保存至相册设置为YES。如果HXPhotoManager 不重制，在别的app中下载图片，弹出选择框没有刷新出新下载的图片。

**Comment by SilenceLove** [comment]
目前使用HXPhotoView不支持单选模式
