### ISSUE TITLE
选择时gif不要显示 怎么设置啊 大神 求救

### ISSUE THREAD

**Issue by jiangchao829** [SilenceLove/HXPhotoPicker#191]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [x] 我已经查阅了已有的issue，没有找到相同的
- [x] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图

**Comment by jiangchao829** [comment]
假如这个图片是gif 。在选择列表中不要出现， 而不是显示gif的第一帧图片

**Comment by SilenceLove** [comment]
配置类把lookGif设置为No

**Comment by jiangchao829** [comment]
imagePickerManager.configuration.lookGifPhoto = false。
已经置为 No 还是不行
