### ISSUE TITLE
逻辑问题

### ISSUE THREAD

**Issue by CocoaML** [SilenceLove/HXPhotoPicker#192]
### 感谢分享

有一个逻辑问题：
在所有照片页面：(HXDatePhotoViewController) 点击任意一个图片，进入单个图片预览页面 (HXDatePhotoPreviewViewController) 左右滚动多张图片，如果图片在iCloud中，自动下载到本地后，再返回所有照片页面：(HXDatePhotoViewController), 任然显示iCloud图标，点击iCloud图标不能下载，也不能选择。。。

**Comment by SilenceLove** [comment]
找到原因了..
需要改两个地方

**Comment by SilenceLove** [comment]
一. HXDatePhotoViewCell 的 startRequestICloudAsset 方法里
在每个获取成功的回调里加上 weakSelf.model.isICloud = NO;
二. HXPhotoModel.m 里的requestDataWithResult 方法里把self.isICloud = NO 屏蔽掉

**Comment by CocoaML** [comment]
感谢您的回复, 我在尝试一下
