### ISSUE TITLE
前置摄像头拍照 拍完一次 再次拍照 闪光灯图片变型 毕现 ios12

### ISSUE THREAD

**Issue by jiangchao829** [SilenceLove/HXPhotoPicker#193]
[###]([url]([url](url))) 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图

**Comment by SilenceLove** [comment]
能截个图吗?我这里试了一几次没出现变形.

**Comment by jiangchao829** [comment]
可以啊 你给我邮箱 我给你发下

**Comment by jiangchao829** [comment]
294005139@qq.com。这个可以吗

**Comment by jiangchao829** [comment]
发你 294005139@qq.com 这个邮箱了 你看看吧 附件就是

**Comment by SilenceLove** [comment]
👌

**Comment by SilenceLove** [comment]
你用最新版本的试一下
我试了几次都没出现变形的情况
