### ISSUE TITLE
视频图片混合选择时，最大选择数maxNum没生效

### ISSUE THREAD

**Issue by fby1070** [SilenceLove/HXPhotoPicker#195]
self.manager.configuration.selectTogether = YES;
    self.manager.configuration.videoMaxNum = 4;
    self.manager.configuration.photoMaxNum = 4;
    self.manager.configuration.maxNum = 4;

![image](https://user-images.githubusercontent.com/11359021/51510355-be860700-1e37-11e9-9165-d34addb71b4d.png)

**Comment by SilenceLove** [comment]
要是想最大选择数是4，并且图片和视频混合选不限制数量的话，照片最大数和视频最大数应该是设置成0

**Comment by fby1070** [comment]
self.manager.configuration.selectTogether = YES;
    self.manager.configuration.videoMaxNum = 0;
    self.manager.configuration.photoMaxNum = 0;
    self.manager.configuration.maxNum = 4;

![image](https://user-images.githubusercontent.com/11359021/51589528-43e5e600-1f22-11e9-8f57-f7d2d55fa06e.png)

**Comment by SilenceLove** [comment]
你是什么版本的?pod的话我还没有更新

**Comment by fby1070** [comment]
2.2.3

**Comment by SilenceLove** [comment]
pod 已更新2.2.5版本
