### ISSUE TITLE
sectionHeader隐藏不行,能否加个属性直接控制相册选取相册界面的导航栏透明度,比如说，一进去就是不透明

### ISSUE THREAD

**Issue by lzc1022** [SilenceLove/HXPhotoPicker#196]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图

**Comment by SilenceLove** [comment]
sectionHeader隐藏不行指的是什么？
HXPhotoConfiguration.h 有block把导航栏返回了。可以自行修改
