### ISSUE TITLE
视频和图片共同选择后处理成功，但是数组为空

### ISSUE THREAD

**Issue by leisong1125** [SilenceLove/HXPhotoPicker#200]
![2019-02-15 10 18 24](https://user-images.githubusercontent.com/14797836/52830291-2bc14b00-310b-11e9-8ff8-5034f69407a4.png)

**Comment by leisong1125** [comment]
这个是demo上的 也会出现问题
<img width="1166" alt="2019-02-15 10 31 38" src="https://user-images.githubusercontent.com/14797836/52830737-fddd0600-310c-11e9-93b2-cf5c7f19f244.png">

**Comment by SilenceLove** [comment]
![image](https://user-images.githubusercontent.com/18083149/52834341-67184580-311c-11e9-9846-83f62a27ff12.png)
这里将break换成continue..

**Comment by leisong1125** [comment]
good、测试过了没出现之前的问题
