### ISSUE TITLE
调起相机时，导航栏向下偏移了10个点

### ISSUE THREAD

**Issue by Mrdongyueyue** [SilenceLove/HXPhotoPicker#203]
在HXCustomCameraViewController的方法changeSubviewFrame中
if (!HX_IS_IPhoneX_All && HX_IOS11_Later) {
    self.customNavigationBar.hx_y = self.previewView.hx_y + 10;
}
这里会有问题么？这样写是为了解决什么问题呢？

**Comment by SilenceLove** [comment]
这里，我个人觉得向下便宜10好看些😂

**Comment by Mrdongyueyue** [comment]
原来如此😂
