### ISSUE TITLE
pod YYWebImage与YYKit冲突 解决方案：将YYKit拆开分别导入

### ISSUE THREAD

**Issue by SwiftHsw** [SilenceLove/HXPhotoPicker#210]
pod YYWebImage与YYKit冲突
解决方案：将YYKit拆开分别导入,我有YYKit了,然后拖进去就爆冲突,不是倒入YYKit 就通用的吗?

**Comment by SilenceLove** [comment]
不要导入YYKit  
一个一个的导入就可以了
"YYWebImage"
"YYImage"
等等
