### ISSUE TITLE
怎么单独使用图片浏览放大功能？

### ISSUE THREAD

**Issue by 2952883085** [SilenceLove/HXPhotoPicker#211]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图

**Comment by SilenceLove** [comment]
![image](https://user-images.githubusercontent.com/18083149/55767814-fd2d7400-5aac-11e9-87c4-e0d9f8b050a0.png)
HXPhotoView.h 有暴露方法

**Comment by 2952883085** [comment]
EalbumActiveDataModel *model = self.dataSource[_idx];
 EalbumActiveTitleListDataModel *m = model.list.data[indexPath.item];
[[HXPhotoView photoManager:self.photoManager] jumpPreviewViewControllerWithModel:[HXPhotoModel photoModelWithImageURL:[NSURL URLWithString:m.photo_url]]];提示model有误，图片UI布局我自己用的collection布局的

**Comment by SilenceLove** [comment]
你自己布局的话,, 要点进去看下代码.. 然后你要改一下..

**Comment by 2952883085** [comment]
好的，谢谢了

**Comment by SilenceLove** [comment]
已支持
