### ISSUE TITLE
SDWebImage 5.0 报错！

### ISSUE THREAD

**Issue by boai** [SilenceLove/HXPhotoPicker#212]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图
SDWebImage  5.0 中 ，sd_cancelCurrentAnimationImagesLoad 这个方法去掉了！

**Comment by SilenceLove** [comment]
已适配v5.0.0
