### ISSUE TITLE
cell

### ISSUE THREAD

**Issue by ycf4971** [SilenceLove/HXPhotoPicker#213]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [x] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图

**Comment by ycf4971** [comment]
想实现图片选择之后 cell 带圆角的效果 请问 是否有暴露出来的接口

**Comment by SilenceLove** [comment]
暂时没有暴露出来,需要自己改源码

**Comment by ycf4971** [comment]
好的 感谢
