### ISSUE TITLE
我想直接使用图片预览功能，传一个数组和某个图片model，然后可以滚动，甚至是手势，请问怎么设置

### ISSUE THREAD

**Issue by snake406635029** [SilenceLove/HXPhotoPicker#219]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图

**Comment by SilenceLove** [comment]
最新版本的可以单独使用。但是不支持手势

**Comment by SilenceLove** [comment]
已支持
