### ISSUE TITLE
大神您好 选择后的图片一行显示多张怎么设置

### ISSUE THREAD

**Issue by ZachGuoMingyu** [SilenceLove/HXPhotoPicker#223]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [x] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图

**Comment by SilenceLove** [comment]
目前还不支持
