### ISSUE TITLE
HXPhotoView 使用问题

### ISSUE THREAD

**Issue by ebamboo** [SilenceLove/HXPhotoPicker#225]
如果设置 HXPhotoView 最大显示数量为 4，初始化并代码添加四张图片后，会显示 “第 5 张” 图片--- 添加按钮图片。预期效果：初始化 HXPhotoView 并代码添加 4 张及以上图片时，最终应只能添加并显示 4 张图片，不应该显示添加按钮图片。

**Comment by SilenceLove** [comment]
Demo有这个问题吗？

**Comment by ebamboo** [comment]
修改最新Demo3 最大值确实没这个问题了，我才发现用到 2.2.3 。。。
