### ISSUE TITLE
能否把HXPhotoPreviewViewController单独使用呢

### ISSUE THREAD

**Issue by tanjieaa** [SilenceLove/HXPhotoPicker#226]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图
——————————————————————————————————————

现在都是和HXPhotoView绑定的，因为需求界面和demo不完全一样，所以布局是自己写了，但是想用HXPhotoPreviewViewController，现在是用pod的，也没法改源码，所以希望能把HXPhotoPreviewViewController提取出来

**Comment by SilenceLove** [comment]
最新版提供了方法，在分类里
