### ISSUE TITLE
编辑一张全景图，点击一次旋转，内存涨10倍

### ISSUE THREAD

**Issue by Pangshishan** [SilenceLove/HXPhotoPicker#227]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图

**Comment by wangjufan** [comment]
在hx_rotationImage 中添加尺寸限制
   while (rect.size.width * rect.size.height > 4 * 1000 * 1000) {
        rect.size.width /= 2;
        rect.size.height /= 2;
    }
    
- (UIImage *)hx_rotationImage:(UIImageOrientation)orient {
    
    CGRect bnds = CGRectZero;
    UIImage* copy = nil;
    CGContextRef ctxt = nil;
    CGImageRef imag = self.CGImage;
    CGRect rect = CGRectZero;
    CGAffineTransform tran = CGAffineTransformIdentity;
    
    rect.size.width = CGImageGetWidth(imag);
    rect.size.height = CGImageGetHeight(imag);
    
    while (rect.size.width * rect.size.height > 4 * 1000 * 1000) {
        rect.size.width /= 2;
        rect.size.height /= 2;
    }
