### ISSUE TITLE
怎么通过视频videourl地址 在相册中找到相对应的视频，（先将选中的视频保存到数据库然后在相册选择器查看）

### ISSUE THREAD

**Issue by 2272229234** [SilenceLove/HXPhotoPicker#231]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图

**Comment by SilenceLove** [comment]
找不到..请参考demo里面保存草稿功能
