### ISSUE TITLE
大佬，下面这个人把你的库重新在GitHub上又发了一遍出来

### ISSUE THREAD

**Issue by a714857512** [SilenceLove/HXPhotoPicker#232]
大佬，下面这个人把你的库重新在GitHub上又发了一遍出来，只改了前缀之类的，其他很多描述都没有改，好不要脸呀
https://github.com/KeenTeam1990/HXWeiboPhotoPicker

**Comment by Gayle448** [comment]
这么巧，刚刚在盗版的那个人那看到你的评论才发现那个仓库原来不是原作者的，来这边就发现你刚评论了。

**Comment by a714857512** [comment]
因为我再次更新了一下这个框架的版本，刚好有搜到那家伙上传的，只好来这里吐槽了。
