### ISSUE TITLE
大佬，选择相册，里面拍照功能问题

### ISSUE THREAD

**Issue by 1109744025** [SilenceLove/HXPhotoPicker#235]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [x] 我已经查阅了已有的issue，没有找到相同的
- [x] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图

**Comment by 1109744025** [comment]
大佬你好，我发现一个问题：选择相册时候，里面有个相机拍照功能，如果拍照之后，再同时选择相册的图片。这样代理里面数组model.asset里面会有nil。望大佬有时间看下这个问题。

**Comment by SilenceLove** [comment]
readme有说明
