### ISSUE TITLE
打开相册选取照片，缺少了两张照片

### ISSUE THREAD

**Issue by WanMeg** [SilenceLove/HXPhotoPicker#243]
我已经查阅了已有的issue，没有找到相同的

你好，有个问题请教一下，在选择图片的时候，打开相册缺少了两张照片，这会是什么原因呢？
请看图

![选择照片1](https://user-images.githubusercontent.com/27676280/58528453-17601480-8209-11e9-956c-7207ad235dde.png)

![5113张照片](https://user-images.githubusercontent.com/27676280/58527614-efbb7d00-8205-11e9-95b7-eb5edb147643.png)

![5115张照片](https://user-images.githubusercontent.com/27676280/58527636-0b268800-8206-11e9-9b55-c02f21c8699b.png)

**Comment by jidanyu** [comment]
我也发现了这个问题。我这边好像少的都是几M以上，从微信上保存的图片。请问您解决了吗？

**Comment by WanMeg** [comment]
> 我也发现了这个问题。我这边好像少的都是几M以上，从微信上保存的图片。请问您解决了吗？我发现同一张图片大小5M。从微信上保存至系统。自己的app里不会出现，但是从qq上保存。就出现了。这可能和微信有关系。试试把- (void)getAllPhotoAlbums:(void(^)(HXAlbumModel *firstAlbumModel))firstModel albums:(void(^)(NSArray *albums))albums isFirst:(BOOL)isFirst 方法中 的 option.sortDescriptors = @[[NSSortDescriptor sortDescriptorWithKey:@"creationDate" ascending:YES]]; 这行注释掉看。

嗯嗯谢谢，我这没有实际的去解决，那个用户后来没有再反馈过信息，所以就没再处理过，感谢解答，后面再遇到这种情况 我就试试你的办法
