### ISSUE TITLE
你好 YYWebImage 和 SD 不能去掉一个吗？

### ISSUE THREAD

**Issue by pikacode** [SilenceLove/HXPhotoPicker#245]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [1 ] 我已经查阅了已有的issue，没有找到相同的
- [ 1] 我想提出一个建议或bug，而不是问一个问题

### issue
同时依赖了2个图片库，导致我们App也必须安装2个库，同时用2个有什么必要性吗？

**Comment by SilenceLove** [comment]
pod 已去掉这两个库的依赖. 如果要使用网络图片需要自己导入

**Comment by pikacode** [comment]
非常感谢！
