### ISSUE TITLE
照片选择界面照片显示顺序与系统相机不一致【微信、微博等是与系统一致的】

### ISSUE THREAD

**Issue by MinMao-Hub** [SilenceLove/HXPhotoPicker#246]
从微信保存照片到本地，在系统相册中，显示为最后一张【按照添加到相册的时间排序】
在HXPhotoPicker中，这张照片被放到了照片的真实时间的位置，而不是添加到系统相册的时间。

**Comment by SilenceLove** [comment]
/**
 照片列表是否按照片日期排序  默认YES
 */
@property (assign, nonatomic) BOOL creationDateSort;
设置为NO就好了
