### ISSUE TITLE
用 hx_requestImageWithOriginal:YES completion 方法获取原图  图片方向由竖直变成横向

### ISSUE THREAD

**Issue by yy103zhu** [SilenceLove/HXPhotoPicker#247]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图

**Comment by chengongwen** [comment]
同问，lookLivePhoto live格式的图片方向由竖直变成横向

![image](https://user-images.githubusercontent.com/9940006/110084090-7f726000-7dca-11eb-97de-a5d7314a9493.png)

**Comment by chengongwen** [comment]
同问，lookLivePhoto live格式的图片方向由竖直变成横向，被旋转了

![image](https://user-images.githubusercontent.com/9940006/110084090-7f726000-7dca-11eb-97de-a5d7314a9493.png)

**Comment by chengongwen** [comment]
原图 - 发布后的图片
![image](https://user-images.githubusercontent.com/9940006/110085231-d593d300-7dcb-11eb-8525-f680443f4947.png)

![image](https://user-images.githubusercontent.com/9940006/110085241-d88ec380-7dcb-11eb-9306-a4559246f5b5.png)

**Comment by HanYaZhou1990** [comment]
我使用iPad，app只支持横向的情况下，进入拍照页面也存在此问题。

**Comment by HanYaZhou1990** [comment]
[
![image](https://user-images.githubusercontent.com/5268599/219596578-b3fc069a-69e9-463f-aee7-b5079beb511e.png)
](url)
