### ISSUE TITLE
我使用pod的时候报很多错误

### ISSUE THREAD

**Issue by DongfengWang123** [SilenceLove/HXPhotoPicker#249]
1.No known class method for selector 'sharedDownloader';
2.No known instance method for selector 'downloadImageWithURL:options:progress:completed:'
3.Unknown receiver 'SDWebImageDownloader'; did you mean 'SDWebImageManager'?Replace ;'SDWebImageDownloader' with 'SDWebImageManager';
4.Use of undeclared identifier 'SDWebImageDownloadToken';
5.Use of undeclared identifier 'token'

**Comment by SilenceLove** [comment]
yywebimage 需要是5.0以上的版本
