### ISSUE TITLE
选择多张照片内存不足闪退

### ISSUE THREAD

**Issue by WIndFate** [SilenceLove/HXPhotoPicker#250]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [x] 我已经查阅了已有的issue，没有找到相同的
- [x] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图

第一次在相册选择99张照片后添加到HXPhotoView，内存就已经976.1MB
了，退出画面内存不会降低。第二次进入相册再选择99张照片，就会内存不足闪退

**Comment by WIndFate** [comment]
<img width="384" alt="スクリーンショット 2019-06-27 14 10 39" src="https://user-images.githubusercontent.com/14509638/60237972-e812f500-98e5-11e9-9bac-04f583f9f3ef.png">

**Comment by SilenceLove** [comment]
用的是哪个版本的

**Comment by SilenceLove** [comment]
我用最新的demo2试了，选了200张没有出现你说的这种情况。你是不是在选择完成后做了什么处理

**Comment by WIndFate** [comment]
<img width="1050" alt="スクリーンショット 2019-06-28 18 15 31" src="https://user-images.githubusercontent.com/14509638/60331979-c478a900-99d0-11e9-8319-46966597d893.png">

最新版本的demo3会这样。
我这里需要加载显示网络图片（既已经上传过的照片），同时还能自己添加新照片，并把自己添加的新照片上传。

我先在
- (void)photoView:(HXPhotoView *)photoView changeComplete:(NSArray<HXPhotoModel *> *)allList photos:(NSArray<HXPhotoModel *> *)photos videos:(NSArray<HXPhotoModel *> *)videos original:(BOOL)isOriginal。 
里面移除网络图片，然后再调用
self.toolManager getSelectedImageList:tempPhotos requestType:HXDatePhotoToolManagerRequestTypeOriginal success:^(NSArray<UIImage *> *imageList)
取出自己添加的图片，然后要进行上传操作。这时候发现大量添加照片后，内存不会释放。

我试了下
- (void)getSelectedImageList:(NSArray<HXPhotoModel *> *)modelList success:(HXDatePhotoToolManagerGetImageListSuccessHandler)success failed:(HXDatePhotoToolManagerGetImageListFailedHandler)failed
这个方法不设置HXDatePhotoToolManagerRequestTypeOriginal，内存占用挺小的，可能是我选了原图的原因吗？

另外
allList hx_requestImageWithOriginal:isOriginal completion:^(NSArray<UIImage *> * _Nullable imageArray, NSArray<HXPhotoModel *> * _Nullable errorArray)
这个方法好像没法区分网络图片。
或者有其他方法可以在photoView中既能排除网络图片，又能获取自己添加的原图的方法吗？
