### ISSUE TITLE
HXPhotoPreviewViewController 顶部栏和底部栏能否支持自定义呢

### ISSUE THREAD

**Issue by PerfectisShittttttttttttttttttttttttttt** [SilenceLove/HXPhotoPicker#251]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题
![1B642C379BCEFBD1137D1BAE760A4107](https://user-images.githubusercontent.com/29631504/60328235-7196f580-99c0-11e9-83e5-23827a5a6dbf.jpg)

### issue
请尽量详细描述，建议附上截图

**Comment by PerfectisShittttttttttttttttttttttttttt** [comment]
我指的是样式问题

**Comment by houdzaiw** [comment]
> 我指的是样式问题

大佬，解决了吗，有没有什么好的解决方案？
