### ISSUE TITLE
请问怎么在点击图片右上角的删除按钮之后,图片数据删除之前自己决定要不要删除这张图,确定要删除时再删除图片数据

### ISSUE THREAD

**Issue by iotjin** [SilenceLove/HXPhotoPicker#253]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图

**Comment by SilenceLove** [comment]
HXPhotoView有属性删除图片时是否弹窗提醒
