### ISSUE TITLE
cell上HXPhotoView 刷新造成的删除失败

### ISSUE THREAD

**Issue by MrL90** [SilenceLove/HXPhotoPicker#255]
我是在cell上使用的HXPhotoView 模式是 HXPhotoViewPreViewShowStyleDefault  ，限定了最多9张图片
出现的问题是。当我选好了图片后。返回展示选中图片的界面。点击图片进入预览模式。又上角有删除按钮。不调用 setPhotoViewChangeHeightBlock 是没有问题的。如果少于6张或3张 就要刷新cell的高度。刷新的时候cell重新赋值。这样造成当前manager的 Array数据和 预览界面Array数据不相同。所以删除了。会出现问题

**Comment by SilenceLove** [comment]
cell重用问题
