### ISSUE TITLE
设置导航栏上面返回字体颜色失效

### ISSUE THREAD

**Issue by DongfengWang123** [SilenceLove/HXPhotoPicker#258]
_headImageManager.configuration.navigationBar = ^(UINavigationBar *navigationBar, UIViewController *viewController) {
            
            //设置导航上面返回箭头的颜色
            navigationBar.tintColor = [UIColor whiteColor];
            
        };
将导航栏上面的蓝色返回箭头和"取消"等按钮改为白色.使用上面的方法,首次进入的时候有效,再次进入的时候颜色任然是以前的蓝色.

**Comment by lizheftd** [comment]
我也遇到相同的问题.更改颜色后,第一次进入是对的,再次进入就回到之前的颜色了.请问你解决了吗
