### ISSUE TITLE
您好，请问如何通过URL单独使用HXVideoEditViewController呢？

### ISSUE THREAD

**Issue by brandy2015** [SilenceLove/HXPhotoPicker#262]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [x] 我已经查阅了已有的issue，没有找到相同的
- [x] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图

**Comment by brandy2015** [comment]
I got it.

let vc = HXVideoEditViewController()

        vc.model = HXPhotoModel(videoURL: FileURL)
        vc.avAsset = AVAsset(url: FileURL)
        vc.manager = self.manager
        vc.isInside = true
//        vc.outside = self.outside;

        present(vc, animated: true, completion: nil)

**Comment by SilenceLove** [comment]
控制器分类已加方法
