### ISSUE TITLE
2.3.1版本单独引入YYWebImage无法加载网络图片

### ISSUE THREAD

**Issue by doubletcjs** [SilenceLove/HXPhotoPicker#263]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [x] 我已经查阅了已有的issue，没有找到相同的
- [x] 我想提出一个建议或bug，而不是问一个问题

### issue

单独导入YYWebImage可正常加载网络图片，但是HXPhotoView无法加载网络图片。直接闪退，找不到对应的类

<img width="971" alt="Screen Shot 2019-07-19 at 3 16 51 PM" src="https://user-images.githubusercontent.com/4081010/61516911-9834d300-aa38-11e9-8aec-ba2620859d81.png">

 *** Assertion failure in -[UIImageView hx_setImageWithModel:original:progress:completed:], ../HXPhotoPicker/照片选择器/HXPhotoPicker/Category/UIImageView+HXExtension.m:122

**Comment by lanyuzx** [comment]
swift工程即使导入了SDWebImage和YYWebImage也是报这个错误
