### ISSUE TITLE
想问一下  有类似于微信那种长按录制视频不用滑动到视频才能录制的功能吗

### ISSUE THREAD

**Issue by zhangyutao12** [SilenceLove/HXPhotoPicker#264]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图

**Comment by yjm2657** [comment]
可以自定义相机页面,把相机的imageout和videoout,auidoinput,都加进去
