### ISSUE TITLE
多个图片一张一张上传后,代理方法中的是list包含的HXPhotoModel实体里面的属性没有赋值,都是null

### ISSUE THREAD

**Issue by JKbai** [SilenceLove/HXPhotoPicker#274]
![屏幕快照 2019-08-22 上午9 59 19](https://user-images.githubusercontent.com/20763750/63480246-bbcdbc00-c4c3-11e9-932c-ebe937ee9506.png)

场景:多张图片(一张一张)上传;(demo3),其他的demo也有这个问题;

步骤:
1.点击加号,上传一张图片,点击库里的完成;
2.再次点击加号上传第二张图片后, photos或者allList里面的model对象是两个,但是这两个对象对应的属性值(如:thumbPhoto, previewPhoto)为null

**Comment by errorUserInfo** [comment]
同样的问题

**Comment by errorUserInfo** [comment]
pod 'HXPhotoPicker','~> 2.1.9'有requestImageAfterFinishingSelection属性可以拿到值 不知道为什么后面去掉了这个属性

**Comment by errorUserInfo** [comment]
@SilenceLove

**Comment by SilenceLove** [comment]
requestImageAfterFinishingSelection   属性已恢复
