### ISSUE TITLE
相册选择能否仿闲鱼单独嵌入一个view里面  不使用presentViewController弹出界面  

### ISSUE THREAD

**Issue by qz-wzf** [SilenceLove/HXPhotoPicker#275]
类似闲鱼那种效果
![IMG_1967](https://user-images.githubusercontent.com/22139358/63754534-97207c80-c8e7-11e9-89a3-d69d6da5c0a6.PNG)

**Comment by caicai0525** [comment]
请问您实现这种效果了吗

**Comment by Lovezysong** [comment]
这也不是三个view啊？这应该是三个独立的子控制器，你直接使用HXAlbumListViewController再改改回调就可以了，
