### ISSUE TITLE
难道是Bug？

### ISSUE THREAD

**Issue by sharehoney** [SilenceLove/HXPhotoPicker#279]
第一次使用这个感觉不错的项目。

不过发现进行多次选择图片时，选中的图片会重复：

使用的方式 ————
  [photoList hx_requestImageWithOriginal:NO completion:^(NSArray<UIImage *> * _Nullable imageArray, NSArray<HXPhotoModel *> * _Nullable errorArray) {....}

关键部分 ————
我使用的是外部的一个数组houseImageArray  来存放 图片，
if ([weakSelf.houseImageArray containsObject:pickedImg] == NO) {
.....
}
这是造成重复的根源，估计 正确的比较方法 不会是这样。

—— 一时不知怎么是好。

———— 真希望有足够的时间来研究源码，更希望能得到作者的联系方法以求指点。

### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图

**Comment by SilenceLove** [comment]
hx_requestImageWithOriginal:NO completion这个方法回调里面去比较UIImage是没有用得，可以在远完照片返回model数组时，用数组存model数组。用model来判断是不是同一个

**Comment by sharehoney** [comment]
谢谢回复。HXPhotoModel好强大。

**Comment by Z-Victory** [comment]
![image](https://user-images.githubusercontent.com/15643266/66641103-a4ea5100-ec4c-11e9-91bc-97bbeac93069.png)
判断不出来，你那边可以吗
