### ISSUE TITLE
本地选择之后再次进入，HXPhotoModel中previewPhoto，thumbPhoto为空

### ISSUE THREAD

**Issue by hooyking** [SilenceLove/HXPhotoPicker#294]
第一次添加本地图片后，再次进去勾选其他的图或取消一部分以前勾选的图，点击完成后
- (void)photoView:(HXPhotoView *)photoView changeComplete:(NSArray<HXPhotoModel *> *)allList photos:(NSArray<HXPhotoModel *> *)photos videos:(NSArray<HXPhotoModel *> *)videos original:(BOOL)isOriginal
此方法中photos中HXPhotoModel中以前选中的previewPhoto和thumbPhoto都为空

**Comment by uaremylove** [comment]
我也出现了这种情况，请我怎么解决的
