### ISSUE TITLE
单选模式下选中一个视频能否自动取消选中上一个视频

### ISSUE THREAD

**Issue by Z-Victory** [SilenceLove/HXPhotoPicker#299]

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by SilenceLove** [comment]
单选模式选完了手动清空已选数组  [manager clearSelectedList]
