### ISSUE TITLE
老板, 这个怎么swift不能用啊...

### ISSUE THREAD

**Issue by ench44** [SilenceLove/HXPhotoPicker#30]
如题, 头文件仍在桥接文件里, 找不到模块...愁死人.

**Comment by LoveZYForever** [comment]
swift的桥接文件中![image](https://user-images.githubusercontent.com/18083149/29854447-a28ee158-8d78-11e7-8d06-9360db4a5153.png)引用 #import "HXPhotoView.h"   

之前有人这么解决的

**Comment by ench44** [comment]
这句话就是我在群里发的……




发自网易邮箱大师
在2017年08月30日 11:46，silence 写道：

swift的桥接文件中引用 #import "HXPhotoView.h"

之前有人这么解决的

**Comment by LoveZYForever** [comment]
这就尴尬了。。

**Comment by meilulu** [comment]
Swift确实用不了
