### ISSUE TITLE
使用完之后内存没有释放

### ISSUE THREAD

**Issue by harveyseeking** [SilenceLove/HXPhotoPicker#300]
iPhone XR使用HXPhotoView选择图片完成之后内存多了30M，退出页面内存还是那么多，请问要怎么释放内存，要手动设置delegate=nil吗
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图

**Comment by SilenceLove** [comment]
进入后台再进入前台

**Comment by harveyseeking** [comment]
谢谢解答
