### ISSUE TITLE
框架支持masonry布局吗？

### ISSUE THREAD

**Issue by yoriWang** [SilenceLove/HXPhotoPicker#303]
![image](https://user-images.githubusercontent.com/20896260/67547297-4edbda00-f731-11e9-8400-1dd2478d5c94.png)

![image](https://user-images.githubusercontent.com/20896260/67547316-5c915f80-f731-11e9-9130-d8a1d366c289.png)

这个视图我使用的是masonry布局的   发送按钮的top是equalTo(photoView.mas_bottom),结果如图，并不能正确约束

**Comment by SilenceLove** [comment]
在HXPhotoView的高度更新代理里更新布局
