### ISSUE TITLE
选图时 底部操作按钮HXPhotoBottomView看不到，无法点击完成按钮

### ISSUE THREAD

**Issue by RiberWang** [SilenceLove/HXPhotoPicker#304]
### HXPhotoView跳转HXPhotoViewController底部HXPhotoBottomView有时会不出现，选择图片时无法点击完成按钮

我这边尝试解决了一下：这个bottomView会存在在self.view上，但是就是看不见.我使用Xcode的试图调试功能，alpha为1，frame也是正确的。但是还是看不见！偶尔会复现，多次点击肯定会出现！

<img width="1274" alt="WX20191026-120044@2x" src="https://user-images.githubusercontent.com/13045019/67615624-49e65b80-f801-11e9-97ed-363863bd3a8c.png">

**Comment by Michaelyb520** [comment]
这个问题我也遇到了~

**Comment by RiberWang** [comment]
更新后解决了吗？

**Comment by SilenceLove** [comment]
是的
