### ISSUE TITLE
13.0+选择编辑图片的时候，图片取不到

### ISSUE THREAD

**Issue by zxmios** [SilenceLove/HXPhotoPicker#305]
![IMG_3002](https://user-images.githubusercontent.com/17398058/67658856-d033a680-f995-11e9-85c8-5a9e3807152b.PNG)
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图
发现问题出在HXPhotoEditViewController中的- (void)setupModel方法中，执行requestImageURLStartRequestICloud方法的时候failed返回的字典中PHContentEditingInputErrorKey，此时没有给originalImage赋值，所以bottomViewDidRestoreClick方法中self.imageView.image = self.originalImage;导致图片没有了，我现在处理的方法是在HXPhotoViewController的requestThumbImageCompletion回调中给model.tempImage赋值为image，不知是否正确：
 self.requestID = [self.model requestThumbImageCompletion:^(UIImage *image, HXPhotoModel *model, NSDictionary *info) {
            if (weakSelf.model == model) {
                weakSelf.imageView.image = image;
                model.tempImage = image;
                if (weakSelf.maskView.hidden) {
                    weakSelf.imageView.hidden = NO;
                    weakSelf.maskView.hidden = NO;
                    [UIView animateWithDuration:0.05 animations:^{
                        weakSelf.maskView.alpha = 1;
                        weakSelf.imageView.alpha = 1; 
                    }];
                }
            }
        }];

**Comment by SilenceLove** [comment]
可以，下个版本解决获取失败之后的处理
