### ISSUE TITLE
状态栏颜色问题。

### ISSUE THREAD

**Issue by Michaelyb520** [SilenceLove/HXPhotoPicker#307]
### 问题1：状态栏颜色问题异常

预览或者选择选择相册之前，状态栏白色。进入预览或者选择相册页面后，返回。状态栏颜色变成了黑色。异常出现！怎么结解决？

操作系统：iOS 13.0

![image](https://user-images.githubusercontent.com/9857312/67734403-f6ac1d00-fa3b-11e9-91ed-3a5706974662.png)

计入相册选择页面，状态栏bian变黑色了。

![image](https://user-images.githubusercontent.com/9857312/67734425-062b6600-fa3c-11e9-84de-d62264c88766.png)

返回时，状态栏边黑色了。。。。

![image](https://user-images.githubusercontent.com/9857312/67734478-29eeac00-fa3c-11e9-8364-367160589dca.png)

**Comment by SilenceLove** [comment]
- (void)photoViewPreviewDismiss:(HXPhotoView *)photoView {
    [self changeStatus];
}
- (void)photoViewDidCancel:(HXPhotoView *)photoView {
    [self changeStatus];
}
看demo2里面的这两个回调

**Comment by Michaelyb520** [comment]
如果想修改 导航栏颜色 以及状态来 按钮选项的 颜色，怎么操作~

**Comment by SilenceLove** [comment]
看配置类

**Comment by Michaelyb520** [comment]
通过 查配置类，发现底部 toolbar 按钮主题的 个个性化配置提供太少~

![image](https://user-images.githubusercontent.com/9857312/67758381-88398000-fa78-11e9-9ac0-d9a42b3097ab.png)

**Comment by SilenceLove** [comment]
#163 国际化问题

**Comment by SilenceLove** [comment]
底部按钮通过主题色设置
导航栏按钮颜色通过配置类, 导航栏的回调的UINavigationBar设置
