### ISSUE TITLE
相册选择控制器问题

### ISSUE THREAD

**Issue by Michaelyb520** [SilenceLove/HXPhotoPicker#308]
### 相册控制器第一次进入正常，就导航栏颜色异常。第二进入异常！

第一次进入：

![image](https://user-images.githubusercontent.com/9857312/67914522-5b49b200-fbcb-11e9-84f4-f5e2b666f4a1.png)

第二次进入：顶部无缘无故多出很大一片空白。底部工具栏不见了
![image](https://user-images.githubusercontent.com/9857312/67914454-22114200-fbcb-11e9-9f8d-4ff08f65d93d.png)

![image](https://user-images.githubusercontent.com/9857312/67914474-33f2e500-fbcb-11e9-9520-05b249efce6b.png)

### 真心搞不懂，间距哪里来的？？

![image](https://user-images.githubusercontent.com/9857312/67915367-ba102b00-fbcd-11e9-9b55-1b48b82d6b27.png)

**Comment by Michaelyb520** [comment]
### 关于导航栏的设置。建议在`HXPhotoViewController`和`HXPhotoPreviewViewController`控制器中加入下面代码。

```objc
if (self.manager.configuration.navigationBar) {
        self.manager.configuration.navigationBar(self.navigationController.navigationBar,self);
 }
```

**Comment by SilenceLove** [comment]
readme 有说明解决偏移问题
偏移参考 系统导航栏毛玻璃的问题

**Comment by Michaelyb520** [comment]
这个问题就是因为 设置 了 导航栏才导致的

```objc
_manager.configuration.navigationBar = ^(UINavigationBar *navBar, UIViewController *vc) {
            
           
            
            // 解决 translucent 设置为NO后，视图向下偏移的问题
            /navBar.translucent = NO;
            vc.extendedLayoutIncludesOpaqueBars = YES;
            vc.automaticallyAdjustsScrollViewInsets = NO;
            navBar.tintColor = appData_.whiteColor;
            navBar.barTintColor = appData_.themeColorHL;
};
```

如果 你设置  translucent 就不会。但是不设置 translucent 的话。导航栏会有半透明效果。和app整体导航栏配置不协调。需要怎么破
