### ISSUE TITLE
跟环信冲突了...

### ISSUE THREAD

**Issue by tingyuyisheng** [SilenceLove/HXPhotoPicker#31]
环信用的SDWEBIMAGE只支持3.8...你的需要4.0.0...我只想说..环信那个坑逼..

**Comment by LoveZYForever** [comment]
你可以把4.0.0 版本的方法换成3.8的 ,没什么影响

**Comment by tingyuyisheng** [comment]
恩恩,我把你里面的SD注释掉了

**Comment by liuchunlao** [comment]
@tingyuyisheng 怎么注释的？将sd_删除了还是怎么样？

**Comment by tingyuyisheng** [comment]
把报错的地方注释掉

**Comment by liuchunlao** [comment]
硬解，确实有效！
如何是通过cocoapos集成该咋整？

**Comment by tingyuyisheng** [comment]
不用cocoapods,直接拖进项目里,因为咱貌似用不到网络图片功能,用到在思考解决方案.哈哈
