### ISSUE TITLE
从HXPhotoModel中获取UIImage时 会把HXPhotoView中的那个加号图标也获取到

### ISSUE THREAD

**Issue by sharehoney** [SilenceLove/HXPhotoPicker#310]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [x] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图

代码如下：
        for (HXPhotoModel *model in self.photoManager.afterSelectedArray) {
            
            [[PHImageManager defaultManager] requestImageForAsset:model.asset
                                                       targetSize:size
                                                      contentMode:PHImageContentModeAspectFit
                                                          options:nil
                                                    resultHandler:^(UIImage * _Nullable result, NSDictionary * _Nullable info) {
                                                        if (result) {
                                                            [self uploadPictureNetActionWithImage:result];
                                                        }
                                                        
                                                    }];
            
        }
————从HXPhotoModel中获取UIImage时 会把HXPhotoView中的那个加号图标也获取到，有办法解决吗？
多谢。

**Comment by SilenceLove** [comment]
![image](https://user-images.githubusercontent.com/18083149/71054402-d4599480-218c-11ea-9425-fd662e4e6829.png)
根据type判断过滤掉
