### ISSUE TITLE
最新更新的库问题

### ISSUE THREAD

**Issue by Michaelyb520** [SilenceLove/HXPhotoPicker#312]
## 最新更新的库问题
请尽量详细描述，建议附上截图

### 1. 照片选择界面单选框突然变大了额~以前正常的圈和选中后的一样大，现在看起来很难看

<img width="669" alt="WX20191122-102704@2x" src="https://user-images.githubusercontent.com/9857312/69392982-d6a60b80-0d12-11ea-869e-70c0c67bd606.png">

### 2. 相册列表cell我们可以自定义吗？比如类似微信的相册列表。

<img width="433" alt="WX20191121-181915@2x" src="https://user-images.githubusercontent.com/9857312/69393005-ede4f900-0d12-11ea-9c7f-735ae7e05bb3.png">

微信相册列表cell文字的排列方式：

<img width="746" alt="WX20191122-102811@2x" src="https://user-images.githubusercontent.com/9857312/69393036-035a2300-0d13-11ea-9475-0f85af05c6ab.png">

**Comment by SilenceLove** [comment]
什么情况下这个圆圈会变大? demo运行正常的
