### ISSUE TITLE
在UITableviewCell中使用Masonry会内存溢出

### ISSUE THREAD

**Issue by harveyseeking** [SilenceLove/HXPhotoPicker#315]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图
在UITableviewCell中使用Masonry布局HXPhotoView会导致内存涨到几百兆然后崩溃，2.3.6和2.3.8试了都会

**Comment by DongfengWang123** [comment]
我也遇到了同样的问题.
1.创建onePhotoView的时候,起始坐标设置为CGRectZero,然后使用Masonry对其重新布局.当单击onePhotoView进行选择图片的时候,CPU就会高达100%现象.直接就卡死了
-(HXPhotoView *)onePhotoView
{
    if (!_onePhotoView)
    {
        _onePhotoView=[[HXPhotoView alloc] initWithFrame:CGRectZero manager:self.oneManager];
        _onePhotoView.outerCamera = YES;
       _onePhotoView.delegate = self;
    }
    
    return _onePhotoView;
}

**Comment by harveyseeking** [comment]
感谢作者一直更新
