### ISSUE TITLE
请问如何获取到相册中照片的本地URL？

### ISSUE THREAD

**Issue by lumianie** [SilenceLove/HXPhotoPicker#316]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [x] 我已经查阅了已有的issue，没有找到相同的
- [x] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图
我想将照片数组URL存储在本地沙盒中，到那时并没有找到相关的方法或者属性获取到照片URL

**Comment by yjjwxq** [comment]
同问

**Comment by xiaohange** [comment]
同问

**Comment by SilenceLove** [comment]
model里已有方法
