### ISSUE TITLE
iOS11下，导航栏出现上移

### ISSUE THREAD

**Issue by wongwenlei** [SilenceLove/HXPhotoPicker#32]
导航栏上移，好像是automaticallyAdjustsScrollViewInsets这个在iOS11下面失效导致的？

**Comment by jkwf** [comment]
contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;可以换成这个试试，不过注意加上版本判断

**Comment by wongwenlei** [comment]
好的，谢谢回复

**Comment by JLLJHD** [comment]
在哪里加啊

**Comment by yxj19950701** [comment]
解决了吗？
