### ISSUE TITLE
在录制视频时在听书,混合时录制能成功,但是单视频录制失败

### ISSUE THREAD

**Issue by linhongmin1027** [SilenceLove/HXPhotoPicker#320]
项目中有个短视频录制模块，发现在听书之类的时候，无法录制视频，但是测试带有图片和视频一起混合时能够录制视频。版本为2.3.7
测试HXPhotoPicker的demo也出现相同情况。希望可以优化一下
![IMG_2475](https://user-images.githubusercontent.com/20904302/70990171-ee00ca80-20ff-11ea-9a49-f55242c892b3.PNG)

**Comment by SilenceLove** [comment]
最好发一下错误信息，可能是因为不能同时进行的原因

**Comment by linhongmin1027** [comment]
AVCaptureFileOutputRecordingDelegate回调error
Error Domain=AVFoundationErrorDomain Code=-11800 "这项操作无法完成" UserInfo={NSLocalizedFailureReason=发生未知错误（-12780）, NSLocalizedDescription=这项操作无法完成, NSUnderlyingError=0x282fb8570 {Error Domain=NSOSStatusErrorDomain Code=-12780 "(null)"}}
主要是图片加视频混合切换时，是可以录制视频的

**Comment by linhongmin1027** [comment]
> 最好发一下错误信息，可能是因为不能同时进行的原因

AVCaptureFileOutputRecordingDelegate回调error
Error Domain=AVFoundationErrorDomain Code=-11800 "这项操作无法完成" UserInfo={NSLocalizedFailureReason=发生未知错误（-12780）, NSLocalizedDescription=这项操作无法完成, NSUnderlyingError=0x282fb8570 {Error Domain=NSOSStatusErrorDomain Code=-12780 "(null)"}}
主要是图片加视频混合切换时，是可以录制视频的

**Comment by SilenceLove** [comment]
什么听书app

**Comment by linhongmin1027** [comment]
随便一个都是的，好像直播也有这个问题，我当时用的是起点阅读
