### ISSUE TITLE
ipad拍照界面

### ISSUE THREAD

**Issue by bingolib** [SilenceLove/HXPhotoPicker#331]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图
我的应用只支持ipad横屏，当跳转相机界面拍照时 界面始终是反转的。请问该怎么解决

**Comment by SilenceLove** [comment]
自带的相机不支持旋转，如果想可以旋转可以使用自定义相机功能替换成系统的相机

**Comment by HanYaZhou1990** [comment]
我也有同样问题

https://user-images.githubusercontent.com/5268599/219610808-a67e0244-3b01-44a4-9309-a87adac7621e.mp4

![3131676623516_ pic](https://user-images.githubusercontent.com/5268599/219610850-d88cdd80-5d56-4215-9477-6c954a5bd834.jpg)
