### ISSUE TITLE
ios 13真机会卡死UI界面

### ISSUE THREAD

**Issue by langlanglang** [SilenceLove/HXPhotoPicker#333]
ios 13真机上会卡死UI界面，根本动不了，再模拟器和ios13以下版本，正常。

![1583551872582](https://user-images.githubusercontent.com/21981911/76135971-37114c80-6067-11ea-93a3-1d27f9b91d5e.jpg)

**Comment by sharehoney** [comment]
我遇到的情况是会卡死一段时间，5、6秒钟吧，然后就好了。
开始还以为是我的照片太多了——接近6000张。
