### ISSUE TITLE
增加其他第三方编辑图片出现问题

### ISSUE THREAD

**Issue by Jasting** [SilenceLove/HXPhotoPicker#338]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [x] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
<img width="308" alt="屏幕快照 2020-03-19 下午6 03 55" src="https://user-images.githubusercontent.com/33852553/77055755-6c754d00-6a0c-11ea-95d3-1365cb73d773.png">
<img width="300" alt="屏幕快照 2020-03-19 下午6 04 18" src="https://user-images.githubusercontent.com/33852553/77055818-844cd100-6a0c-11ea-81c9-5addd5b2771a.png">
<img width="299" alt="屏幕快照 2020-03-19 下午6 04 39" src="https://user-images.githubusercontent.com/33852553/77055887-9890ce00-6a0c-11ea-9288-cea1b78b6ca0.png">
<img width="290" alt="屏幕快照 2020-03-19 下午6 04 55" src="https://user-images.githubusercontent.com/33852553/77055967-b6f6c980-6a0c-11ea-885a-b9b350d19f1d.png">

请尽量详细描述，建议附上截图

**Comment by SilenceLove** [comment]
第三方库的问题
