### ISSUE TITLE
请导入YYWebImage/SDWebImage后再使用网络图片功能

### ISSUE THREAD

**Issue by lanyuzx** [SilenceLove/HXPhotoPicker#344]
### 请导入YYWebImage/SDWebImage后再使用网络图片功能
作者大大,我用你的demo 删除HXPhotoPicker,改为pod导入,然后我分别pod SDWebImage和 手动导入SDWebImage ,都是找不到,是怎么回事呢? 很是费解

**Comment by 1518880611** [comment]
对对，我正想来说这个问题，我也遇到了，跪求大佬解决

**Comment by Wilshion** [comment]
同问，HXPhotoPicker使用最新的2.4.2版本，工程之前就有SDWebImage5.0版本，提示【请导入YYWebImage/SDWebImage后再使用网络图片功能】

**Comment by lanyuzx** [comment]
> 同问，HXPhotoPicker使用最新的2.4.2版本，工程之前就有SDWebImage5.0版本，提示【请导入YYWebImage/SDWebImage后再使用网络图片功能】

我用的就是他的demo  pod最新的,就是找不到,系统这个__has_include 监测不出来

**Comment by ywdonga** [comment]
我也遇到了，很尴尬呀

**Comment by CoderXSLee** [comment]
我也遇到了～各位怎么解决的？

**Comment by Sum123** [comment]
我也遇到了～各位怎么解决的？

**Comment by wangwanjie** [comment]
卧槽，我还以为就我一个人遇到，我现在也遇到了，很郁闷啊，作者能看到吗

**Comment by SilenceLove** [comment]
我试了几次都是可以的
如果HXPhotoPicker为pod导入的那么YY或者SD也必须是pod导入的否则会找不到

**Comment by CoderXSLee** [comment]
cocoapods 1.8.4

**Comment by CoderXSLee** [comment]
cocoapods 1.8.4
macOS 10.15.4
Xcode 11.4.1

pod SDWebImage
pod HXPhotoPicker

我这边是找不到，各种方式尝遍了。最终全部手动导入的才解决。

**Comment by wangwanjie** [comment]
> 我试了几次都是可以的
> 如果HXPhotoPicker为pod导入的那么YY或者SD也必须是pod导入的否则会找不到

我正常使用也没有问题，是在添加自定义 model 时候出现的

**Comment by Wilshion** [comment]
> 我试了几次都是可以的
> 如果HXPhotoPicker为pod导入的那么YY或者SD也必须是pod导入的否则会找不到

我是在使用预览网络图片（单独使用场景）的时候遇到的，其中有用到HXCustomAssetModel。然后就提示【请导入YYWebImage/SDWebImage后再使用网络图片功能】。

**Comment by wangwanjie** [comment]
> HXCustomAssetModel

是的，我也是用 HXCustomAssetModel 才出现

**Comment by Sum123** [comment]
用到HXCustomAssetModel预览网络图片的时候确实是会报错

**Comment by wangwanjie** [comment]
作者这是不解决一下吗。。

**Comment by zR-Zr** [comment]
遇到了.....

**Comment by Wilshion** [comment]
这个问题，作者再帮忙看看吧，感觉确实不少人遇到了

**Comment by Wilshion** [comment]
@SilenceLove

**Comment by SilenceLove** [comment]
@Wilshion 最新版2.4.4有这个问题?

**Comment by Wilshion** [comment]
> @Wilshion 最新版2.4.4有这个问题?

作者你好，刚才试了下，升级到2.4.4，现象还有，提示【请导入YYWebImage/SDWebImage后再使用网络图片功能，HXPhotoPicker为pod导入的那么YY或者SD也必须是pod导入的否则会找不到】。

**Comment by Wilshion** [comment]
@SilenceLove 
作者你好，刚才试了下，升级到2.4.4，现象还有，提示【请导入YYWebImage/SDWebImage后再使用网络图片功能，HXPhotoPicker为pod导入的那么YY或者SD也必须是pod导入的否则会找不到】。

**Comment by Wilshion** [comment]
@SilenceLove 
作者你好，刚升级了2.4.4，测试了下，问题还是存在，不过看到你改了错误信息【请导入YYWebImage/SDWebImage后再使用网络图片功能，HXPhotoPicker为pod导入的那么YY或者SD也必须是pod导入的否则会找不到】。

**Comment by SilenceLove** [comment]
@Wilshion 都是pod导入的吗?

**Comment by Wilshion** [comment]
@SilenceLove 是的，都是pod导入的
![image](https://user-images.githubusercontent.com/9622345/83373453-f5403a00-a3fa-11ea-8647-322045747b32.png)

**Comment by SilenceLove** [comment]
@Wilshion 看在只能pod加上SD了，下个版本加上

**Comment by Wilshion** [comment]
@SilenceLove 好的，感谢

**Comment by SilenceLove** [comment]
@Wilshion v2.4.5
 pod 'HXPhotoPicker' 不依赖第三方
        'HXPhotoPicker/SDWebImage' 依赖SD v5.0
        'HXPhotoPicker/YYWebImage' 依赖YY v1.05
搜不到库执行 pod repo update
![image](https://user-images.githubusercontent.com/18083149/83506944-69153c00-a4fa-11ea-8437-e99c7a9ba196.png)

**Comment by kuyona** [comment]
![截屏2020-06-2410 08 20](https://user-images.githubusercontent.com/18322574/85489555-bf116700-b602-11ea-983d-e7ef976da188.png)
![截屏2020-06-2410 09 00](https://user-images.githubusercontent.com/18322574/85489560-c0db2a80-b602-11ea-869e-ab8f312af8f9.png)

pod导入sd跟hx 使用时还是找不到 崩溃

**Comment by Wilshion** [comment]
@kuyona 我最后是放弃使用pod，换成导入源码的方式，你可以试试，后续作者如果有新版本修复了，可以换回来
