### ISSUE TITLE
希望视频播放能增加暂停/恢复/进度条拖动

### ISSUE THREAD

**Issue by Roen-Ro** [SilenceLove/HXPhotoPicker#346]
### 如题
非常感谢程序员们的辛勤付出造出了这么一款强大的工具

希望在预览视频的时候增加播放、暂停、拖动功能

**Comment by SilenceLove** [comment]
至于在选择完之后，在HXPhotoView上预览时设置
/**  预览大图时的风格样式  */
@property (assign, nonatomic) HXPhotoViewPreViewShowStyle previewStyle;
HXPhotoViewPreViewShowStyleDark     //!< 暗黑，此模式下视频会有进度条
