### ISSUE TITLE
2.4.2版本的HXPhotoManager的问题

### ISSUE THREAD

**Issue by Michael0930** [SilenceLove/HXPhotoPicker#347]
作者大大：
Version2.4.2，在同一个ViewController里面不同位置分别调用两次照片选择器，两次设置的HXPhotoManagerSelectedType分比为图片和视频，第二次调用会沿用第一次调用的HXPhotoManagerSelectedType设置，也就是如果第一次只加载图片第二次也只加载图片（而设置的HXPhotoManagerSelectedType为Video），如果第一次加载视频第二次也只加载视频（而设置的HXPhotoManagerSelectedType为Photo）
此问题在Version2.3.8不出现

**Comment by rango123456** [comment]
我也遇到同样的问题
