### ISSUE TITLE
关于requestImageAfterFinishingSelection设置成YES之后，导出网络视频会堵住主线程的问题

### ISSUE THREAD

**Issue by CHEN031226** [SilenceLove/HXPhotoPicker#348]
作者您好：
requestImageAfterFinishingSelection参数设置为YES之后，添加了几个HXCustomAssetModel后再添加图片资源 ，因为这个参数，HXCustomAssetModel的NetworkVideoURL也要跟着导出一次，然后这边有这样的警告：

- Main Thread Checker: UI API called on a background thread: -[UIViewController navigationController]
- 0x0000000102770f60 -[HXPhotoViewController dismissVC] + 320
-  0x0000000102770bf0 __50-[HXPhotoViewController afterFinishingGetVideoURL]_block_invoke + 232

而且我也不想网络视频跟着导出一回，请问这里能否优化一下？

**Comment by CHEN031226** [comment]
Thread name: com.ibireme.webimage.request, Queue name: com.apple.root.default-qos.overcommit, QoS: 0

好像一些在主线程的做的事情跑到 com.ibireme.webimage.request这边去了 所以导致卡顿，请问是什么原因造成的？

**Comment by SilenceLove** [comment]
如果网络图片没有下载完成，会去先下载网络图片。没有卡顿只是无法操作

**Comment by CHEN031226** [comment]
> 如果网络图片没有下载完成，会去先下载网络图片。没有卡顿只是无法操作

我这边是让他跳回主线程防止卡顿导致程序崩溃，但是这个问题能否真正得到解决呢？

**Comment by SilenceLove** [comment]
![image](https://user-images.githubusercontent.com/18083149/83393452-61399700-a429-11ea-8231-44b782c50020.png)
在NSArray+HXExtension里吧这段代码注释掉就可以了

**Comment by CHEN031226** [comment]
> ![image](https://user-images.githubusercontent.com/18083149/83393452-61399700-a429-11ea-8231-44b782c50020.png)
> 在NSArray+HXExtension里吧这段代码注释掉就可以了

您好，我已经注释掉        if (photoModel.networkPhotoUrl) 里面的代码，但是还是有个菊花在那里转着，请问是还需要补上什么代码吗？

**Comment by SilenceLove** [comment]
把if也去掉



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: CHEN031226 <notifications@github.com&gt;
发送时间: 2020年6月1日 17:14
收件人: SilenceLove/HXPhotoPicker <HXPhotoPicker@noreply.github.com&gt;
抄送: silence <294005139@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[SilenceLove/HXPhotoPicker] 关于requestImageAfterFinishingSelection设置成YES之后，导出网络视频会堵住主线程的问题 (#348)





  

 在NSArray+HXExtension里吧这段代码注释掉就可以了
  
您好，我已经注释掉        if (photoModel.networkPhotoUrl) 里面的代码，但是还是有个菊花在那里转着，请问是还需要补上什么代码吗？

**Comment by CHEN031226** [comment]
> 把if也去掉 发自我的iPhone
> […](#)

好的 可以了 谢谢
