### ISSUE TITLE
2.4.2及2.4.3 版本demo中，demo9中，选择图片大于3张，界面卡死

### ISSUE THREAD

**Issue by Wilshion** [SilenceLove/HXPhotoPicker#354]
问题描述：
如题，demo9中，cell上添加照片，超过3张界面卡死。
环境：
1.Xcode版本 11.3.1
2.模拟器：iPhone11，13.3
3.是否必现：是
4.验证方式：下载最新版本demo，运行后打开demo9，在第二个或者第三个cell上去选择照片，当选择大于三张时候点击【完成】按钮，返回不了，界面卡死。如下图，选择超过3张后界面卡死
![2020-05-23 16 04 33](https://user-images.githubusercontent.com/9622345/82725518-0bba0780-9d10-11ea-81fb-c5b29a0f7394.gif)

**Comment by SilenceLove** [comment]
没办法重现，你的属性怎么设置的？

**Comment by Wilshion** [comment]
> 没办法重现，你的属性怎么设置的？

没修改任何东西，就是打开demo运行，不知道你所指的属性是指啥呢

**Comment by SilenceLove** [comment]
发现问题了，后续版本解决
