### ISSUE TITLE
hx_presentPreviewPhotoControllerWithManager

### ISSUE THREAD

**Issue by a758209678** [SilenceLove/HXPhotoPicker#356]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [√ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图
单独使用这个方法跳转图片浏览器时，过渡动画的初始位置是屏幕的左上角而不是所点击图片的位置。

**Comment by SilenceLove** [comment]
参考Demo12的代码
