### ISSUE TITLE
 pod 'HXPhotoPicker/SDWebImage', '~> 2.4.5'，HXPhotoView的添加图片不显示

### ISSUE THREAD

**Issue by Wilshion** [SilenceLove/HXPhotoPicker#358]
作者您好，使用Pod导入新版本2.4.5，然后在页面中使用HXPhotoView，➕图片不显示，但是点击事件还有，而如果换成导入pod 'HXPhotoPicker', '~> 2.4.5'，这个➕会显示。（难道我使用姿势不对？）
测试流程：
1.新建工程
2.创建profile
3.两种方式挨个导入测试。

展示下我的pod 文件内容（ViewController.m文件代码不变）
![image](https://user-images.githubusercontent.com/9622345/83612943-aab6ed00-a5b5-11ea-9198-7ef43e016188.png)

下面分别展示两个导入方式的结果。

下面gif图片展示的是导入 pod 'HXPhotoPicker/SDWebImage', '~> 2.4.5' 出现的问题。
![2020-06-03 16 00 32](https://user-images.githubusercontent.com/9622345/83612588-2f553b80-a5b5-11ea-9be3-9b6794ab78f2.gif)

下面图片展示的是导入pod 'HXPhotoPicker', '~> 2.4.5' ，这个是正常的。
![2020-06-03 16 14 19](https://user-images.githubusercontent.com/9622345/83612693-51e75480-a5b5-11ea-897c-91467d637d60.gif)

**Comment by SilenceLove** [comment]
删除pod 然后再重新pod 一次

**Comment by Wilshion** [comment]
@SilenceLove 作者您好，我删除本地工程podfile文件，然后删除xcworkspace，然后重新touch podfile，编辑新的podfile，然后pod install，然后好像还是不行，作者你试了可以吗

**Comment by SilenceLove** [comment]
试了，可以。pod先删掉。然后再添加进去



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Wilshion <notifications@github.com&gt;
发送时间: 2020年6月5日 17:27
收件人: SilenceLove/HXPhotoPicker <HXPhotoPicker@noreply.github.com&gt;
抄送: silence <294005139@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[SilenceLove/HXPhotoPicker]  pod 'HXPhotoPicker/SDWebImage', '~&gt; 2.4.5'，HXPhotoView的添加图片不显示 (#358)





 
@SilenceLove 作者您好，我删除本地工程podfile文件，然后删除xcworkspace，然后重新touch podfile，编辑新的podfile，然后pod install，然后好像还是不行，作者你试了可以吗

**Comment by wangwanjie** [comment]
> @SilenceLove 作者您好，我删除本地工程podfile文件，然后删除xcworkspace，然后重新touch podfile，编辑新的podfile，然后pod install，然后好像还是不行，作者你试了可以吗

加载图片未出现，可以通过调试发现 photoView 的 collectionView frame 为空（我是使用约束布局），这个作者可以修复，你也可以和我一样先这牙膏解决，给 collectionView 增加约束，就 ok 了
```ObjC
    [self.photoView.collectionView mas_remakeConstraints:^(MASConstraintMaker *make) {
        make.edges.equalTo(self.photoView);
    }];
```

**Comment by Wilshion** [comment]
@wangwanjie 有用，谢啦，先这么解决吧，哈哈。

**Comment by Wilshion** [comment]
@wangwanjie 你有没有遇到这个问题，选择照片的页面，拍照的图标不见了（和加号图片问题类似），然后每个照片的右上角的小圆圈也不见了？？具体见下图
![image](https://user-images.githubusercontent.com/9622345/84476902-63211700-acc1-11ea-9500-ae0d723f850f.png)

**Comment by SilenceLove** [comment]
如果都是pod导入的提示找不到话，先将SD或YY 和 HX 的pod全部移除，再 pod install
然后再 pod HXPhotoPicker/SDWebImage 或者 HXPhotoPicker/YYWebImage
