### ISSUE TITLE
使用约束布局时时，传入本地\网络图片时，高度计算错误

### ISSUE THREAD

**Issue by wangwanjie** [SilenceLove/HXPhotoPicker#359]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图

版本 2.4.5
约束布局
传入自定义图片，由于 photoView.frame 初始宽度为0，导致 itemW 计算不正确
![image](https://user-images.githubusercontent.com/15172899/83938990-c74c6280-a80b-11ea-81ab-c3a4472b1f5f.png)
从而导致第一次触发 - (void)photoView:(HXPhotoView *)photoView updateFrame:(CGRect)frame 的 frame 高度不正确

**Comment by SilenceLove** [comment]
[self.photoView refreshView];
添加完需要刷新photoView
