### ISSUE TITLE
图片和视频分开选择的问题

### ISSUE THREAD

**Issue by Arise903** [SilenceLove/HXPhotoPicker#363]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### [issue](url)
请尽量详细描述，建议附上截图

图片和视频分开选择，视频数量限制为1个，已选择的图片数量一旦大于1，就选择不了视频了。
代码如下：

   if (button == _toolbarPictureButton) {
        
        self.manager.type = HXPhotoManagerSelectedTypePhoto;
        

        
        [self hx_presentSelectPhotoControllerWithManager: self.manager didDone:^(NSArray<HXPhotoModel *> * _Nullable allList, NSArray<HXPhotoModel *> * _Nullable photoList, NSArray<HXPhotoModel *> * _Nullable videoList, BOOL isOriginal, UIViewController * _Nullable viewController, HXPhotoManager * _Nullable manager) {

             } cancel:^(UIViewController * _Nullable viewController, HXPhotoManager * _Nullable manager) {
                 

             }];
        
       

        
    } else if (button == _toolbarAtButton) {
        
  
        self.manager.type = HXPhotoManagerSelectedTypeVideo;
        
        
        [self hx_presentSelectPhotoControllerWithManager: self.manager didDone:^(NSArray<HXPhotoModel *> * _Nullable allList, NSArray<HXPhotoModel *> * _Nullable photoList, NSArray<HXPhotoModel *> * _Nullable videoList, BOOL isOriginal, UIViewController * _Nullable viewController, HXPhotoManager * _Nullable manager) {

          
            [self.myTableView reloadRowsAtIndexPaths:@[[NSIndexPath indexPathForRow:2 inSection:0]] withRowAnimation:0];

        } cancel:^(UIViewController * _Nullable viewController, HXPhotoManager * _Nullable manager) {

        }];
        

-(HXPhotoManager *)manager {
    
    
    if (!_manager) {
        
        _manager= [[HXPhotoManager alloc]init];
        _manager.configuration.openCamera = YES;
        _manager.configuration.photoMaxNum = 9;
        _manager.configuration.videoMaxNum = 1;
        _manager.configuration.maxNum = 9;
            _manager.configuration.videoMinimumSelectDuration = 5;
            _manager.configuration.videoMaximumDuration = 180;
            _manager.configuration.lookLivePhoto = YES;
            _manager.configuration.saveSystemAblum = YES;
            _manager.configuration.selectTogether = YES;
            _manager.configuration.creationDateSort = YES;
            _manager.configuration.videoMaximumSelectDuration = 180;
           _manager.configuration.videoMinimumSelectDuration = 5;
        
    }
    
    
    return _manager;
    
    
    
    
    
}

**Comment by MusicOnMyMind** [comment]
> ### 感谢提交问题
> 提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容
> 
> ### 查看README、配置类HXPhotoConfiguration
> * [ ]  我已经查阅了已有的issue，没有找到相同的
> * [ ]  我想提出一个建议或bug，而不是问一个问题
> 
> ### [issue](url)
> 请尽量详细描述，建议附上截图
> 
> 图片和视频分开选择，视频数量限制为1个，已选择的图片数量一旦大于1，就选择不了视频了。
> 代码如下：
> 
> if (button == _toolbarPictureButton) {
> 
> ```
>     self.manager.type = HXPhotoManagerSelectedTypePhoto;
>     
> 
>     
>     [self hx_presentSelectPhotoControllerWithManager: self.manager didDone:^(NSArray<HXPhotoModel *> * _Nullable allList, NSArray<HXPhotoModel *> * _Nullable photoList, NSArray<HXPhotoModel *> * _Nullable videoList, BOOL isOriginal, UIViewController * _Nullable viewController, HXPhotoManager * _Nullable manager) {
> 
> 
>          } cancel:^(UIViewController * _Nullable viewController, HXPhotoManager * _Nullable manager) {
>              
> 
> 
>          }];
>     
>    
> 
> 
>     
> } else if (button == _toolbarAtButton) {
>     
> 
>     self.manager.type = HXPhotoManagerSelectedTypeVideo;
>     
>     
>     [self hx_presentSelectPhotoControllerWithManager: self.manager didDone:^(NSArray<HXPhotoModel *> * _Nullable allList, NSArray<HXPhotoModel *> * _Nullable photoList, NSArray<HXPhotoModel *> * _Nullable videoList, BOOL isOriginal, UIViewController * _Nullable viewController, HXPhotoManager * _Nullable manager) {
> 
>       
>         [self.myTableView reloadRowsAtIndexPaths:@[[NSIndexPath indexPathForRow:2 inSection:0]] withRowAnimation:0];
> 
> 
>     } cancel:^(UIViewController * _Nullable viewController, HXPhotoManager * _Nullable manager) {
> 
>     }];
> ```
> 
> -(HXPhotoManager *)manager {
> 
> ```
> if (!_manager) {
>     
>     _manager= [[HXPhotoManager alloc]init];
>     _manager.configuration.openCamera = YES;
>     _manager.configuration.photoMaxNum = 9;
>     _manager.configuration.videoMaxNum = 1;
>     _manager.configuration.maxNum = 9;
>         _manager.configuration.videoMinimumSelectDuration = 5;
>         _manager.configuration.videoMaximumDuration = 180;
>         _manager.configuration.lookLivePhoto = YES;
>         _manager.configuration.saveSystemAblum = YES;
>         _manager.configuration.selectTogether = YES;
>         _manager.configuration.creationDateSort = YES;
>         _manager.configuration.videoMaximumSelectDuration = 180;
>        _manager.configuration.videoMinimumSelectDuration = 5;
>     
> }
> 
> 
> return _manager;
> ```
> 
> }

这个需要自己定义属性来存储当前选了几张图片和几个视频，然后与maxNum计算后得出还可选几张图片和几个视频再赋值给photoMaxNum及videoMaxNum
