### ISSUE TITLE
关于添加新图片资源后，下标获取不准确的问题。

### ISSUE THREAD

**Issue by CHEN031226** [SilenceLove/HXPhotoPicker#367]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图

您好！
我发现一个问题，就是在设置完网络图片后，我添加了新的图片资源。然后取消选中原先的网络图片，只剩下那一个新的图片。然后提交数组的时候，抓取到的下标selectedIndex不是0。这是什么问题导致的？

- (BOOL)isEqualPhotoModel:(HXPhotoModel *)photoModel，我是用这个方法来判断这两个模型是不是一样的（您应该也知道每次走changeComplete的代理UIImage的地址都会变化），所以没有更新到下标。
麻烦看到这个问题的时候能帮我解答一下，谢谢！

**Comment by SilenceLove** [comment]
能提供截图吗？

**Comment by CHEN031226** [comment]
> 能提供截图吗？

好像没办法上传图片，我就复制一下我添加资源的代码吧

                __block BOOL isExist = NO;
                [self.selectedPhotos enumerateObjectsUsingBlock:^(HXPhotoModel*  _Nonnull obj, NSUInteger idx, BOOL * _Nonnull stop) {
                    if ([obj isEqualPhotoModel:pp] ) {
                        *stop = YES;
                        isExist = YES;
                    }
                    
                }];
                
                if (!isExist) {//如果不存在就添加进去
                    
                    [self.selectedPhotos addObject:pp];
                }

情景就是，
1.添加HXCustomAssetModel的模型（self.selectedPhotos为0）
2.选择添加新的本地图片（self.selectedPhotos为1，下标为1）
3.再打开图片列表，取消了HXCustomAssetModel的选中状态（新图片的下标应该为0）
4.进入到判断，由于[obj isEqualPhotoModel:pp]他可以通过，就跳出了这个循环。所以导致self.selectedPhotos里那个元素的下标还是和原来的一样是1，但是界面上他的下标是0.
5.目前我的解决办法就是再添加这一段
 
 if (obj.selectedIndex != pp.selectedIndex) {
                            obj.selectedIndex = pp.selectedIndex;
                            obj.selectIndexStr = pp.selectIndexStr;
                        }

**Comment by SilenceLove** [comment]
添加model必须按manager的方法添加，自己添加的会出现这些问题
