### ISSUE TITLE
相册预览视频  很多视频报错  AVPlayerItemStatusFailed  加载失败

### ISSUE THREAD

**Issue by huohongxu** [SilenceLove/HXPhotoPicker#370]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration / HXPhotoEditConfiguration
- [x] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图

**Comment by SilenceLove** [comment]
具体报错信息截图有么

**Comment by huohongxu** [comment]
<img width="707" alt="image" src="https://user-images.githubusercontent.com/17743556/89362893-8e444780-d701-11ea-8475-cf5b111ab30c.png">
大部分视频无法预览  系统iOS14

**Comment by SilenceLove** [comment]
确定在系统的相册能够播放吗？
我这边看了系统相册也播放不了。应该是ios14的bug
