### ISSUE TITLE
怎样修改选择图片时导航栏两侧的按钮标题颜色？如图

### ISSUE THREAD

**Issue by sharehoney** [SilenceLove/HXPhotoPicker#371]
嗨，请问：怎样修改选择图片时导航栏两侧的按钮标题颜色？
![IMG_0609](https://user-images.githubusercontent.com/5847579/89272139-4de8b900-d670-11ea-8b4a-9d1f3c9cc914.jpg)

**Comment by SilenceLove** [comment]
![image](https://user-images.githubusercontent.com/18083149/89386265-6a015e80-d733-11ea-8aa4-6f805dc26721.png)
设置主题色
或者
通过返回导航栏的block改变导航栏的tinColor
![image](https://user-images.githubusercontent.com/18083149/89386243-6077f680-d733-11ea-90e7-db7eb3b37c52.png)
