### ISSUE TITLE
setOriginal接口无效

### ISSUE THREAD

**Issue by zhuangxq** [SilenceLove/HXPhotoPicker#373]
已确认没有相关issue。

期望效果：隐藏原图按钮，点击完成回调直接是原图。
代码配置如下：

    let manager: HXPhotoManager! = HXPhotoManager(type: .photo)
	manager.setOriginal(true)
	manager.configuration.requestImageAfterFinishingSelection = true
	manager.configuration.hideOriginalBtn = true
	viewController.hx_presentSelectPhotoController(with: manager, didDone: { (allModels, photoModels, videoModels, isOrigin, viewController, manager) in
                        // image不是原图
			let image = allModels?.first?.previewPhoto
			
		}, cancel: { (viewController, manager) in
			
		})
	}

结果： 返回结果不是原图。

看了下源码，isOriginal字段在hx_presentSelectPhotoController时，在selectedListTransformBefore方法里被endIsOriginal字段覆盖，导致isOriginal字段没生效。

临时解决方案：hx_presentSelectPhotoController调用之后，再次设置manager.setOriginal(true)。 

另外建议一下，可以支持swift optional,  添加一下nullable， nonnull状态。

**Comment by SilenceLove** [comment]
isOriginal这个需要选中了原图按钮才会为true

**Comment by SilenceLove** [comment]
添加了一个新的属性 requestOriginalImage  在隐藏原图按钮的时候通过设置它来决定获取的是不是原图
