### ISSUE TITLE
编辑 icloud 视频时会遇到处理失败的提示

### ISSUE THREAD

**Issue by lifeMiik** [SilenceLove/HXPhotoPicker#375]
作者你好，用你写的 demo 运行到手机上，选择的是 icloud 的视频来编辑时，会显示处理失败，是否是没下载完成呢。

-  我已经查阅了已有的issue，没有找到相同的
- 我想提出一个建议或bug，而不是问一个问题

![WechatIMG39](https://user-images.githubusercontent.com/13726235/91010879-e215c280-e615-11ea-8e9a-33a686161b6d.jpeg)

**Comment by lifeMiik** [comment]
报错信息： 
 [10:43:00.502] fsbxpc_obtainSandboxRegistrationForPath signalled err=-17507 (kFigSandboxError_ExtensionDenied) (Could not obtain sandbox extension) at /Library/Caches/com.apple.xbs/Sources/EmbeddedCoreMediaFramework/EmbeddedCoreMedia-2729.5.1.3/Prototypes/Player/ClientServer/FigSandboxSupport.c:454

**Comment by SilenceLove** [comment]
这个应该不是icloud的视频下载问题...能播放了说明视频已经下载完成了

**Comment by lifeMiik** [comment]
> 下载

那应该是编辑出错了，我的手机有些视频 连微信都选择不了，😃

**Comment by lifeMiik** [comment]
> 这个应该不是icloud的视频下载问题...能播放了说明视频已经下载完成了

那应该是编辑的问题了，我的手机有些视频连微信也选择不了，😃

**Comment by SilenceLove** [comment]
可以把你那个原视频发我一下吗

**Comment by lifeMiik** [comment]
> 可以把你那个原视频发我一下吗

可以，要怎么发给你呢

**Comment by SilenceLove** [comment]
294005139@qq.com 发到邮箱吧

**Comment by lifeMiik** [comment]
发了哦，请查收

**Comment by SilenceLove** [comment]
ok



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Miik"<notifications@github.com&gt;; 
发送时间: 2020年8月26日(星期三) 中午11:10
收件人: "SilenceLove/HXPhotoPicker"<HXPhotoPicker@noreply.github.com&gt;; 
抄送: "微微一笑很倾城"<294005139@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [SilenceLove/HXPhotoPicker] 编辑 icloud 视频时会遇到处理失败的提示 (#375)





 
发了哦，请查收

**Comment by SilenceLove** [comment]
是原视频吗? 没有压缩过吧。我这边编辑的是正常的

**Comment by lifeMiik** [comment]
> 是原视频吗? 没有压缩过吧。我这边编辑的是正常的

我QQ选择原文件发送到QQ的，我开通的了 icloud 收费的，本地手机视频都是可以编辑的，但是有些 icloud 上的就是不正常，😃

**Comment by SilenceLove** [comment]
ios14的问题，等ios14正式版出了后再看看

**Comment by SilenceLove** [comment]
最新版已解决
