### ISSUE TITLE
第一次进入选择照片后，再次进入相册，还是选中上次选择图片，怎么取消呢

### ISSUE THREAD

**Issue by 2952883085** [SilenceLove/HXPhotoPicker#378]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration / HXPhotoEditConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图

**Comment by SilenceLove** [comment]
![image](https://user-images.githubusercontent.com/18083149/93751595-e7bff180-fc2f-11ea-87ec-c60d5d4d4d3c.png)
managerd调用清空方法

**Comment by 2952883085** [comment]
好的，谢谢了





------------------ 原始邮件 ------------------
发件人: silence <notifications@github.com&gt;
发送时间: 2020年9月21日 17:29
收件人: SilenceLove/HXPhotoPicker <HXPhotoPicker@noreply.github.com&gt;
抄送: 2952883085 <2952883085@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[SilenceLove/HXPhotoPicker] 第一次进入选择照片后，再次进入相册，还是选中上次选择图片，怎么取消呢 (#378)





 

 managerd调用清空方法

**Comment by liuchunlao** [comment]
这个是首次安装app后，弹出选择器时，系统提示访问所有照片，选择照片，不允许。
然后走的选择照片，选了3张照片，以后任何时候弹出界面都只显示这3张照片。

这个得去系统设置里面找对应app->照片->编辑所选照片，然后添加想要访问的照片。
如果想方便就直接允许访问所有照片
