### ISSUE TITLE
使用AFNetworking进行多图上传的时候，一张一张选择预览图，会闪退

### ISSUE THREAD

**Issue by yoriWang** [SilenceLove/HXPhotoPicker#379]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration / HXPhotoEditConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图 

您好，我在使用AFNetworking进行多图上传的时候，出现闪退，具体流程是：
1、打开图片库选择图片
![image](https://user-images.githubusercontent.com/20896260/91688076-c2414a00-eb93-11ea-9cd3-42829ac81dd3.png)
2、点击完成
3、打开图片库选择图片
![image](https://user-images.githubusercontent.com/20896260/91688118-d8e7a100-eb93-11ea-956f-8cb834164b20.png)
4、点击完成
5、点击保存，并上传图片的时候，程序会闪退
![image](https://user-images.githubusercontent.com/20896260/91688160-fa488d00-eb93-11ea-9951-10198c672513.png)

报错内容如下：
Assertion failure in -[AFStreamingMultipartFormData appendPartWithHeaders:body:]

另外，点击导航栏左侧的最近项目，程序也会闪退，请问什么原因导致的。
感谢~

**Comment by SilenceLove** [comment]
崩溃与框架无关

**Comment by SilenceLove** [comment]
或者试试最新版
