### ISSUE TITLE
调用视频录像，录制结束后开始循环播放视频，左下角的（视频进度图片按钮）点击进入视频编辑页面后会崩溃，Demo12 也一样会崩溃。log：[GatekeeperXPC] Connection to assetsd was interrupted or assetsd died

### ISSUE THREAD

**Issue by jingtiaopi** [SilenceLove/HXPhotoPicker#380]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration / HXPhotoEditConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图

**Comment by SilenceLove** [comment]
视频问题?

**Comment by jingtiaopi** [comment]
Demo 的也会出现且输出log，跟视频没关系，使用小视频也会出现。还没时间来调试 -_-#

另外，视频录制时间结束而结束录制时，左上角没有重拍按钮；视频录制手动松开结束录制时，左上角有重拍按钮。应该是计时器时间结束时- stopRecording 没有调用 - videoFinishRecording:，重置cancelBtn状态。

**Comment by SilenceLove** [comment]
录制视频这个漏了，后续版本修正
你说的视频编辑崩溃目前灭有复现、试试最新demo

**Comment by jingtiaopi** [comment]
好的~ 多谢啦
