### ISSUE TITLE
ios 14下 相册权限

### ISSUE THREAD

**Issue by highplay** [SilenceLove/HXPhotoPicker#381]
用户选择选中“选中的图片”，不能访问图片，建议优化

**Comment by SilenceLove** [comment]
ios14的系统限制

**Comment by highplay** [comment]
系统只是限制能访问的照片时选中的照片，而不是让用户必须允许访问全部图片 才能使用

**Comment by SilenceLove** [comment]
问题是我就是要访问所有照片啊



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: highplay <notifications@github.com&gt;
发送时间: 2020年9月18日 09:23
收件人: SilenceLove/HXPhotoPicker <HXPhotoPicker@noreply.github.com&gt;
抄送: silence <294005139@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[SilenceLove/HXPhotoPicker] ios 14下 相册权限 (#381)





 
系统只是限制能访问的照片时选中的照片，而不是让用户必须允许访问全部图片 才能使用

**Comment by highplay** [comment]
好吧，我换其他的用吧，这个用不了了

**Comment by SilenceLove** [comment]
选择部分的权限已优化
之前一直用模拟器测的iOS14，模拟器下有问题。

**Comment by highplay** [comment]
建议加上一个“选择更多”的按钮，在PHAuthorizationStatusLimited下点击弹出选择更多照片的系统弹框，这样就不需要杀死APP重新选择了

**Comment by SilenceLove** [comment]
这些问题都已修复，照片列表都会实时更新。马上发布最新版

**Comment by SilenceLove** [comment]
已更新，可查看最新demo
你说的那个弹窗是系统设置的
如果你需要更改的话有两种方式
1.去设置相册权限里修改
2.可以在返回照片列表导航栏的block回调里在导航栏上加一个选择按钮，调用系统的 [[PHPhotoLibrary sharedPhotoLibrary] presentLimitedLibraryPickerFromViewController:[UIApplication sharedApplication].keyWindow.rootViewController.navigationController] 这个方法跳转选择照片界面进行更新
![image](https://user-images.githubusercontent.com/18083149/93750753-92cfab80-fc2e-11ea-840e-3fb4b17cee0e.png)
判断 [viewController isKindOfClass:[HXPhotoViewController class]] 是否是照片列表的控制器
然后添加按钮
viewController.navigationItem.rightBarButtonItem
![image](https://user-images.githubusercontent.com/18083149/93750998-f659d900-fc2e-11ea-8fa4-5e23a0300dd5.png)
