### ISSUE TITLE
两个VC，一个只选择视频，另一个只选择图片，打开相册时后 最近项目 显示有问题

### ISSUE THREAD

**Issue by WanMeg** [SilenceLove/HXPhotoPicker#383]
你好，我这里两个viewcontroller A和B，
A里面manger设置只选择视频(HXPhotoManagerSelectedTypeVideo)，
B设置只选择图片(HXPhotoManagerSelectedTypePhoto),

问题描述：
假如第一次打开A页面选择视频，打开相册是正常的 最近项目 也只显示视频资源；
退出A 再打开B 选择图片这时候还是视频资源，最近项目 还是视频列表，不是图片列表；
重新运行项目，先打开B 相册显示的是图片资源，再退出B 打开A，A页面还是图片，而不是视频；
相册列表的 最近项目 并没有重置资源

看源码没有找到原因，麻烦帮看下可能会是什么原因导致的，谢谢

**Comment by WanMeg** [comment]
用的pod 'HXPhotoPicker_YY', '~> 2.4.2' 版本，老版本可能有问题，现在升级到最新的没问题了

**Comment by ccchzxj** [comment]
您好，使用您的选择器遇上一个问题，视频图片选择分成两个按钮，要求一个只选择视频，一个只选择照片，源码里面没有将两个manager合成一个的方法，使用一个manager会出现不能同时选择的问题，请问有什么解决办法
