### ISSUE TITLE
新版本打包上传apple警告⚠️

### ISSUE THREAD

**Issue by xiaohange** [SilenceLove/HXPhotoPicker#386]
警告ITMS-90176：“无法识别的语言环境-本地化目录中使用的语言环境名称（“ Payload / xxx.app / hx_en.lproj”，“ Payload / xxx.app / hx_ja.lproj”，“ Payload / xxx.app / hx_ko .lproj”，“ Payload / xxx.app / hx_zh-Hans.lproj”，“ Payload / xxx.app / hx_zh-Hant.lproj”）无效。iTunes支持BCP47，但不支持UN M.49规范。请参阅 语言和语言环境指定指南，网址为https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html，以获取有关命名特定于语言的目录的更多信息。”

**Comment by SilenceLove** [comment]
3.0.8 已改

**Comment by xiaohange** [comment]
@SilenceLove 谢谢

**Comment by xiaohange** [comment]
@SilenceLove 错误ITMS-90542：“ CFBundleSupportedPlatforms值无效。捆绑包'Payload / xxx.app / HXPhotoPicker.bundle'中Info.plist文件中的键'CFBundleSupportedPlatforms'包含无效值'[iPhoneSimulator]'。请考虑从中删除CFBundleSupportedPlatforms密钥。 如果该捆绑包是第三方框架的一部分，请考虑与该框架的开发人员联系以获取更新以解决此问题。”

**Comment by xiaohange** [comment]
info.plist文件中的CFBundleSupportedPlatforms字段和其对应的值导致的，移除即可

**Comment by SilenceLove** [comment]
bundle里多余的文件已删

**Comment by xiaohange** [comment]
@SilenceLove 感谢！
