### ISSUE TITLE
内部需要提示的时候闪退，如超过最大图片数

### ISSUE THREAD

**Issue by qinhongke** [SilenceLove/HXPhotoPicker#387]
[NSBundle hx_localizedStringForKey:@"视频大于%ld秒，无法选择"]、只要调到 hx_localizedStringForKey 这个方法就闪退

**Comment by SilenceLove** [comment]
是否最新版吗？demo有这个问题吗？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: qinhongke <notifications@github.com&gt;
发送时间: 2020年9月11日 11:18
收件人: SilenceLove/HXPhotoPicker <HXPhotoPicker@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[SilenceLove/HXPhotoPicker] 内部需要提示的时候闪退，如超过最大图片数 (#387)





 
[NSBundle hx_localizedStringForKey:@"视频大于%ld秒，无法选择"]、只要调到 hx_localizedStringForKey 这个方法就闪退

**Comment by qinhongke** [comment]
3.0.7，真机没有问题，模拟器就闪退，Demo 没有问题

**Comment by SilenceLove** [comment]
最新的是3.0.8 试一下最新版



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: qinhongke <notifications@github.com&gt;
发送时间: 2020年9月11日 14:16
收件人: SilenceLove/HXPhotoPicker <HXPhotoPicker@noreply.github.com&gt;
抄送: silence <294005139@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[SilenceLove/HXPhotoPicker] 内部需要提示的时候闪退，如超过最大图片数 (#387)





 
3.0.7，真机没有问题，模拟器就闪退，Demo 没有问题

**Comment by qinhongke** [comment]
3.0.8 在模拟器一样崩溃

**Comment by SilenceLove** [comment]
崩溃日志是什么



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: qinhongke <notifications@github.com&gt;
发送时间: 2020年9月12日 18:11
收件人: SilenceLove/HXPhotoPicker <HXPhotoPicker@noreply.github.com&gt;
抄送: silence <294005139@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[SilenceLove/HXPhotoPicker] 内部需要提示的时候闪退，如超过最大图片数 (#387)





 
3.0.8 在模拟器一样崩溃

**Comment by qinhongke** [comment]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSPlaceholderString initWithFormat:locale:arguments:]: nil argument'
