### ISSUE TITLE
相册加载中，相册标题多次点击必现崩溃

### ISSUE THREAD

**Issue by zhuangxq** [SilenceLove/HXPhotoPicker#389]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration / HXPhotoEditConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue

操作路径：
1. 进入相册选择页面。
2. 相册比较多，loading中
3. 标题多次点击，崩溃

(需要操作录屏的话，可以提供给）

![screenshot](https://user-images.githubusercontent.com/7955963/93289209-7556a800-f810-11ea-9a14-0f82925d16f6.png)

**Comment by SilenceLove** [comment]
试试最新的demo，看看还会不会出现这个问题
