### ISSUE TITLE
能否支持下配置相机icon？

### ISSUE THREAD

**Issue by RunzhuZhao** [SilenceLove/HXPhotoPicker#390]

**Comment by SilenceLove** [comment]
![image](https://user-images.githubusercontent.com/18083149/93582568-3f165580-f9d5-11ea-8dd1-9ed0f3063c8c.png)
已加

**Comment by RunzhuZhao** [comment]
谢谢，辛苦啦~


------------------&nbsp;Original&nbsp;------------------
