### ISSUE TITLE
ios14兼容吗？

### ISSUE THREAD

**Issue by HelloWilliam** [SilenceLove/HXPhotoPicker#391]

**Comment by SilenceLove** [comment]
已兼容

**Comment by DogTwoChen** [comment]
iOS 14点击图片预览的时候变成空白

**Comment by SilenceLove** [comment]
如果用的是sdwebimage 请升级到最新版，如果用的yywebimage请替换成sd



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: GodTwoChen <notifications@github.com&gt;
发送时间: 2020年9月18日 08:29
收件人: SilenceLove/HXPhotoPicker <HXPhotoPicker@noreply.github.com&gt;
抄送: silence <294005139@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[SilenceLove/HXPhotoPicker] ios14兼容吗？ (#391)





 
iOS 14点击图片预览的时候变成空白

**Comment by DogTwoChen** [comment]
OK。升级后解决了，谢谢
