### ISSUE TITLE
iOS 14下选择部分照片还是不行，只能选择允许所有照片

### ISSUE THREAD

**Issue by iosdevcoding** [SilenceLove/HXPhotoPicker#392]
感谢开源，感谢作者。

弹框访问相册权限的时候，如果选择了部分照片不显示，只能选择允许所有照片。
希望能解决一下这个问题。

**Comment by SilenceLove** [comment]
系统限制，选择了部分照片这个权限，在获取相册的时候系统并不会过滤掉不可查看的照片，也没有可判断的方法。最后会造成无法查看的照片无法显示，最后会造成界面一大片空白。
目前还没发现可以直接判断哪张是不可查看的，也没有过滤的方法。后期找到了解决方案再进行优化

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: iosdevcoding <notifications@github.com&gt;
发送时间: 2020年9月19日 14:11
收件人: SilenceLove/HXPhotoPicker <HXPhotoPicker@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[SilenceLove/HXPhotoPicker] iOS 14下选择部分照片还是不行，只能选择允许所有照片 (#392)





 
感谢开源，感谢作者。
 
弹框访问相册权限的时候，如果选择了部分照片不显示，只能选择允许所有照片。
 希望能解决一下这个问题。

**Comment by iosdevcoding** [comment]
感谢作者回复，我看其其它的App在iOS 14上选中部分照片就可以

**Comment by iosdevcoding** [comment]
另外，点击加号的图标，不是会弹出拍照和从手机相册中选择的弹框吗？10.3.1的系统弹不出弹框，模拟器上看的

**Comment by SilenceLove** [comment]
我升到ios14试试

**Comment by iosdevcoding** [comment]
好的，谢谢

**Comment by SilenceLove** [comment]
可能是我模拟器的问题....真机试了一下系统会过滤掉为选择的资源.
下个版本处理一下这个问题

**Comment by iosdevcoding** [comment]
好的，作者可以把需要改动的地方发出来吗？我先处理一下，提交版本😂

**Comment by SilenceLove** [comment]
已适配，测试请使用真机。iOS14模拟器会出问题

**Comment by SilenceLove** [comment]
10.3.1 的问题也已修复
