### ISSUE TITLE
如何去掉定位定位的权限

### ISSUE THREAD

**Issue by iosdevcoding** [SilenceLove/HXPhotoPicker#394]
感谢作者解决iOS 14相册的权限问题，太给力了，我想再问一下代码里设置了cameraCanLocation=NO，info.plist也没有配置Location Always Usage Description，但是安装后，系统设置里还是有位置的权限。

**Comment by SilenceLove** [comment]
cameraCanLocation 这是NO了并不会去请求定位权限

**Comment by iosdevcoding** [comment]
对，不会去请求，但是iOS14上，神奇的是系统设置里有为位置权限的入口，而且提交版本AppStore那边发邮件提示这个Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationWhenInUseUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

**Comment by SilenceLove** [comment]
这个问题，只有把定位功能单独抽出来了来解决了。。

**Comment by iosdevcoding** [comment]
麻烦了麻烦了，看你有没有时间处理

**Comment by SilenceLove** [comment]
定位问题已经修复了，可以查看最新demo。我这边用真机没有再出现这样的情况了

**Comment by iosdevcoding** [comment]
666，太厉害了，感谢作者！

**Comment by SilenceLove** [comment]
你那边是正常的吗?

**Comment by iosdevcoding** [comment]
刚试了，正常啦
