### ISSUE TITLE
iOS 14 添加或删除部分图片授权，列表没有动态变化

### ISSUE THREAD

**Issue by iToby** [SilenceLove/HXPhotoPicker#395]
iOS 14 ，进入选择图片页面后，添加或删除部分图片授权，列表没有动态变化，仍然显示原来所有图片，选择一个图片后，再点+号进来选择更多时显示异常
![image](https://user-images.githubusercontent.com/8199014/93740488-29936c80-fc1d-11ea-989b-eb966306267d.png)

**Comment by SilenceLove** [comment]
你那个添加按钮逻辑自己写的吗?

**Comment by iToby** [comment]
直接进设置修改的，自己调[[PHPhotoLibrary sharedPhotoLibrary] presentLimitedLibraryPickerFromViewController:self];修改也是一样的，不会变化

**Comment by SilenceLove** [comment]
把self  换成 导航栏

**Comment by iToby** [comment]
> 把self 换成 self.navigationController

这样可行。还请指教直接进设置修改的情况怎么处理。感谢

**Comment by SilenceLove** [comment]
这种情况，目前还没处理..看了一下微信也没处理这种情况
后面我看下怎么处理一下

**Comment by iToby** [comment]
> 这种情况，目前还没处理..看了一下微信也没处理这种情况
> 后面我看下怎么处理一下

👍👍👍

**Comment by SilenceLove** [comment]
目前还没处理这种进设置这种情况...

**Comment by SilenceLove** [comment]
已更新，可以查看最新demo

**Comment by iToby** [comment]
> 已更新，可以查看最新demo

👍👍👍 感谢
