### ISSUE TITLE
请问如何在UIImageView+HXExtension.h中导入SDWebImage

### ISSUE THREAD

**Issue by ChenZachary** [SilenceLove/HXPhotoPicker#396]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration / HXPhotoEditConfiguration
- [x] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图

**Comment by ChenZachary** [comment]
我都是pod导入的

**Comment by SilenceLove** [comment]
Pod 添加的时候应该是&nbsp;
'HXPhotoPivker/SDWebImage'



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ChenZachary <notifications@github.com&gt;
发送时间: 2020年9月21日 20:02
收件人: SilenceLove/HXPhotoPicker <HXPhotoPicker@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[SilenceLove/HXPhotoPicker] 请问如何在UIImageView+HXExtension.h中导入SDWebImage (#396)





 
我都是pod导入的

**Comment by ChenZachary** [comment]
网上搜的方法解决了，感谢回复🙏

**Comment by ChenZachary** [comment]
解决
