### ISSUE TITLE
升级到ios14后大图显示黑屏

### ISSUE THREAD

**Issue by Lovezysong** [SilenceLove/HXPhotoPicker#398]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration / HXPhotoEditConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图

**Comment by Lovezysong** [comment]
当项目里显示动图用到了FLAnimatedImageView，SDAnimatedImageView，YYAnimatedImageView就会有这个问题
14.0 系统调用了此方法，没有正确处理

-(void)displayLayer:(CALayer *)layer;

解决如下,找到这个方法
-(void)displayLayer:(CALayer *)layer {
if (_curFrame) {
layer.contents = (__bridge id)_curFrame.CGImage;
} else {
// If we have no animation frames, call super implementation. iOS 14+ UIImageView use this delegate method for rendering.
if ([UIImageView instancesRespondToSelector:@selector(displayLayer:)]) {
[super displayLayer:layer];
}
}
}

**Comment by Jasonning** [comment]
有用 谢啦
