### ISSUE TITLE
model.videoURL.path 路径为空

### ISSUE THREAD

**Issue by Arise903** [SilenceLove/HXPhotoPicker#399]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration / HXPhotoEditConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图 
  }else if ([session status] == AVAssetExportSessionStatusFailed){
                        if (HXShowLog) NSSLog(@"视频导出失败");
                        [timer invalidate];
                        if (failed) {
                            failed(nil, strongSelf);
                        }
                    }

**Comment by Arise903** [comment]
有没有其他的方法，来获取图片的地址？？

**Comment by SilenceLove** [comment]
model 里的request的方法

**Comment by Arise903** [comment]
目前我用的是PHAsset来获取视频地址的。

**Comment by SilenceLove** [comment]
可以

**Comment by Arise903** [comment]
另外可以增加一个功能，就是使用一个框架图片和视频可以单独选择的功能。

**Comment by SilenceLove** [comment]
单选只查看图片或视频?

**Comment by Arise903** [comment]
是的，使用者可以自由选自只选择图片、只选择视频，或者视频和图片同时选择以及自由设置视频和图片的数量

**Comment by SilenceLove** [comment]
配置类都有



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Arise <notifications@github.com&gt;
发送时间: 2020年10月9日 10:56
收件人: SilenceLove/HXPhotoPicker <HXPhotoPicker@noreply.github.com&gt;
抄送: silence <294005139@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[SilenceLove/HXPhotoPicker] model.videoURL.path 路径为空 (#399)





 
是的，使用者可以自由选自只选择图片、只选择视频，或者视频和图片同时选择以及自由设置视频和图片的数量

**Comment by SilenceLove** [comment]
可以看下demo1里的代码
