### ISSUE TITLE
HXPhotoPreviewViewController中的darkDeleteBtn不显示

### ISSUE THREAD

**Issue by Mrdongyueyue** [SilenceLove/HXPhotoPicker#400]
### 感谢提交问题
提交 issue 前请先通过关键字搜索已经存在或解决了的 issue，避免重复提交相同内容

### 查看README、配置类HXPhotoConfiguration / HXPhotoEditConfiguration
- [ ] 我已经查阅了已有的issue，没有找到相同的
- [ ] 我想提出一个建议或bug，而不是问一个问题

### issue
请尽量详细描述，建议附上截图 
在`HXPhotoPreviewViewController.m` 1391行`darkDeleteBtn`的初始化方法中，`_darkDeleteBtn.hidden = YES;`，在视图显示之后没有根据`previewShowDeleteButton`修改`darkDeleteBtn.hidden`属性

**Comment by PerfectisShittttttttttttttttttttttttttt** [comment]
还有darkCancelBtn需要一起修改 hidden属性

**Comment by SilenceLove** [comment]
3.1.1版本已优化
