### ISSUE TITLE
编辑图片的时候裁切功能默认是自由模式的问题

### ISSUE THREAD

**Issue by iosdevcoding** [SilenceLove/HXPhotoPicker#401]
作者你好，请教一个问题。

编辑图片的时候默认是自由模式，怎么改为默认4:3的比例，而且继续保留其它的裁切比例，我配置了aspectRatio参数，但是就不出现其它裁切比例了

**Comment by SilenceLove** [comment]
目前默认选中的是自由模式，暂时不能更改默认选项。

**Comment by iosdevcoding** [comment]
好的，谢谢回复
