### ISSUE TITLE
hx_requestImageWithOriginal方法获取不到网络图片

### ISSUE THREAD

**Issue by iotjin** [SilenceLove/HXPhotoPicker#402]
![image](https://user-images.githubusercontent.com/9895575/94670531-43cbf980-0345-11eb-8994-8a30b2fcfc4a.png)

我在demo12调用下面这个方法想获取原图，但是网络图片打印的是占位图
- (void)photoView:(HXPhotoView *)photoView changeComplete:(NSArray<HXPhotoModel *> *)allList photos:(NSArray<HXPhotoModel *> *)photos videos:(NSArray<HXPhotoModel *> *)videos original:(BOOL)isOriginal {

  [allList hx_requestImageWithOriginal:isOriginal completion:^(NSArray<UIImage *> * _Nullable imageArray, NSArray<HXPhotoModel *> * _Nullable errorArray) {
        NSLog(@"imageArray --%@",imageArray);
    }];
}

打印的数据
imageArray --(
    "<UIImage:0x6000031eeb50 named(main: 1) {430, 430}>",
    "<UIImage:0x6000031e5560 named(hx_qz_photolist_picture_fail) {124, 124}>",
    "<UIImage:0x6000031ef2a0 anonymous {270, 480}>",
    "<UIImage:0x6000031eed00 anonymous {169, 246}>",
    "<UIImage:0x6000031e5560 named(hx_qz_photolist_picture_fail) {124, 124}>",
    "<UIImage:0x6000031e5560 named(hx_qz_photolist_picture_fail) {124, 124}>"
)

**Comment by SilenceLove** [comment]
网络图片下载失败了

**Comment by iotjin** [comment]
> 网络图片下载失败了

我看了一下源码，知道是怎么回事了，NSArray+HXExtension.m 文件中 194行有个判断，[[HXPhotoCommon photoCommon].requestNetworkAfter，我之前用的那个版本没有requestNetworkAfter这个参数，使用现在这个版本requestNetworkAfter默认是false,没走里面的方法

![image](https://user-images.githubusercontent.com/9895575/95952546-e77bd600-0e2a-11eb-98a2-0c0533b22706.png)

**Comment by SilenceLove** [comment]
如果需要下载网络图片需要把那个值设置为YES



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: iotjin <notifications@github.com&gt;
发送时间: 2020年10月14日 14:46
收件人: SilenceLove/HXPhotoPicker <HXPhotoPicker@noreply.github.com&gt;
抄送: silence <294005139@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[SilenceLove/HXPhotoPicker] hx_requestImageWithOriginal方法获取不到网络图片 (#402)





  
网络图片下载失败了
  
我看了一下源码，知道是怎么回事了，NSArray+HXExtension.m 文件中 194行有个判断，[[HXPhotoCommon photoCommon].requestNetworkAfter，我之前用的那个版本没有requestNetworkAfter这个参数，使用现在这个版本requestNetworkAfter默认是false,没走里面的方法
