### ISSUE TITLE
hxNavigationBarHeight、hxTopMargin等宏定义有错误

### ISSUE THREAD

**Issue by jiasongs** [SilenceLove/HXPhotoPicker#404]
正常应该是
`#define NavigationBarHeight (IS_IPAD ? (IOS_VERSION >= 12.0 ? 50 : 44) : (IS_LANDSCAPE ? PreferredValueForVisualDevice(44, 32) : 44))`
`#define StatusBarHeight (UIApplication.sharedApplication.statusBarHidden ? 0 : UIApplication.sharedApplication.statusBarFrame.size.height)`

`#define hxTopMargin (HX_IS_IPhoneX_All ? 44 : 0)` 在iOS 13, iPhone 11的情况下，top是48，并不是44。
建议用`#define StatusBarHeight`代替，

另外`#define hxBottomMargin`也有问题，横竖屏的情况是不一样的。如下图
<img width="827" alt="图片" src="https://user-images.githubusercontent.com/22904757/95653401-193f2500-0b2b-11eb-94ad-b5910e32d193.png">

建议修复此问题，使此库更加严谨些

**Comment by SilenceLove** [comment]
可以提交一个pr不😊

**Comment by jiasongs** [comment]
> 可以提交一个pr不😊

好的，还有一些其他的问题，我改好后提交PR

**Comment by SilenceLove** [comment]
👍太棒了

**Comment by jiasongs** [comment]
> 可以提交一个pr不😊

项目里很多地方都使用的是绝对布局，即采用整个屏幕作为画布进行布局，但是iPad，包括分屏等各类情况，会导致画面很大不美观。
且子控件的布局没有放在`viewDidLayoutSubviews`或者`layoutSubviews`里，只有旋转屏幕时才会调用，但是这样外部若是改变frame，子控件的布局就得不到回应。
我尝试改进以上问题，改动起来发现需要改动的地方太多，项目的布局基本需要重构，此PR的提交可能会很久，目前我时间有限，暂时关闭此ISSUE，如果有空闲时间会改进此项目，提交PR，谢谢。
