### ISSUE TITLE
图片编辑界面显示黑屏

### ISSUE THREAD

**Issue by charlesYun** [SilenceLove/HXPhotoPicker#406]
最新demo真机运行，图片编辑界面黑屏显示不出来，预览界面正常

**Comment by yinjining** [comment]
我也出现了同样的问题，设备是iPhone5s，操作做系统是11.1.1   运行微信朋友圈的那个样例，编辑时出现黑屏，模拟器无此类问题。

**Comment by iPermanent** [comment]
![Image](https://github.com/user-attachments/assets/9ca84ab9-793d-4885-be4f-b6ab8f2187ff)
5.0.0版本  依然存在同样问题
系统 18.3.1 手机 13 pro max 编辑完图片后图片黑色无显示
