### ISSUE TITLE
项目中使用HXPhotoView九宫格加载已有网络图片, 加载完成后, 打印出来的图片信息如下, 不能直接使用这些图片进行提交操作.

### ISSUE THREAD

**Issue by duboce2008** [SilenceLove/HXPhotoPicker#410]
在这个方法中

-(void)photoView:(HXPhotoView *)photoView changeComplete:(NSArray<HXPhotoModel *> *)allList photos:(NSArray<HXPhotoModel *> *)photos videos:(NSArray<HXPhotoModel *> *)videos original:(BOOL)isOriginal {

[allList hx_requestImageWithOriginal:isOriginal completion:^(NSArray<UIImage *> * _Nullable imageArray, NSArray<HXPhotoModel *> * _Nullable errorArray) {
// imageArray 获取成功的image数组
// errorArray 获取失败的model数组
NSSLog(@"\nimage: %@\nerror: %@",imageArray,errorArray);
self.selectedPhotosArray = [NSMutableArray arrayWithArray:imageArray];
}];
}
打印结果:
image: (
<UIImage:0x283286d90 named(hx_qz_photolist_picture_fail) {124, 124}>,
<UIImage:0x283286d90 named(hx_qz_photolist_picture_fail) {124, 124}>,
)
error: (null)

**Comment by SilenceLove** [comment]
#402
