### ISSUE TITLE
iPhone12屏幕的宏定义，跳转系统设置适配iOS10，PHImageRequestID取值iOS13的适配

### ISSUE THREAD

**Issue by liuxiaobai710189615** [SilenceLove/HXPhotoPicker#411]
1.HXPhotoDefine.h中宏定义建议适配iPhone12

#define HX_IS_IPHONEX (CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(375, 812)) || CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(812, 375)) || CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(414, 896)) || CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(896, 414)) || CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(360, 780)) || CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(780, 360)) || CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(390, 844)) || CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(844, 390)) || CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(428, 926)) || CGSizeEqualToSize([UIScreen mainScreen].bounds.size, CGSizeMake(926, 428)))

// 判断iPhone X
#define HX_Is_iPhoneX ([UIScreen instancesRespondToSelector:@selector(currentMode)] ? CGSizeEqualToSize(CGSizeMake(1125, 2436), [[UIScreen mainScreen] currentMode].size) : NO)

//判断iPHoneXr、iPHone11
#define HX_Is_iPhoneXR ([UIScreen instancesRespondToSelector:@selector(currentMode)] ? CGSizeEqualToSize(CGSizeMake(828, 1792), [[UIScreen mainScreen] currentMode].size) && !HX_UI_IS_IPAD : NO)

//判断iPHoneX、iPHoneXs、iPHone11 Pro
#define HX_Is_iPhoneXS ([UIScreen instancesRespondToSelector:@selector(currentMode)] ? CGSizeEqualToSize(CGSizeMake(1125, 2436), [[UIScreen mainScreen] currentMode].size) && !HX_UI_IS_IPAD : NO)

//判断iPhoneXs Max、iPHone11 ProMax
#define HX_Is_iPhoneXS_MAX ([UIScreen instancesRespondToSelector:@selector(currentMode)] ? CGSizeEqualToSize(CGSizeMake(1242, 2688), [[UIScreen mainScreen] currentMode].size) && !HX_UI_IS_IPAD : NO)

//判断iPHone12 mini
#define HX_Is_iPhoneTwelveMini ([UIScreen instancesRespondToSelector:@selector(currentMode)] ? CGSizeEqualToSize(CGSizeMake(1080, 2340), [[UIScreen mainScreen] currentMode].size) && !HX_UI_IS_IPAD : NO)

//判断iPHone12 和 iPHone12 Pro
#define HX_Is_iPhoneTwelvePro ([UIScreen instancesRespondToSelector:@selector(currentMode)] ? CGSizeEqualToSize(CGSizeMake(1170, 2532), [[UIScreen mainScreen] currentMode].size) && !HX_UI_IS_IPAD : NO)

//判断iPHone12 ProMax
#define HX_Is_iPhoneTwelveProMax ([UIScreen instancesRespondToSelector:@selector(currentMode)] ? CGSizeEqualToSize(CGSizeMake(1284, 2778), [[UIScreen mainScreen] currentMode].size) && !HX_UI_IS_IPAD : NO)

#define HX_IS_IPhoneX_All (HX_Is_iPhoneX || HX_Is_iPhoneXR || HX_Is_iPhoneXS || HX_Is_iPhoneXS_MAX || HX_IS_IPHONEX || HX_Is_iPhoneTwelveMini || HX_Is_iPhoneTwelvePro || HX_Is_iPhoneTwelveProMax)

2.请全局搜：[NSURL URLWithString:UIApplicationOpenSettingsURLString] 跳转系统设置，建议适配iOS10以后

NSURL *url = [NSURL URLWithString:UIApplicationOpenSettingsURLString];
if (@available(iOS 10.0, *)) {
    [[UIApplication sharedApplication] openURL:url options:@{} completionHandler:^(BOOL success) {
        if (success) {
            
        }else{
            
        }
    }];
} else {
    [[UIApplication sharedApplication] openURL:url];
}

3.在HXPhotoModel.m中，请搜requestImageDataForAsset，建议适配iOS13

    PHImageRequestID requestID;
    if (@available(iOS 13.0, *)) {
        requestID = [[PHImageManager defaultManager] requestImageDataAndOrientationForAsset:self.asset options:option resultHandler:^(NSData * _Nullable imageData, NSString * _Nullable dataUTI, CGImagePropertyOrientation orientation, NSDictionary * _Nullable info) {
            
            /*
             kCGImagePropertyOrientationUp = 1,        // 0th row at top,    0th column on left   - default orientation
             kCGImagePropertyOrientationUpMirrored,    // 0th row at top,    0th column on right  - horizontal flip
             kCGImagePropertyOrientationDown,          // 0th row at bottom, 0th column on right  - 180 deg rotation
             kCGImagePropertyOrientationDownMirrored,  // 0th row at bottom, 0th column on left   - vertical flip
             kCGImagePropertyOrientationLeftMirrored,  // 0th row on left,   0th column at top
             kCGImagePropertyOrientationRight,         // 0th row on right,  0th column at top    - 90 deg CW
             kCGImagePropertyOrientationRightMirrored, // 0th row on right,  0th column on bottom
             kCGImagePropertyOrientationLeft           // 0th row on left,   0th column at bottom - 90 deg CCW
             */
            
            /*
             UIImageOrientationUp,            // default orientation
             UIImageOrientationDown,          // 180 deg rotation
             UIImageOrientationLeft,          // 90 deg CCW
             UIImageOrientationRight,         // 90 deg CW
             UIImageOrientationUpMirrored,    // as above but image mirrored along other axis. horizontal flip
             UIImageOrientationDownMirrored,  // horizontal flip
             UIImageOrientationLeftMirrored,  // vertical flip
             UIImageOrientationRightMirrored, // vertical flip
             */
            
            UIImageOrientation sureOrientation;
            if (orientation == kCGImagePropertyOrientationUp) {
                sureOrientation = UIImageOrientationUp;
            } else if (orientation == kCGImagePropertyOrientationUpMirrored) {
                sureOrientation = UIImageOrientationUpMirrored;
            } else if (orientation == kCGImagePropertyOrientationDown) {
                sureOrientation = UIImageOrientationDown;
            } else if (orientation == kCGImagePropertyOrientationDownMirrored) {
                sureOrientation = UIImageOrientationDownMirrored;
            } else if (orientation == kCGImagePropertyOrientationLeftMirrored) {
                sureOrientation = UIImageOrientationLeftMirrored;
            } else if (orientation == kCGImagePropertyOrientationRight) {
                sureOrientation = UIImageOrientationRight;
            } else if (orientation == kCGImagePropertyOrientationRightMirrored) {
                sureOrientation = UIImageOrientationRightMirrored;
            } else if (orientation == kCGImagePropertyOrientationLeft) {
                sureOrientation = UIImageOrientationLeft;
            } else {
                sureOrientation = UIImageOrientationUp;
            }
            
            [weakSelf requestDataWithResult:imageData info:info size:CGSizeZero resultClass:[NSData class] orientation:sureOrientation audioMix:nil startRequestICloud:startRequestICloud progressHandler:progressHandler success:^(id result, NSDictionary *info, UIImageOrientation orientation, AVAudioMix *audioMix) {
                if (success) {
                    success(result, orientation, weakSelf, info);
                }
            } failed:failed];
        }];
    } else {
        requestID = [[PHImageManager defaultManager] requestImageDataForAsset:self.asset options:option resultHandler:^(NSData * _Nullable imageData, NSString * _Nullable dataUTI, UIImageOrientation orientation, NSDictionary * _Nullable info) {
            [weakSelf requestDataWithResult:imageData info:info size:CGSizeZero resultClass:[NSData class] orientation:orientation audioMix:nil startRequestICloud:startRequestICloud progressHandler:progressHandler success:^(id result, NSDictionary *info, UIImageOrientation orientation, AVAudioMix *audioMix) {
                if (success) {
                    success(result, orientation, weakSelf, info);
                }
            } failed:failed];
        }];
    }

                if (@available(iOS 13.0, *)) {
                    iCloudRequestId = [[PHImageManager defaultManager] requestImageDataAndOrientationForAsset:self.asset options:iCloudOption resultHandler:^(NSData * _Nullable imageData, NSString * _Nullable dataUTI, CGImagePropertyOrientation orientation, NSDictionary * _Nullable info) {
                        
                        UIImageOrientation sureOrientation;
                        if (orientation == kCGImagePropertyOrientationUp) {
                            sureOrientation = UIImageOrientationUp;
                        } else if (orientation == kCGImagePropertyOrientationUpMirrored) {
                            sureOrientation = UIImageOrientationUpMirrored;
                        } else if (orientation == kCGImagePropertyOrientationDown) {
                            sureOrientation = UIImageOrientationDown;
                        } else if (orientation == kCGImagePropertyOrientationDownMirrored) {
                            sureOrientation = UIImageOrientationDownMirrored;
                        } else if (orientation == kCGImagePropertyOrientationLeftMirrored) {
                            sureOrientation = UIImageOrientationLeftMirrored;
                        } else if (orientation == kCGImagePropertyOrientationRight) {
                            sureOrientation = UIImageOrientationRight;
                        } else if (orientation == kCGImagePropertyOrientationRightMirrored) {
                            sureOrientation = UIImageOrientationRightMirrored;
                        } else if (orientation == kCGImagePropertyOrientationLeft) {
                            sureOrientation = UIImageOrientationLeft;
                        } else {
                            sureOrientation = UIImageOrientationUp;
                        }
                        
                        BOOL downloadFinined = (![[info objectForKey:PHImageCancelledKey] boolValue] && ![info objectForKey:PHImageErrorKey] && ![[info objectForKey:PHImageResultIsDegradedKey] boolValue]);
                        if (downloadFinined && imageData) {
                            dispatch_async(dispatch_get_main_queue(), ^{
//                                weakSelf.isICloud = NO;
                                weakSelf.iCloudDownloading = NO;
                                if (success) {
                                    success(imageData, info, sureOrientation, nil);
                                }
                            });
                        }else {
                            dispatch_async(dispatch_get_main_queue(), ^{
                                if (![[info objectForKey:PHImageCancelledKey] boolValue]) {
                                    weakSelf.iCloudDownloading = NO;
                                }
                                if (failed) {
                                    failed(info, weakSelf);
                                }
                            });
                        }
                    }];
                } else {
                    iCloudRequestId = [[PHImageManager defaultManager] requestImageDataForAsset:self.asset options:iCloudOption resultHandler:^(NSData * _Nullable imageData, NSString * _Nullable dataUTI, UIImageOrientation orientation, NSDictionary * _Nullable info) {
                        BOOL downloadFinined = (![[info objectForKey:PHImageCancelledKey] boolValue] && ![info objectForKey:PHImageErrorKey] && ![[info objectForKey:PHImageResultIsDegradedKey] boolValue]);
                        if (downloadFinined && imageData) {
                            dispatch_async(dispatch_get_main_queue(), ^{
//                                weakSelf.isICloud = NO;
                                weakSelf.iCloudDownloading = NO;
                                if (success) {
                                    success(imageData, info, orientation, nil);
                                }
                            });
                        }else {
                            dispatch_async(dispatch_get_main_queue(), ^{
                                if (![[info objectForKey:PHImageCancelledKey] boolValue]) {
                                    weakSelf.iCloudDownloading = NO;
                                }
                                if (failed) {
                                    failed(info, weakSelf);
                                }
                            });
                        }
                    }];
                }

**Comment by SilenceLove** [comment]
老哥，可以提交一个pr吗...

**Comment by liuxiaobai710189615** [comment]
没有提交过，不知道怎么搞？抱歉哈！回头研究研究！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "silence"<notifications@github.com&gt;; 
发送时间: 2020年10月21日(星期三) 上午10:51
收件人: "SilenceLove/HXPhotoPicker"<HXPhotoPicker@noreply.github.com&gt;; 
抄送: "萧洒"<710189615@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [SilenceLove/HXPhotoPicker] iPhone12屏幕的宏定义，跳转系统设置适配iOS10，PHImageRequestID取值iOS13的适配 (#411)





 
老哥，可以提交一个pr吗...

**Comment by iToby** [comment]
请教一下，判断X系列为什么要判断每一款设备，是为了规避什么坑吗？直接使用 [[UIApplication sharedApplication]delegate].window.safeAreaInsets.bottom > 0.0 判断是有坑吗？ @liuxiaobai710189615 @SilenceLove
