### ISSUE TITLE
获取真实图片

### ISSUE THREAD

**Issue by dashaomao** [SilenceLove/HXPhotoPicker#420]
除了NSArray+HXExtension.h类中获取真实图片的，还有其它方法?从相册中选择的图片model.previewPhoto、model.thumbPhoto获取的都不是真实的图片

**Comment by SilenceLove** [comment]
Model里的request 相关方法

**Comment by sany620** [comment]
不知道后续能不能支持通过一个成员变量获取真实的图片，上面说的方法，不太友好
