### ISSUE TITLE
选择图片，预览闪一下后，空白。

### ISSUE THREAD

**Issue by TianYou899** [SilenceLove/HXPhotoPicker#422]
**bug描述**

你好，首先非常感谢你开源的图片选择器，确实帮助了我很多。但是我现在遇到一些问题，希望你能帮我解决一下！我在多选图片的时候，在相册预览或者选择后预览，展示图片的时候，首先显示一下图片，然后突然就白了，开始我以为我的代码有问题，然后把Demo中 demo3 拖到项目中也是这样子，下面附件为demo3在我的项目中的样子。
[1606270773577467.mp4.zip](https://github.com/SilenceLove/HXPhotoPicker/files/5594048/1606270773577467.mp4.zip)

**版本号**
1.HXPhotoPicker版本号：3.1.1
2.手机系统版本号：iOS 14
3.手机型号：iPhone X
遇到的问题，感觉和手机没有关系。

**截图、GIF**

[1606270773577467.mp4.zip](https://github.com/SilenceLove/HXPhotoPicker/files/5594049/1606270773577467.mp4.zip)

**Comment by SilenceLove** [comment]
#398 看下是SDWebImage是否升级到最新版

**Comment by TianYou899** [comment]
pod 'SDWebImage',                              '5.8.1'
这个应该是最新版的

**Comment by darkengine** [comment]
> pod 'SDWebImage', '5.8.1'
> 这个应该是最新版的

SDWebImage (5.9.4) 最新都到5.9.x了

**Comment by TianYou899** [comment]
升级完，已经解决了！谢谢各位大佬！
