### ISSUE TITLE
最新的版本3.1.6 github 下载的项目同样问题 手机系统14.2

### ISSUE THREAD

**Issue by zhangchuangchuang** [SilenceLove/HXPhotoPicker#424]
**bug描述**
最新版本3.1.6 github下载的项目同样的问题

第一次安装
运行Demo2ViewController 点击从手机相册选择 弹出系统权限提示框  选择  选择照片 选择了一张照片  跳转到相册 点击相册内部的相机 拍摄照片后 相册会多出2张 其中会多出一张相机背景的cell ，
点击 多出一张相机背景的cell  造成闪退
-[HXPhotoCameraViewCell canSelect]: unrecognized selector sent to instance 0x1074aaae0
点击选择其他照片 造成闪退
[HXPhotoCameraViewCell imageView]: unrecognized selector sent to instance 0x107acff80

**版本号**
1.HXPhotoPicker版本号：3.1.6
2.手机系统版本号：14.2
3.手机型号：任意机型

**复现步骤**
1. 遇到问题的相关效果、类是：Demo2ViewController 主要不是类  任何情景下 如上操作 都会出现闪退
2.具体的操作步骤是 如上

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by zhangchuangchuang** [comment]
最新的版本3.1.6 github 下载的项目同样问题 手机系统14.2

**Comment by SilenceLove** [comment]
最新demo没有这个问题，请确认是否是github下载的最新demo

**Comment by zhangchuangchuang** [comment]
确定是 最新的demo  cocoapods 下来的 也是最新的版本  都会出现这个问题

**Comment by zhangchuangchuang** [comment]
github 上下载的demo 运行 会出现    cocoapods 下来的 接入到项目中 也会出现  都是最新的 我上传几张截图试试

**Comment by zhangchuangchuang** [comment]
[https://github.com/zhangchuangchuang/Review_IMG/blob/master/WechatIMG10.jpeg](图1)
[https://github.com/zhangchuangchuang/Review_IMG/blob/master/WechatIMG11.jpeg](图2)
[https://github.com/zhangchuangchuang/Review_IMG/blob/master/WechatIMG6.jpeg](图3l)
[https://github.com/zhangchuangchuang/Review_IMG/blob/master/WechatIMG7.jpeg](图4)
[https://github.com/zhangchuangchuang/Review_IMG/blob/master/WechatIMG8.jpeg](图5)
[https://github.com/zhangchuangchuang/Review_IMG/blob/master/WechatIMG9.jpeg](图6)

顺序有可能排的不对

**Comment by SilenceLove** [comment]
图片打不开，看不了
你说的这个问题之前版本是有。3.1.6 修复了
HXVersion @"3.1.6" 你看一下这个是不是3.1.6
或者看 HXPhotoViewController.m 这个文件
- (void)customCameraViewController:(HXCustomCameraViewController *)viewController didDone:(HXPhotoModel *)model
这个方法里有没有这段代码
if ([HXPhotoTools authorizationStatusIsLimited]) {
        return;
    }

**Comment by zhangchuangchuang** [comment]
哦  不好意思 3.1.6 这个版本 已经解决了这个问题了 我用的3.1.5
