### ISSUE TITLE
圆形裁剪 出来的图片为什么会有白色方形背景  不是应该是圆形的图片吗

### ISSUE THREAD

**Issue by gaoguanbao** [SilenceLove/HXPhotoPicker#428]
圆形裁剪 出来的图片为什么会有白色方形背景  不是应该是圆形的图片吗？
如图：https://instabio.cdn.fotoee.com/20201216/06393042189

**Comment by gaoguanbao** [comment]
![06393042189](https://user-images.githubusercontent.com/20783580/102316238-8b5f3a80-3fb0-11eb-9877-e6457d376bc2.png)

**Comment by SilenceLove** [comment]
你可以打断点看裁剪的图片，是没有白色背景的

**Comment by gaoguanbao** [comment]
> 你可以打断点看裁剪的图片，是没有白色背景的

是的 不好意思 找到问题了 是我上传图片的时候将图片强制转成JPEG格式造成的
