### ISSUE TITLE
选择照片内存爆满崩溃

### ISSUE THREAD

**Issue by bigcoww** [SilenceLove/HXPhotoPicker#430]
**bug提交前阅读**
1.请先阅读【相关问题】，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
选择部分照片内存爆满,导致崩溃

**版本号**
1.HXPhotoPicker版本号：当前最新版本
2.手机系统版本号：12.4.9
3.手机型号：iPhone 6

**复现步骤**
1. 遇到问题的相关效果、类是：选取照片(有编辑框)
2.具体的操作步骤是：选取照片,自动跳转进入编辑,在编辑网格出现前,卡住,然后崩溃

**截图、GIF**
 Metal GPU Frame Capture Enabled
 Metal API Validation Enabled
[GatekeeperXPC] Connection to assetsd was interrupted or assetsd died
Message from debugger: Terminated due to memory issue

**Comment by howoften** [comment]
我也遇到这个问题，相册里有10+MB， 甚至几十MB，点击照片预览会直接崩溃，报memory issue
