### ISSUE TITLE
没有导入AFNetworking网络框架无法下载视频

### ISSUE THREAD

**Issue by qunwang6** [SilenceLove/HXPhotoPicker#431]
HXPhotoCommon.m:307	没有导入AFNetworking网络框架无法下载视频
3.1.1以后的版本会出现这个问题

**Comment by q52529** [comment]
我也遇到了这个问题。请问你解决了吗？明明是导入了的

**Comment by SilenceLove** [comment]
pod导入的请改成 "HXPhotoPicker/SDWebImage_AF" 或 "HXPhotoPicker/YYWebImage_AF"

**Comment by q52529** [comment]
> pod导入的请改成“ HXPhotoPicker / SDWebImage_AF”或“ HXPhotoPicker / YYWebImage_AF”

非常感谢！

**Comment by qunwang6** [comment]
> pod导入的请改成 "HXPhotoPicker/SDWebImage_AF" 或 "HXPhotoPicker/YYWebImage_AF"

谢谢👍

**Comment by qunwang6** [comment]
> pod导入的请改成 "HXPhotoPicker/SDWebImage_AF" 或 "HXPhotoPicker/YYWebImage_AF"

这个版本的AF含有UIWebview，不能上架到苹果商店，有没有其它方法？

**Comment by qunwang6** [comment]
@SilenceLove

**Comment by qunwang6** [comment]
@SilenceLove 
"HXPhotoPicker/SDWebImage_AF" 或 "HXPhotoPicker/YYWebImage_AF" 能否指定安装这个版本
pod 'AFNetworking', '~> 3.0', :subspecs => ['Reachability', 'Serialization', 'Security', 'NSURLSession']
