### ISSUE TITLE
点击拍照按钮闪退

### ISSUE THREAD

**Issue by ZXiaoPang** [SilenceLove/HXPhotoPicker#432]
**版本号**
1.HXPhotoPicker版本号：3.1.7
2.手机系统版本号：1.4.3
3.手机型号：8p

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。
![截屏2020-12-23 上午11 22 31](https://user-images.githubusercontent.com/13376829/102955561-2c01ad00-4511-11eb-9968-4c455778c807.png)

**Comment by ZXiaoPang** [comment]
![截屏2020-12-23 上午11 22 31](https://user-images.githubusercontent.com/13376829/102955608-420f6d80-4511-11eb-9f10-e274b69c1773.png)

**Comment by ZXiaoPang** [comment]
Thread 1: "Could not load NIB in bundle: 'NSBundle </private/var/containers/Bundle/Application/928F639A-92D8-49C9-B29E-D6E78B88FBA5/掌上智生活.app> (loaded)' with name 'HXCameraBottomView'"

**Comment by SilenceLove** [comment]
什么方式导入的

**Comment by ZXiaoPang** [comment]
cocoapods
