### ISSUE TITLE
videoMaximumSelectDuration不太准确

### ISSUE THREAD

**Issue by qingshanbugai** [SilenceLove/HXPhotoPicker#436]
**bug描述**
videoMaximumSelectDuration设置为15秒，实际上16秒的视频也能选择

**版本号**
1.HXPhotoPicker版本号：3.1.8
2.手机系统版本号：14.3
3.手机型号：iPhone6s

**复现步骤**
1. 遇到问题的相关效果、类是：视频和图片混合选择，有一个16秒的视频可以选择
2.具体的操作步骤是：把我这个16秒的视频保存到相册，指定HXPhotoManager.configuration.videoMaximumSelectDuration设置为15秒,弹出图片和视频选择器

**截图、GIF**

这是那个16秒的视频：https://user-images.githubusercontent.com/7610726/103969799-b731a280-51a1-11eb-80ad-1718098a45cd.mp4
这是测试视频：https://user-images.githubusercontent.com/7610726/103969859-dcbeac00-51a1-11eb-8743-ebc9f050a575.mp4

**Comment by SilenceLove** [comment]
我看看

**Comment by SilenceLove** [comment]
![image](https://user-images.githubusercontent.com/18083149/103985239-8a8e8280-51c3-11eb-8fc9-f9e28c543642.png)
仓库已更新，pod还没有。可以先手动改下这里代码
