### ISSUE TITLE
iPhone 12mini的适配没有做好,正常选择图片的时候,第一行会被导航栏挡住一部分

### ISSUE THREAD

**Issue by mistak1992** [SilenceLove/HXPhotoPicker#438]
**bug提交前阅读**
1.请先阅读【相关问题】，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
选择图片页面时，第一行会被导航栏挡住一部分

**版本号**
1.HXPhotoPicker版本号：v3.1.8
2.手机系统版本号：14.3
3.手机型号：iPhone 12mini

**复现步骤**
1. 遇到问题的相关效果、类是：
2.具体的操作步骤是：选择图片的时候

**截图、GIF**
https://camo.githubusercontent.com/6800f9453c000a698d3f00afe6b7acc975ea3fc9345a1aa7e4f0ddf4b0f3c5b1/687474703a2f2f74736e72686170702e6f73732d636e2d68616e677a686f752e616c6979756e63732e636f6d2f63686172746c652f73616d706c655f67726170685f322e504e47

这个问题可能是因为部分机型的状态栏高度不再是20/44，具体参考
https://www.jianshu.com/p/17a49d30e0e4

**Comment by SilenceLove** [comment]
已优化
