### ISSUE TITLE
只能选中一个图片或者一个视频的时候, 有bug

### ISSUE THREAD

**Issue by LoSenTrad** [SilenceLove/HXPhotoPicker#442]
最新版本3.1.7和3.1.8都有这样的问题
@property (nonatomic,strong) HXPhotoView *photoView;

 self.photoManager.configuration.photoMaxNum = 1;
 self.photoManager.configuration.videoMaxNum = 1;
 self.photoManager.configuration.maxNum = 1;

需求是: 打开相册,只能选中一个图片或者一个视频
发现bug(demo也是会如此):如果是通过HXPhotoView *photoView来弹出相册选择的话, 是不可以直接选择视频,只能编辑视频再确认, 同时编辑视频时长限制无效.
如果是不通过HXPhotoView *photoView来弹出相册是可以满足需求的.

**Comment by SilenceLove** [comment]
self.photoManager.configuration.photoMaxNum = 0;
self.photoManager.configuration.videoMaxNum = 0;
self.photoManager.configuration.maxNum = 1;
self.photoManager.configuration.selectTogether = NO;
这样设置
