### ISSUE TITLE
朋友你这个边下边播的逻辑，视频缓冲完了竟然没有保存到本地呢

### ISSUE THREAD

**Issue by wutao66** [SilenceLove/HXPhotoPicker#445]
**bug提交前阅读**
1.请先阅读【相关问题】，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.HXPhotoPicker版本号：？
2.手机系统版本号：？
3.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by SilenceLove** [comment]
没有这个边看边存的逻辑，目前有的是提前下载。和微信类似



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 桃子萌萌哒呀啦 <notifications@github.com&gt;
发送时间: 2021年1月23日 17:48
收件人: SilenceLove/HXPhotoPicker <HXPhotoPicker@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[SilenceLove/HXPhotoPicker] 朋友你这个边下边播的逻辑，视频缓冲完了竟然没有保存到本地呢 (#445)





 
bug提交前阅读
 1.请先阅读【相关问题】，里面有常见问题的解决方案；
 2.请先搜索已有的Issues，尝试找到相同问题的讨论；
 3.请先阅读相关类的API、源码，尝试从源码找到答案；
 4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；
 
bug描述
 请简单描述你的bug现象。
 
版本号
 1.HXPhotoPicker版本号：？
 2.手机系统版本号：？
 3.手机型号：？
 
复现步骤
  
遇到问题的相关效果、类是：？
 2.具体的操作步骤是：？ 
 
截图、GIF
 提供bug出现时的截图或者GIF。
