### ISSUE TITLE
拍完照片后点击，就选择当前你拍照的这张照片预览崩溃

### ISSUE THREAD

**Issue by zhoumingwu** [SilenceLove/HXPhotoPicker#446]
+ (PHImageRequestID)requestImageDataForAsset:(PHAsset *)asset
                                     options:(PHImageRequestOptions *)options
                                  completion:(void (^)(NSData *imageData,  UIImageOrientation orientation, NSDictionary<NSString *, id> *info))completion {
    PHImageRequestID requestID;
    if (@available(iOS 13.0, *)) {
        requestID = [[PHImageManager defaultManager] requestImageDataAndOrientationForAsset:asset options:options resultHandler:^(NSData * _Nullable imageData, NSString * _Nullable dataUTI, CGImagePropertyOrientation orientation, NSDictionary * _Nullable info) {
            if (completion) {
                dispatch_async(dispatch_get_main_queue(), ^{
                    completion(imageData, [self imageOrientationWithCGImageOrientation:orientation], info);
                });
            }
        }];

崩溃再这里

**Comment by zhoumingwu** [comment]
机型 iPhone xr
版本：iOS 14.2

**Comment by SilenceLove** [comment]
#452
