### ISSUE TITLE
选择图片崩溃

### ISSUE THREAD

**Issue by BestKai** [SilenceLove/HXPhotoPicker#452]
**bug提交前阅读**
1.请先阅读【相关问题】，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
`
        _photoManager.configuration.requestOriginalImage = YES;
        _photoManager.configuration.requestImageAfterFinishingSelection = YES;
        _photoManager.configuration.singleJumpEdit = NO;
        _photoManager.configuration.singleSelected = YES;
        _photoManager.configuration.photoCanEdit = NO;
        
        _photoManager.configuration.showOriginalBytes = NO;
        _photoManager.configuration.showOriginalBytesLoading = YES;
`
这样设置，打开选择器之后拍摄一张照片，选择刚刚拍摄的照片崩溃、崩溃信息如下：
![image](https://user-images.githubusercontent.com/8436462/110057464-98afe800-7d9b-11eb-92f1-3d95ffe0423d.png)

**版本号**
1.HXPhotoPicker版本号：oc - 3.1.8？
2.手机系统版本号：14.4？
3.手机型号：6s？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by xiaohange** [comment]
@SilenceLove 麻烦给看下～

**Comment by BestKai** [comment]
需要设置  saveSystemAblum  才能不崩溃，不过这里还是建议做个兼容

**Comment by SilenceLove** [comment]
我这边试了很多次没出现崩溃...manager的配置还有其他的吗?

**Comment by BestKai** [comment]
demo  地址  https://github.com/BestKai/HXPhotoPickerExample.git  直接用微信朋友圈 那个功能从相册选择 就可以复现

**Comment by SilenceLove** [comment]
找到问题了，等下修复

**Comment by SilenceLove** [comment]
已更新3.1.9版本
