### ISSUE TITLE
看图说话

### ISSUE THREAD

**Issue by 295060456** [SilenceLove/HXPhotoPicker#454]
![image](https://user-images.githubusercontent.com/13795605/111260026-acd4ce80-8652-11eb-8338-18fc4e8ef2fa.png)
这怎么回事？怎么办

**Comment by SilenceLove** [comment]
什么情况下出现的

**Comment by 295060456** [comment]
下次版本更新的时候，把这一句加上。
![image](https://user-images.githubusercontent.com/13795605/112286433-e5615180-8cbd-11eb-956d-b9bbae504ac3.png)
必须加载这里。
#import "UINavigationController+FDFullscreenPopGesture.h"和他有冲突，方法交换了。你这个HXPhotoViewController没有暴露出去
