### ISSUE TITLE
只用于外部预览查看图片会闪一下

### ISSUE THREAD

**Issue by fanlilinSaber** [SilenceLove/HXPhotoPicker#459]
1. 能否把外部预览的单独独立出来
2. [self hx_presentPreviewPhotoControllerWithManager:photoManager
                                         previewStyle:HXPhotoViewPreViewShowStyleDark
                                         currentIndex:currentIndex
                                            photoView:nil]; 
如果 photoView = nil  我看了 里面的逻辑 始终拿不到图片是否已经下载，也就是获取不到图片的原始大小一直都是200 * 200 所以每次都会闪一下

我现在临时的解决方案是在
![image](https://user-images.githubusercontent.com/26476506/113964430-11eca000-985e-11eb-8045-e93202310658.png)
暂时可以修复单独作为外部预览图片 闪跳一下的问题

希望作者能解决这个bug

**Comment by vinsent** [comment]
相同问题, 但按照 @fanlilinSaber 的临时解决方案也无效果
```
    if (!self.photoView && image) {
        model.imageSize = CGSizeMake(image.size.width * image.scale, image.size.height * image.scale);
    }
```

**Comment by FeiJiuLin** [comment]
#
<img width="879" alt="WeChatcc43cb34b2aa0f160503ec6e2c0e1292" src="https://user-images.githubusercontent.com/18732459/223024293-937a17f1-391a-469e-a437-bcd81e96de03.png">
如果是本地图片，直接读取渲染，如果用SDAnimatedImageView来加载图片需要修改
- (void)displayLayer:(CALayer *)layer
{
    if (self.currentFrame) {
        layer.contentsScale = self.animatedImageScale;
        layer.contents = (__bridge id)self.currentFrame.CGImage;
    } else {
        // If we have no animation frames, call super implementation. iOS 14+ UIImageView use this delegate method for rendering.
        if ([UIImageView instancesRespondToSelector:@selector(displayLayer:)]) {
           [super displayLayer:layer];
        }
    }
  
}
