### ISSUE TITLE
照片唯一id问题

### ISSUE THREAD

**Issue by xiaohange** [SilenceLove/HXPhotoPicker#460]
业务情景：上传过的照片不让再次上传，以照片唯一标识符去存储上传记录，发现都不唯一。 请教照片到底用什么作为唯一标识呢？ @SilenceLove 

1.最初尝试 asset.localIdentifier 作为照片唯一标识，发现升级iOS，或升级版本后，重启设备等这个标识符都会重置。

2.尝试以照片名字作为标识符： 发现在iOS14以后部分设备这个名字还不唯一，并且iOS13废弃了`PHImageFileURLKey`
```
[[PHImageManager defaultManager] requestImageForAsset:asset targetSize:size contentMode:PHImageContentModeDefault options:options resultHandler:^(UIImage * _Nullable result, NSDictionary * _Nullable info) {
    NSURL *url = [info valueForKey:@"PHImageFileURLKey"];
    NSString *str = [url absoluteString];   //url>string
    NSArray *arr = [str componentsSeparatedByString:@"/"];
   NSString *imgName = [arr lastObject];
   NSLog(@"imgName:%@",imgName);
}]
```

3.尝试以照片名字作为标识符： 新的方法获取照片名字。

```
PHAssetResource * resource = [[PHAssetResource assetResourcesForAsset: asset] firstObject];
NSString *privateFileURL = [resource valueForKey:@"privateFileURL"];
// 图片名字
 NSString *lastImgName = [[privateFileURL  lastPathComponent ] stringByDeletingPathExtension];
```

**Comment by LiuJinfan** [comment]
你这个需求用照片的hash值是最好的方法

**Comment by xiaohange** [comment]
> 你这个需求用照片的hash值是最好的方法

这个是唯一不变的吗？不会因为卸载，升级等改变吧？

**Comment by LiuJinfan** [comment]
> > 你这个需求用照片的hash值是最好的方法
> 
> 这个是唯一不变的吗？不会因为卸载，升级等改变吧？

理论上只要文件内容没变,hash 就不会变, 甚至你不同手机上的同一张照片的hash都是唯一的

**Comment by xiaohange** [comment]
> > > 你这个需求用照片的hash值是最好的方法
> > 
> > 
> > 这个是唯一不变的吗？不会因为卸载，升级等改变吧？
> 
> 理论上只要文件内容没变,hash 就不会变, 甚至你不同手机上的同一张照片的hash都是唯一的

使用这个库我看没有hash这个属性

**Comment by LiuJinfan** [comment]
hash跟这个库没关系，你直接对图片进行hash处理就行了，你可以把hash值看做是一张图片的指纹，跟每张图片的指纹是唯一且跟图片一一对应的。具体的方法可以自行百度。

**Comment by xiaohange** [comment]
> hash跟这个库没关系，你直接对图片进行hash处理就行了，你可以把hash值看做是一张图片的指纹，跟每张图片的指纹是唯一且跟图片一一对应的。具体的方法可以自行百度。

谢谢你的解答，还是决定保持用 `asset.localIdentifier `了。
