### ISSUE TITLE
去相册选择图片，在相机胶卷里面有拍照功能的情况下，点击取消或者返回，会卡住主线程。

### ISSUE THREAD

**Issue by dongpeng66** [SilenceLove/HXPhotoPicker#469]
**bug提交前阅读**
1.请先阅读【相关问题】，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
去相册选择图片，在相机胶卷里面有拍照功能的情况下，点击取消或者返回，会卡住主线程，iOS12以上不会有问题。
设置photoManager.configuration.openCamera=NO;可以解决问题。

**版本号**
1.HXPhotoPicker版本号：3.1.9
2.手机系统版本号:9.3.1
3.手机型号：iPhone 6s

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by SilenceLove** [comment]
Ios12以下可以设置cell不预览相机

**Comment by dongpeng66** [comment]
你好，我根据这个文章如下文章：
https://stackoverflow.com/questions/11905505/avcapturesession-stop-running-take-a-long-long-time

修改了HXPhotoViewController.m的这些方法,去提前AVCaptureSession  stopRunning，不会出现卡顿了，目前不知道会不会有其他影响
@property (strong, nonatomic) HXPhotoCameraViewCell *cellw;
- (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath {
HXPhotoCameraViewCell *cell = [collectionView dequeueReusableCellWithReuseIdentifier:@"HXPhotoCameraViewCellId" forIndexPath:indexPath];
        self.cellw=cell;
        cell.bgColor = self.manager.configuration.photoListTakePhotoBgColor;
        cell.model = model;
        if (!self.cameraCell) {
            cell.cameraImage = [HXPhotoCommon photoCommon].cameraImage;
            self.cameraCell = cell;
        }
        if (!self.cellCanSetModel) {
            cell.hidden = YES;
        }
        return cell;
}
- (void)didCancelClick {
    if (self.cellw) {
        [self.cellw stopRunning];
    }
    if (self.manager.configuration.albumShowMode == HXPhotoAlbumShowModePopup) {
        if (self.manager.configuration.photoListChangeTitleViewSelected) {
            self.manager.configuration.photoListChangeTitleViewSelected(NO);
        }
        [self.manager cancelBeforeSelectedList];
    }
    if ([self.delegate respondsToSelector:@selector(photoViewControllerDidCancel:)]) {
        [self.delegate photoViewControllerDidCancel:self];
    }
    if (self.cancelBlock) {
        self.cancelBlock(self, self.manager);
    }
    self.manager.selectPhotoing = NO;
    BOOL selectPhotoCancelDismissAnimated = self.manager.selectPhotoCancelDismissAnimated;
    [self dismissViewControllerAnimated:selectPhotoCancelDismissAnimated completion:^{
        if ([self.delegate respondsToSelector:@selector(photoViewControllerCancelDismissCompletion:)]) {
            [self.delegate photoViewControllerCancelDismissCompletion:self];
        }
    }];
}

**Comment by dongpeng66** [comment]
你好，我根据这个文章如下文章：
https://stackoverflow.com/questions/11905505/avcapturesession-stop-running-take-a-long-long-time

修改了HXPhotoViewController.m的这个方法,去提前AVCaptureSession stopRunning，点击取消解决了卡主线程的问题，但是返回相册还是会卡住主线程，大佬目前还没有修改返回相册按钮的事件，大佬这样子修改可行否？

(void)didCancelClick {
if (self.cameraCell.startSession && self.cameraCell) {
          [self.cameraCell starRunning];
 }
if (self.manager.configuration.albumShowMode == HXPhotoAlbumShowModePopup) {
if (self.manager.configuration.photoListChangeTitleViewSelected) {
self.manager.configuration.photoListChangeTitleViewSelected(NO);
}
[self.manager cancelBeforeSelectedList];
}
if ([self.delegate respondsToSelector:@selector(photoViewControllerDidCancel:)]) {
[self.delegate photoViewControllerDidCancel:self];
}
if (self.cancelBlock) {
self.cancelBlock(self, self.manager);
}
self.manager.selectPhotoing = NO;
BOOL selectPhotoCancelDismissAnimated = self.manager.selectPhotoCancelDismissAnimated;
[self dismissViewControllerAnimated:selectPhotoCancelDismissAnimated completion:^{
if ([self.delegate respondsToSelector:@selector(photoViewControllerCancelDismissCompletion:)]) {
[self.delegate photoViewControllerCancelDismissCompletion:self];
}
}];
}
