### ISSUE TITLE
有人反馈集成之后安装包太大的问题吗

### ISSUE THREAD

**Issue by Jacky-LinPeng** [SilenceLove/HXPhotoPicker#473]
<img width="289" alt="image" src="https://user-images.githubusercontent.com/15797691/124216302-861aa500-db28-11eb-863d-de4b7d5e0969.png">

**Comment by szmichaelyb** [comment]
有啊，肯定的~

**Comment by Jacky-LinPeng** [comment]
> 有啊，肯定的~

请教一下，老铁有好的方案处理吗？
