### ISSUE TITLE
拍摄视频不管怎么设置都只能是15秒

### ISSUE THREAD

**Issue by boweibowei** [SilenceLove/HXPhotoPicker#476]
**bug提交前阅读**
1.请先阅读【相关问题】，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.HXPhotoPicker版本号：？
2.手机系统版本号：？
3.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by zengchao1510** [comment]
我也发现了这个问题，只能是15秒，编辑视频也只能是15秒，设置其他参数都没用

**Comment by SilenceLove** [comment]
相机最大时长不能超过 `videoMaximumSelectDuration`选择视频的最大时长，如果超过了会按视频的最大选择时长处理,
还有一个设置相机拍摄时长要在`configuration.type`配置类型赋值的后面，不然会被覆盖变成15秒
