### ISSUE TITLE
多选图片的顺序与在相册中选择的图片顺序不一致

### ISSUE THREAD

**Issue by doubleJJJJ** [SilenceLove/HXPhotoPicker#486]
**bug描述**
多选图片的顺序与在相册中选择的图片顺序不一致

**复现步骤**
用hx_presentSelectPhotoControllerWithManager跳转本地相册多选图片，然后用requestPreviewImageWithSize获取预览图，发现获取图片和本地选择相册图片的顺序不一致，是否要自己进行排序？还是有对应的API可以设置呢？

**Comment by SilenceLove** [comment]
这是异步的
