### ISSUE TITLE
适配iOS 15 后，点击相机，头部的出现白色导航栏

### ISSUE THREAD

**Issue by weizhangCoder** [SilenceLove/HXPhotoPicker#488]
**bug提交前阅读**
1.请先阅读【相关问题】，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
适配iOS 15 的时候，点击相机，顶部会有白色导航栏出现，

**版本号**
1.HXPhotoPicker版本号：3.2.4
2.手机系统版本号：iOS 15.02
3.手机型号：iPhone11

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？
iOS 15 新增的适配代码，在导航栏的基类里面适配添加下面代码，点击相机的手就会出现，注释这些代码，就没有问题

    // 如果是15的系统需要这样设置，非15系统使用老版方法
    if (@available(iOS 15.0, *)) {
        UINavigationBarAppearance *barApp = [UINavigationBarAppearance new];
        [barApp configureWithOpaqueBackground];
        barApp.titleTextAttributes = navBar.titleTextAttributes;
        barApp.backgroundColor = navBar.barTintColor; // 设置为你项目中的颜色
        navBar.scrollEdgeAppearance = barApp; // 可滑动界面配置
        navBar.standardAppearance = barApp; // 普通页面配置
    }

**截图、GIF**
提供bug出现时的截图或者GIF。
![1591634288705_ pic](https://user-images.githubusercontent.com/11644326/137462334-0d04a572-80e6-4470-af32-4dca36a42e1b.jpg)

**Comment by DoKeer** [comment]
@SilenceLove 你的修改还是有问题。建议如图这样。
![image](https://user-images.githubusercontent.com/12821785/144964109-ced51676-b7c4-4ed9-8d79-6372f379317f.png)
