### ISSUE TITLE
iOS 12.5.4 拍摄视频闪退

### ISSUE THREAD

**Issue by liuchunlao** [SilenceLove/HXPhotoPicker#494]
**bug描述**
iOS 12.5.4 拍摄视频闪退

**版本号**
1.HXPhotoPicker版本号：3.2.4，3.2.8都存在此问题
2.手机系统版本号：iOS [12.5.4](url)
3.手机型号：iPhone 6Plus

**复现步骤**
1. 遇到问题的相关效果、类是：运行demo，进行视频拍摄时闪退。 定位类：HXCustomCameraViewController
2.具体的操作步骤是：运行demo，demo7，选择相册，拍摄，长按录制视频，超过3秒后，松手 ，闪退

**Comment by SilenceLove** [comment]
使用最新版，最新版已经修复

**Comment by SilenceLove** [comment]
崩溃日志发一下
