### ISSUE TITLE
demo 面的微信朋友圈选择完照片后显示问题

### ISSUE THREAD

**Issue by weizhangCoder** [SilenceLove/HXPhotoPicker#497]
**bug提交前阅读**
1.请先阅读【相关问题】，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
使用demo 里面的微信朋友圈选择照片后，显示问题

**版本号**
1.HXPhotoPicker版本号：3.2.8
2.手机系统版本号：15.0.2
3.手机型号：iPhone 11

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：

demo 里面的朋友圈选择照片后，显示问题

**截图、GIF**
提供bug出现时的截图或者GIF。
![1701637650319_ pic](https://user-images.githubusercontent.com/11644326/142982161-1800dc62-5ab0-4c86-b4ca-19bb9aa3dc76.jpg)

**Comment by SilenceLove** [comment]
demo没这问题啊

**Comment by weizhangCoder** [comment]
https://user-images.githubusercontent.com/11644326/143416685-89131cfb-d6a0-4a4b-bc11-67ebafa2ffe6.mp4

我研究了代码，还没有找到哪里问题，目前在系统iOS 15.0.2， 15.1.0 都有这样的问题，你可以把视频慢放，就可以清楚的看到了。

**Comment by SilenceLove** [comment]
知道是啥问题了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: weizhang ***@***.***&gt;
发送时间: 2021年11月25日 17:38
收件人: SilenceLove/HXPhotoPicker ***@***.***&gt;
抄送: Silence ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [SilenceLove/HXPhotoPicker] demo 面的微信朋友圈选择完照片后显示问题 (Issue #497)





 
https://user-images.githubusercontent.com/11644326/143416685-89131cfb-d6a0-4a4b-bc11-67ebafa2ffe6.mp4
 
我研究了代码，还没有找到哪里问题，目前在系统iOS 15.0.2， 15.1.0 都有这样的问题，你可以把视频慢放，就可以清楚的看到了。
