### ISSUE TITLE
在【HXPhotoManager.m】-【photoModelWithAsset:】-isICloud判断问题

### ISSUE THREAD

**Issue by futurerirsy** [SilenceLove/HXPhotoPicker#499]
### **HXPhotoManager.m**
<img width="612" alt="Screenshot 2021-11-25 at 9 29 52 PM" src="https://user-images.githubusercontent.com/20762503/143450321-c1491a8b-5ada-4c61-b034-e0dd1ed41345.png">

### ** 实行结果**

![FullSizeRender(1)](https://user-images.githubusercontent.com/20762503/143439714-1eb5bc98-e598-4015-90b1-cb9c5ad91acf.jpg)

### **修改如下：**
<img width="783" alt="Screenshot 2021-11-25 at 9 28 50 PM" src="https://user-images.githubusercontent.com/20762503/143450386-5e23b48e-809a-4e38-a7e9-9a39503377de.png">

### ** 实行结果**

![FullSizeRender](https://user-images.githubusercontent.com/20762503/143439825-da21f658-d165-45f7-93f0-823470011fb2.jpg)

我觉得修改的比较好。
你们看怎么样？
有问题吗？
... ... ...

**Comment by SilenceLove** [comment]
这样在获取照片列表的时候耗时会变长
