### ISSUE TITLE
能否自定义某些页面

### ISSUE THREAD

**Issue by friendsheeps** [SilenceLove/HXPhotoPicker#510]
项目需求需要自定义一些页面，例如图片编辑页面，需要隐藏部分功能，但页面是由xib编写，经过编译后变成了.nib文件，Xcode无法打开，请问有什么方式可以进行一些微调，或者能否暴露更多配置属性才控制现有功能动显示和隐藏。非常感谢🙏

version 3.3.1

**Comment by 19aneng** [comment]
+1,没想到是去年的事情....
