### ISSUE TITLE
选择HEIC格式图片写入临时目录生成URL后，得到的文件由原来的1.9MB变成27MB

### ISSUE THREAD

**Issue by lylcf** [SilenceLove/HXPhotoPicker#513]
选择了HEIC格式的图片后，调用以下方法写入文件临时准备上传：
HXPhotoModel getImageURLWithResultHandler:
内部代码执行到这里时，imageData还是正常的1.9MB
![截屏2022-04-09 下午2 54 46](https://user-images.githubusercontent.com/19165195/162560774-067e6564-8016-415d-b175-e4ac93d8bc5a.png)
接着执行，UIImagePNGRepresentation的时候问题就来了，转换出来的data直接变成27.5MB
![截屏2022-04-09 下午3 00 53](https://user-images.githubusercontent.com/19165195/162560808-84da8870-ad98-41e0-84e4-6e77c52d7898.png)
建议如果事先能得到图片的二进制Data格式，就直接通过Data判断图片格式

另外希望优化这个部分，UIImagePNGRepresentation本身耗时很长，不适合当做if判断条件
![截屏2022-04-09 下午3 05 52](https://user-images.githubusercontent.com/19165195/162560930-11496c0c-154c-4b29-86a2-ae28dfde6795.png)

**Comment by iPermanent** [comment]
HEIC是压缩格式的图像，写入的时候恢复成JPG或者PNG体积变大是一个正常现象
