### ISSUE TITLE
组件里面以inherit! :search_paths 方式链接代码，hx_photoPickerBundle 获取不到资源

### ISSUE THREAD

**Issue by fanlilinSaber** [SilenceLove/HXPhotoPicker#524]
我们通过pod 正常的方式导入库对里面的资源访问是没有问题的，但是我们的组件化工程为了解决其他组件单例共享必须得使用以下方式 

target 'ZJKGoods' do
pod 'HXPhotoPicker/SDWebImage', '~> 3.3.1'
  # Pods for ZJKGoods
  
  target 'ZJKGoods IOS Example' do
    # Comment the next line if you don't want to use dynamic frameworks
    inherit! :search_paths
    
    # Pods for ZJKGoods IOS Example
  end

end

就会造成资源hx_photoPickerBundle的资源读取问题
这边我找到了优化的代码，可以解决在以任何形式导入在工程中不会引起资源获取不到的问题。希望作者能参考优化下

#import "NSBundle+HXPhotoPicker.h"
#import "HXPhotoCommon.h"

@interface HXPhotopickerBundle: NSObject
@end

@implementation HXPhotopickerBundle

+ (NSBundle *)resourceBundle
{
    static NSBundle *resourceBundle = nil;
    if (!resourceBundle) {
        NSBundle *mainBundle = [NSBundle bundleForClass:self];
        NSString *resourcePath = [mainBundle pathForResource:@"HXPhotoPicker" ofType:@"bundle"];
        resourceBundle = [NSBundle bundleWithPath:resourcePath] ?: mainBundle;
    }
    return resourceBundle;
}

@end

@implementation NSBundle (HXPhotoPicker)
+ (instancetype)hx_photoPickerBundle {
    return [HXPhotopickerBundle resourceBundle];
}

**Comment by fanlilinSaber** [comment]
作者在吗，麻烦更新下这个问题呢，每次更新了之后 都要手动修改这部分的代码

**Comment by SilenceLove** [comment]
可以提一个pr

**Comment by fanlilinSaber** [comment]
明白了&nbsp;


只有你
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月28日(星期一) 下午5:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SilenceLove/HXPhotoPicker] 组件里面以inherit! :search_paths 方式链接代码，hx_photoPickerBundle 获取不到资源 (Issue #524)





 
可以提一个pr

**Comment by fanlilinSaber** [comment]
更新了新版本之后，可以访问到正确路径了。。。
