### ISSUE TITLE
iOS16 跳转到选择相册页面卡死，主要是这个属性 UIModalPresentationOverFullScreen

### ISSUE THREAD

**Issue by KeepWatchOn** [SilenceLove/HXPhotoPicker#528]
iOS16 跳转到选择相册页面内存暴增卡死，主要是这个属性 UIModalPresentationOverFullScreen，注释掉就正常，有人有解决方法吗？

**Comment by ljiosDeveloper** [comment]
解决了吗??

**Comment by KeepWatchOn** [comment]
> 解决了吗??

没有

**Comment by wuruijie** [comment]
有人解决了吗 大家都遇到了啊

**Comment by KeepWatchOn** [comment]
> 有人解决了吗 大家都遇到了啊

我项目里导致卡死的原因是引入了这个类NSDictionary-NilSafe，iOS16下会循环调用内部的方法，把该类全部注释掉就正常了

**Comment by Moshimol** [comment]
> 

还有种方法 如果不能完全移除NSDictionary-NilSafe 是下这个 [处理方法](https://blog.csdn.net/yunhuaikong/article/details/127059276)
