### ISSUE TITLE
iOS16.0系统[[UIBarButtonItem alloc] initWithTitle初始化会导致奔溃问题

### ISSUE THREAD

**Issue by 1477095176** [SilenceLove/HXPhotoPicker#531]
**bug提交前阅读**
1.请先阅读【相关问题】，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
iOS16.0系统[[UIBarButtonItem alloc] initWithTitle初始化会导致奔溃问题

![image](https://user-images.githubusercontent.com/114569581/192730462-7a9ad59d-911c-4a0b-8b5b-121dbac1c4e6.png)

**版本号**
1.HXPhotoPicker版本号：3.3.2
2.手机系统版本号：16.0
3.手机型号：iphone 12 pro

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by githubYsc** [comment]
> **bug提交前阅读** 1.请先阅读【相关问题】，里面有常见问题的解决方案； 2.请先搜索已有的Issues，尝试找到相同问题的讨论； 3.请先阅读相关类的API、源码，尝试从源码找到答案； 4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；
> 
> **bug描述** iOS16.0系统[[UIBarButtonItem alloc] initWithTitle初始化会导致奔溃问题
> 
> ![image](https://user-images.githubusercontent.com/114569581/192730462-7a9ad59d-911c-4a0b-8b5b-121dbac1c4e6.png)
> 
> **版本号** 1.HXPhotoPicker版本号：3.3.2 2.手机系统版本号：16.0 3.手机型号：iphone 12 pro
> 
> **复现步骤**
> 
> 1. 遇到问题的相关效果、类是：？
>    2.具体的操作步骤是：？
> 
> **截图、GIF** 提供bug出现时的截图或者GIF。



> 

看看是不是使用了NSDictionary-NilSafe 库，移除掉可解
