### ISSUE TITLE
能否强制裁剪

### ISSUE THREAD

**Issue by anchao-lu** [SilenceLove/HXPhotoPicker#540]
要求必须裁剪才能上传，这个应该怎么实现

**Comment by iPermanent** [comment]
_manager.configuration.photoEditConfigur.onlyCliping = YES; 
demo里有

**Comment by anchao-lu** [comment]
不是这个，我的意思是能不能强制用户选择图片后跳转编辑页面，之后才能去上传

**Comment by Lovezysong** [comment]
singleJumpEdit
