### ISSUE TITLE
NSLocationWhenInUseUsageDescription 问题

### ISSUE THREAD

**Issue by Nododo** [SilenceLove/HXPhotoPicker#546]
感谢作者开发这么好的库

但提交appstore需要添加NSLocationWhenInUseUsageDescription说明

但如果只用相册功能，就没必要使用地理位置的api，建议把地理位置剥离出来，方便使用。

感谢哈

**Comment by SilenceLove** [comment]
```
pod 'HXPhotoPicker/NoLocation'
```

**Comment by Nododo** [comment]
> ```
> pod 'HXPhotoPicker/NoLocation'
> ```

你好，能开一个oc版本的 无地理位置的分支吗？

我找了一下历史分支，没找到啊


谢谢
