### ISSUE TITLE
图片截取的比例不正确，

### ISSUE THREAD

**Issue by xyl-private** [SilenceLove/HXPhotoPicker#547]
**bug描述**

// 固定裁剪比例
configuration.photoEditConfigur.aspectRatio = HXPhotoEditAspectRatioType_1x1;

图片截取设置的比例是1x1，截取后导出的图片比例是900:901

**版本号**
1.HXPhotoPicker版本号：3.3.2
2.手机系统版本号：16.4
3.手机型号：iPhone 12 Pro Max

**Comment by SilenceLove** [comment]
使用最新版本
