### ISSUE TITLE
error in XCode 14.3 , linker command failed with exit code 1 

### ISSUE THREAD

**Issue by wengyunqiang** [SilenceLove/HXPhotoPicker#548]
I used swift for my project.  cocoaPod was introduced into the project： pod 'HXPhotoPicker', '~> 3.3.2'

XCode Version : 14.3

ld: file not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphoneos.a
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by iPermanent** [comment]
Just add these code to your podfile on the end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
               end
          end
   end
end

otherwise you can set you platform to a higher target 
just like
 platform :ios, '12.0'
at the begining of the podfile

**Comment by iPermanent** [comment]
one more thing, as you use swift, I suggest you to try the version 4.0.3, it's more powerful, and really good to use, and full with swift
