### ISSUE TITLE
相册里有超大分辨率图预览选择时内存爆增甚至可能crash

### ISSUE THREAD

**Issue by iPermanent** [SilenceLove/HXPhotoPicker#549]
**bug描述**
在相册里存在一张超大分辨率图时，缩略图显示正常，但是点进去以后，由于分辨率极大，会导致内存爆增，这块是否可以考虑改一下使用CATiledLayer 来分块加载显示呢

补充：
图片分辨率为20000*15000左右，在较旧设备上极易造成内存爆掉crash，13 pro及以上只是会有点卡顿问题

**Comment by SilenceLove** [comment]
可以使用4.0版本

**Comment by iPermanent** [comment]
使用4.0.3版本验证，依旧会内存爆掉crash
重现步骤：
将超大图放到相册里
调起HXPhotoPicker 选择预览该超大图，开始时图片模糊状态，静待图片加载完全，当加载完时，内存爆掉，app crash，图片过大无法上传，图片大小约在19.6M，分辨率 20158 × 15511

**Comment by SilenceLove** [comment]
图片可以发我一份吗

**Comment by iPermanent** [comment]
> 图片可以发我一份吗

https://1drv.ms/i/s!Ahq5bxsAW8BWgVI1Off-giaTxwBB?e=8Rx3K6 
图片大于10M无法上传，我放在one drive里了，这里是链接
