### ISSUE TITLE
关于3.x -> 4.x的语言更换

### ISSUE THREAD

**Issue by jiasongs** [SilenceLove/HXPhotoPicker#551]
建议由Objective-C全面转为Swift时，可以增加subpod的形式保留Objc的版本，或者增加一个Swift版的podspec，Objc版本代码资源保持现有结构。类似 https://github.com/ReactiveCocoa/ReactiveObjC

现在仅仅是更改了Tag来进行语言更换，会导致fork项目的Objc开发者无法合并主分支，也会让混编项目无法同时用Objc版本和Swift版本，对于老项目而言，升级4.x成本会比较大。

**Comment by SilenceLove** [comment]
了解，会加一个Objc的podspec

**Comment by SilenceLove** [comment]
OC版本
```pod 'HXPhotoPickerObjC'```
