### ISSUE TITLE
选择图片, 默认不进行tools 修改的话, 直接点击完成 会返回原图, 而不是 裁剪后的图片:  示例Demo Moment中 点击背景图, 直接点击完成 输出图片不是1:1

### ISSUE THREAD

**Issue by SnailLoveSmile** [SilenceLove/HXPhotoPicker#553]

**Comment by zt-zhang** [comment]
![image](https://github.com/SilenceLove/HXPhotoPicker/assets/65379275/70563bbb-642d-4dad-9402-6b3bedfadc0f)
我改了这块可以了

**Comment by SilenceLove** [comment]
查看demo正常

**Comment by zt-zhang** [comment]
https://github.com/SilenceLove/HXPhotoPicker/assets/65379275/1e6be13f-0d81-4cc4-92fd-738da842f81b

使用 master 的 HXPhotoPickerExample targets
Avatar Picker 
不进行圆形裁剪
设置默认宽高比为1:1
选择照片
在编辑页面不进行任何操作，直接点击完成
预览图片，图片未裁剪
期望：图片裁剪为1:1
