### ISSUE TITLE
版本3.3.2 拍照后不会自动跳转编辑页

### ISSUE THREAD

**Issue by YelCode** [SilenceLove/HXPhotoPicker#554]
版本3.3.2 拍照后不会自动跳转编辑页
设置了cameraPhotoJumpEdit = YES 无效
还有个问题？拍照编辑完，直接返回图片，目前还会返回到列表 再去选 多此一举啊

**Comment by SilenceLove** [comment]
旧版本不再维护，请使用4.0版本
