### ISSUE TITLE
视频部分请求头如何设置

### ISSUE THREAD

**Issue by ccchzxj** [SilenceLove/HXPhotoPicker#555]
最近项目添加了防盗码，要求在调取资源的时候添加对应请求头，sdwebimage在appdelegate可以统一设置，但是视频部分必须单独去修改，项目内部分网络视频使用了HXPreView去读取，这部分是否有可以统一设置请求头的方式

**Comment by SilenceLove** [comment]
4.0 swift版本有配置

**Comment by ccchzxj** [comment]
项目里的主要代码是OC，一时半会儿也不能直接改swift，OC调用swift的方法也有问题，OC版本没有吗

**Comment by SilenceLove** [comment]
https://github.com/SilenceLove/HXPhotoPickerObjC
OC代码仓库，你可以修改一下提个pr🤝
