### ISSUE TITLE
你好，感谢分享这么好用的库，怎么去掉裁剪框和编辑，只保留图片预览

### ISSUE THREAD

**Issue by PPLLock** [SilenceLove/HXPhotoPicker#556]
你好，感谢分享这么好用的库，怎么去掉裁剪框和编辑，只保留图片预览

**Comment by SilenceLove** [comment]
`config.editorOptions = []`
`config.previewView.bottomView.isHiddenEditButton = true`

**Comment by PPLLock** [comment]
好的👌非常感谢
