### ISSUE TITLE
English Documentation

### ISSUE THREAD

**Issue by Xenolion** [SilenceLove/HXPhotoPicker#557]
I found it a very good library but the problem is I  do not find a great english documentation for the Library. The Quick Start  in english is good. But based on the fact that everything else is in Chinese I am having a problem  participating  in the Library.

**Comment by SilenceLove** [comment]
What problems did you encounter, I can help you here🤝

**Comment by Xenolion** [comment]
Oooh  sorry I have found  that there is some english comments inside the code. Sorry for the false alarm. I will sponsor once I finish testing and use the library in production. @SilenceLove

**Comment by Xenolion** [comment]
@SilenceLove how can I make the user  pick a square image or pick an image and force the user to crop it as a square. This is particularly useful when you want the photo to be of a certain dimension in order to display them properly. For instance  a square image is good if it is used as a profile picture, a landscape image is useful to be used as a cover picture etc. How can I achieve to force user to pick a square image?

**Comment by SilenceLove** [comment]
you can set like this
```
config.selectMode = .single
config.selectOptions = .photo
config.photoSelectionTapAction = .openEditor
config.editor.isFixedCropSizeState = true
config.editor.cropSize.aspectRatios = []
config.editor.cropSize.isResetToOriginal = false
config.editor.cropSize.isFixedRatio = true
/// set a fixed ratio
config.editor.cropSize.aspectRatio = .init(width: 1, height: 1)
```

**Comment by Xenolion** [comment]
Wow. You  did a wonderful job in this library.

One more last thing. Is it possible to request images and video compressed to a certain size parameters? Request a video of not  more than 480p or an  image compressed to not more than a certain width  and height? What is the behavior of the HXPhotoPicker if the media has not reached even the minimum size?

**Comment by SilenceLove** [comment]
Cannot be compressed to the specified size, but you can set the quality of the compressed image or video through the `compression: PhotoAsset.Compression` parameter
``` 
let imageCompressionQuality: CGFloat?
```
`VideoExportParameter`
```
/// Video export resolution
public let preset: ExportPreset
/// video quality [1 - 10]
public let quality: Int
```

**Comment by Xenolion** [comment]
Do the  compressed video and  image cached? How long are they kept?

**Comment by SilenceLove** [comment]
The default tmp directory, you can do the persistence yourself

**Comment by Xenolion** [comment]
Okay nice thank you, let me continue to explore the  Library.
