### ISSUE TITLE
弹出的相册照片，有时时间正序，有时时间倒序。

### ISSUE THREAD

**Issue by zt-zhang** [SilenceLove/HXPhotoPicker#558]

**Comment by SilenceLove** [comment]
具体是什么样的

**Comment by zt-zhang** [comment]
https://github.com/SilenceLove/HXPhotoPicker/assets/65379275/ba8c114b-56fc-43e7-a9d4-43db01ad9f5b

当照片比较多的时比较好复现。
使用的是 master 的HXPhotoPickerExample Targets
