### ISSUE TITLE
4.0.3 how to call camera directly?

### ISSUE THREAD

**Issue by iPermanent** [SilenceLove/HXPhotoPicker#559]
I use 4.0.3 and in the PickerConfiguration.swift I didn't find any config value to let me jump into camera directly, some times  our app need to take camera and then edit it, so I wonder how can I call it directly

**Comment by SilenceLove** [comment]
1：
```
let config = CameraConfiguration()
let camerController = CameraController(config: config, type: .all, delegate: self)
present(camerController, animated: true, completion: nil)

func cameraController(
    _ cameraController: CameraController,
    didFinishWithResult result: CameraController.Result,
    location: CLLocation?
) {
    switch result {
    case .image(let image):
        print(image)
    case .video(let url):
        print(url)
    }
}
```
2：
```
let config = CameraConfiguration()
Photo.capture(config, type: .all) { result, location in
    switch result {
    case .image(let image):
        print(image)
    case .video(let url):
        print(url)
    }
}
```
3：
```
let config = CameraConfiguration()
let result = CameraController.capture(config: config) { result, location in
    switch result {
    case .image(let image):
        print(image)
    case .video(let url):
        print(url)
    }
}
```

**Comment by iPermanent** [comment]
> 1：
> 
> ```
> let config = CameraConfiguration()
> let camerController = CameraController(config: config, type: .all, delegate: self)
> present(camerController, animated: true, completion: nil)
> 
> func cameraController(
>     _ cameraController: CameraController,
>     didFinishWithResult result: CameraController.Result,
>     location: CLLocation?
> ) {
>     switch result {
>     case .image(let image):
>         print(image)
>     case .video(let url):
>         print(url)
>     }
> }
> ```
> 
> 2：
> 
> ```
> let config = CameraConfiguration()
> Photo.capture(config, type: .all) { result, location in
>     switch result {
>     case .image(let image):
>         print(image)
>     case .video(let url):
>         print(url)
>     }
> }
> ```
> 
> 3：
> 
> ```
> let config = CameraConfiguration()
> let result = CameraController.capture(config: config) { result, location in
>     switch result {
>     case .image(let image):
>         print(image)
>     case .video(let url):
>         print(url)
>     }
> }
> ```

Thanks, I  will try it now.
