### ISSUE TITLE
转场动画的问题

### ISSUE THREAD

**Issue by lzglrxy** [SilenceLove/HXPhotoPicker#561]
在任意一个相册打开一张大图预览后，使用拖拽手势返回上一页，然后“快速”点击打开任意一张图片，这一瞬间没有响应。或者打开任意一张大图，然后“快速”使用拖拽手势返回，拖拽手势在这一瞬间也没有响应。对比系统相册则不存在这样的问题，体验流畅度有个微小的差异

**Comment by SilenceLove** [comment]
优化了一下
