### ISSUE TITLE
Xcode 14.3 编译 HXPhotoPicker compile swift source files 步骤用了800秒

### ISSUE THREAD

**Issue by bikeboy7** [SilenceLove/HXPhotoPicker#564]

**Comment by BinBear** [comment]
遇到同样问题

**Comment by bikeboy7** [comment]
我后来在podfile下面加上这个解决了

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['HXPhotoPicker'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
      end
    end
  end
end
@Lovezysong @BinBear

**Comment by SilenceLove** [comment]
这两天会发个版本解决



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Hi ***@***.***&gt;
发送时间: 2023年9月7日 18:22
收件人: SilenceLove/HXPhotoPicker ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [SilenceLove/HXPhotoPicker] Xcode 14.3 编译 HXPhotoPicker compile swift source files 步骤用了800秒 (Issue #564)





 
我后来在podfile下面加上这个解决了
 
post_install do |installer|
 installer.pods_project.targets.each do |target|
 if ['HXPhotoPicker'].include? target.name
 target.build_configurations.each do |config|
 config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
 end
 end
 end
 end
 @Lovezysong @BinBear

**Comment by SilenceLove** [comment]
`v4.0.6` 已解决
