### ISSUE TITLE
功能需求:HXPhotoView多选情况下,使用单选功能

### ISSUE THREAD

**Issue by 19aneng** [SilenceLove/HXPhotoPicker#569]
HXPhotoView设置最多图片选择数是5,每次选一张图片就编辑一下为正方形,最大数是五张,也就点五下...
现在是每次点击都会替换成第一张

![image](https://github.com/SilenceLove/HXPhotoPicker/assets/22389902/71fb924e-85ce-492a-ade2-d734a3525a7e)

**Comment by SilenceLove** [comment]
OC版本不再增加功能
