### ISSUE TITLE
功能需求：NetworkImageAsset 增加自定义的缓存key

### ISSUE THREAD

**Issue by MZC0829** [SilenceLove/HXPhotoPicker#570]
首先感谢大佬的轮子！

需求背景：图片是存储到阿里云OSS，图片资源的访问权限为私有（私有URL不会变），需要签名转换成公用的URL，图片才可以访问，每次转换后的url都不一样的。

1、现在使用库里的PhotoBrowser来查看大图
2、PhotoAsset(NetworkImageAsset(thumbnailURL: originalURL, originalURL: originalURL))
3、由于每次转换后的url都不一样，因此在查看大图是，kf每次都得重新去网络上加载图片，导致查看图片慢，导致缓存不断增加
4、因此建议在初始化NetworkImageAssets时增加自定义的缓存key（该图片的私有URL）
      类似：
      let resource = ImageResource(downloadURL: realUrl, cacheKey: privateUrl)
      imageView.kf.setImage(with: resource, placeholder: placeholder)

或者大佬们有其他的解决方案，还望不吝赐教，万分感谢！

**Comment by SilenceLove** [comment]
```
/// 重写 downloadImage 方法修改url
class Downloader: Kingfisher.ImageDownloader {
    override func downloadImage(
        with url: URL,
        options: KingfisherParsedOptionsInfo,
        completionHandler: ((Result<ImageLoadingResult, KingfisherError>) -> Void)? = nil
    ) -> DownloadTask? {
        // 修改url
        return super.downloadImage(with: url, options: options, completionHandler: completionHandler)
    }
}
```
```
/// 使用新的 ImageDownloader 
PhotoManager.shared.imageDownloader = Downloader(name: "default")
```

**Comment by SilenceLove** [comment]
不知道这样可行不

**Comment by MZC0829** [comment]
感谢大佬回复，试了好像不行。
还有其他思路吗？谢谢

**Comment by SilenceLove** [comment]
后面会加`cacheKey `属性

**Comment by MZC0829** [comment]
感谢大佬，那就静候佳音了

**Comment by SilenceLove** [comment]
已加

**Comment by MZC0829** [comment]
感谢大佬👍
