### ISSUE TITLE
macCatalyst 和· Ambiguous use of 'saveSystemAlbum(type:customAlbumName:creationDate:location:completion:)'报错

### ISSUE THREAD

**Issue by xiaofengin** [SilenceLove/HXPhotoPicker#571]
<img width="1402" alt="截屏2023-08-13 下午2 33 36" src="https://github.com/SilenceLove/HXPhotoPicker/assets/16508721/f700448b-7761-4415-b6bb-aecb11c79ee6">
运行Demo 4.0.5的版本 发现macCatalyst 和· Ambiguous报错，这个报错和xcode版本有关，我的xcode的版本是13.2.1 会出现这个错误
但是 同事装的是新版的xcode，没有报错
主要是我的电脑比较老，xcode只能装到13.2.1 版本，所以也想问一下大佬，后期会不会兼容13.2.1的xcode，如果有计划兼容，那我就在等等，没有计划的话，我在想别的办法

**Comment by Suzhibin** [comment]
xcode 14.1 也报错

**Comment by xiaofengin** [comment]
@Suzhibin 14.3 测试没有问题
