### ISSUE TITLE
代码设计

### ISSUE THREAD

**Issue by SPStore** [SilenceLove/HXPhotoPicker#575]
不得不说作者很用心，拥有非常多的功能，是目前为止见过的功能最全的照片选择器，而且bug很少。

从产品的角度，是个好框架，但是从代码角度，我看了作者写的代码，几乎没有任何设计模式可言，代码非常的混乱，无非就是用了很多扩展，将VC的代码给抽离了，所以导致文件就非常的多。
还有有很多东西都可以单独抽成一个小pods，比如裁剪页面，假如工程中其他地方只需要一个图片裁剪页，其他编辑不要，该SDK是无法被复用的，所有编辑都处在同一个VC里，根本无法剥离开来。再比如自定义的转场动画，强依赖了fromVC和toVC，如果工程中有其他类似的专场，只能复制代码，改一下fromVC和toVC等，这些依赖的外部资源，都可以使用面向协议的方式去跟外部索要。

再比如EditorStickersItemView，这个view也是有可能被复用的，当一个容器view添加了多个EditorStickersItemView的时候，ItemView于ItemView之间的层级关系，是在容器view里面处理的，其实这些逻辑可以直接在itemView里面实现的，就好比页面上有多个UITextField，我们点击任意一个UITextField，其他UITextField就会自动退出第一响应者，这些我们不需要做吧，这个itemView上也是如此，使用者应当只需关心itemView的添加、交互和回调。

**Comment by SilenceLove** [comment]
写的时候主要以功能为主，开始目的也是外部只用简单的调用就能获取到最后的结果，没想过外部要很灵活定制。主要也是没有太多精力

**Comment by SPStore** [comment]
理解理解，IT届就应该有更多像你一样有匠心精神的人，能写出这么多东西已经非常的nice了，应该花了很长时间去写，去测。我看了不少人写的，想自己参考着写一个，但是看代码实在是看的有点痛苦，所以就肤浅的吐槽了一下。你这个框架目前在全网应该是最全的，另外有一个ZLPhotoBrowser，目前4.5k个start，它那个功能简单些，是按照微信的样式去设计的，你这个增长速度比它要快，不久应该能超越。

**Comment by SilenceLove** [comment]
超不超过都无所谓，主要还是使用起来方便，功能全，效果好，问题少
