### ISSUE TITLE
demo  中 Swift 示例 选择 Editor  编辑类型改为 video  点击导航栏的 打开编辑器 crash 

### ISSUE THREAD

**Issue by cray1211** [SilenceLove/HXPhotoPicker#580]
'NSInternalInconsistencyException', reason: 'negative sizes are not supported in the flow layout'

**Comment by cray1211** [comment]
我在项目中使用也遇到同样的问题

<img width="534" alt="截屏2023-10-08 22 00 02" src="https://github.com/SilenceLove/HXPhotoPicker/assets/31604470/130a594b-3325-47e4-919f-f150c98f6e90">

**Comment by SilenceLove** [comment]
demo无法重现

**Comment by cray1211** [comment]
设备 iPhone 7   系统 iOS 14.0  
崩溃原因  collectionView  itemSize 计算为负值导致crash

**Comment by SilenceLove** [comment]
具体崩溃的代码可以截图看看吗
