### ISSUE TITLE
HXPhotoPicker/Lite 4.0.7 有崩溃

### ISSUE THREAD

**Issue by bberljw** [SilenceLove/HXPhotoPicker#582]
1.0x100e5d000 PhotoPickerViewController.updateTitle() + 524
2.0x100e5ce68 PhotoPickerViewController.updateTitle() (<compiler-generated>:0)
3.0x100e57d48 PhotoPickerViewController.changedAssetCollection(collection:) (PhotoPickerViewController.swift:700)
4.0x100bc7a64 closure #1 in AlbumViewController.fetchCameraAssetCollection() (<compiler-generated>:0)
5.0x100e239e8 closure #1 in PhotoPickerController.fetchCameraAssetCollection() (<compiler-generated>:0)
6.0x100ef4a78 _$s13HXPhotoPicker12PhotoManagerC26fetchCameraAssetCollection3for7options10completionyAA0bG7OptionsV_So07PHFetchL0CyAA0cgH0CctFyycfU_yyScMYccfU_TA (<compiler-generated>:0)
7.0x10008aa8c thunk for @escaping @callee_guaranteed () -> () (<compiler-generated>:0)

**Comment by NineCity** [comment]
我也遇到了，线上用户的崩溃，但我不知道怎么复现，你知道怎么复现出来吗？

**Comment by bberljw** [comment]
> 我也遇到了，线上用户的崩溃，但我不知道怎么复现，你知道怎么复现出来吗？

是的，线上用户的崩溃。我暂时没找到复现的路径

**Comment by bberljw** [comment]
点错了，怎么reopen？

**Comment by bberljw** [comment]
> 我也遇到了，线上用户的崩溃，但我不知道怎么复现，你知道怎么复现出来吗？

是的，线上用户的崩溃。暂时还没找到复现的路径

**Comment by SilenceLove** [comment]
最新版应该不会了

**Comment by bberljw** [comment]
好的，我更新下版本试试。
