### ISSUE TITLE
需要要系统iOS12以上才可以吗？可以知道什么原因吗？

### ISSUE THREAD

**Issue by KhayraHongtao** [SilenceLove/HXPhotoPicker#583]
let imageResource: Resource
        #if HXPICKER_ENABLE_PICKER_LITE
        imageResource = ImageResource(downloadURL: url, cacheKey: cacheKey)
        #else
        imageResource = KF.ImageResource(downloadURL: url, cacheKey: cacheKey)
        #endif

是不是 图片库，KF.ImageResource(downloadURL: url, cacheKey: cacheKey) 这个方法需要12以上

如果
let imageResource: Resource
        #if HXPICKER_ENABLE_PICKER_LITE
        imageResource = ImageResource(downloadURL: url, cacheKey: cacheKey)
        #else
        imageResource = ImageResource(downloadURL: url, cacheKey: cacheKey)
        #endif
上下的方面一样会有什么影响吗？

**Comment by SilenceLove** [comment]
不报错就接影响

**Comment by KhayraHongtao** [comment]
> 不报错就没影响

#587 低版本点击没响应  真机 11 ， 12 的系统
