### ISSUE TITLE
PhotoToolBarView: UIToolbar, PhotoToolBar，预览，编辑  ，完成按钮在真机12系统没响应

### ISSUE THREAD

**Issue by KhayraHongtao** [SilenceLove/HXPhotoPicker#587]
![image](https://github.com/SilenceLove/HXPhotoPicker/assets/14037413/9a653945-fc52-4c20-885b-dbf6c6354e1c)
预览的点击，
编辑的点击，
完成的点击，
没效果

**Comment by KhayraHongtao** [comment]
点击事件都没触发，打断点，没走

**Comment by KhayraHongtao** [comment]
高版本是可以响应的我试过ios 13 以上的系统

**Comment by SilenceLove** [comment]
`public required init(_ config: PickerConfiguration, type: PhotoToolBarType)`在这个方法最后一步加上`layoutIfNeeded()`试试看

**Comment by KhayraHongtao** [comment]
> `public required init(_ config: PickerConfiguration, type: PhotoToolBarType)`在这个方法最后一步加上`layoutIfNeeded()`试试看

![image](https://github.com/SilenceLove/HXPhotoPicker/assets/14037413/1dfec92b-2377-4d37-80eb-0907be7cdf29)

Xcode 高版本编译的话，要加上  self.previewAssets[$0]   ；  self.  不然就会报错

**Comment by KhayraHongtao** [comment]
> `public required init(_ config: PickerConfiguration, type: PhotoToolBarType)`在这个方法最后一步加上`layoutIfNeeded()`试试看

推送上去了，我看下

**Comment by KhayraHongtao** [comment]
> `public required init(_ config: PickerConfiguration, type: PhotoToolBarType)`在这个方法最后一步加上`layoutIfNeeded()`试试看

![image](https://github.com/SilenceLove/HXPhotoPicker/assets/14037413/d79c33b1-bb2e-4495-aec6-cadb0970f233)
这个方法在配置里面加上 layoutIfNeeded  ？

**Comment by SilenceLove** [comment]
> > `public required init(_ config: PickerConfiguration, type: PhotoToolBarType)`在这个方法最后一步加上`layoutIfNeeded()`试试看
> 
> ![image](https://user-images.githubusercontent.com/14037413/276479289-d79c33b1-bb2e-4495-aec6-cadb0970f233.png) 这个方法在配置里面加上 layoutIfNeeded ？

是的，UIToolbar 的问题

**Comment by KhayraHongtao** [comment]
> `public required init(_ config: PickerConfiguration, type: PhotoToolBarType)`在这个方法最后一步加上`layoutIfNeeded()`试试看
![企业微信截图_328dfe40-df93-418b-834c-590e3d60ad32](https://github.com/SilenceLove/HXPhotoPicker/assets/14037413/642e3941-63ee-414a-93f7-5721f9f34811)


这样是吧？

**Comment by SilenceLove** [comment]
> > `public required init(_ config: PickerConfiguration, type: PhotoToolBarType)`在这个方法最后一步加上`layoutIfNeeded()`试试看
> > ![企业微信截图_328dfe40-df93-418b-834c-590e3d60ad32](https://github.com/SilenceLove/HXPhotoPicker/assets/14037413/642e3941-63ee-414a-93f7-5721f9f34811)
> 
> 这样是吧？

是的，解决了没

**Comment by KhayraHongtao** [comment]
> > > `public required init(_ config: PickerConfiguration, type: PhotoToolBarType)`在这个方法最后一步加上`layoutIfNeeded()`试试看
> > > ![企业微信截图_328dfe40-df93-418b-834c-590e3d60ad32](https://github.com/SilenceLove/HXPhotoPicker/assets/14037413/642e3941-63ee-414a-93f7-5721f9f34811)
> > 
> > 
> > 这样是吧？
> 
> 是的，解决了没

我 准备试试，   还有一个问题就是   13以下系统  点击相册里面的相机就闪退，

**Comment by KhayraHongtao** [comment]
> > > `public required init(_ config: PickerConfiguration, type: PhotoToolBarType)`在这个方法最后一步加上`layoutIfNeeded()`试试看
> > > ![企业微信截图_328dfe40-df93-418b-834c-590e3d60ad32](https://github.com/SilenceLove/HXPhotoPicker/assets/14037413/642e3941-63ee-414a-93f7-5721f9f34811)
> > 
> > 
> > 这样是吧？
> 
> 是的，解决了没

https://github.com/SilenceLove/HXPhotoPicker/assets/14037413/64e87f8d-baeb-4010-984c-53c9c0ad55e5

加了，
![image](https://github.com/SilenceLove/HXPhotoPicker/assets/14037413/844d48c4-4709-4f1d-9520-ddce7515fcf7)
没有得到 解决~

**Comment by SilenceLove** [comment]
layoutIfNeeded 换成 layoutSubviews
