### ISSUE TITLE
相册授权，确认选择几张可见相片之后闪退，PhotoToolBarView 报错 promptView = nil

### ISSUE THREAD

**Issue by bikeboy7** [SilenceLove/HXPhotoPicker#589]
步骤：
1、显示系统的相册授权弹窗，选择选项 “选中的照片”
2、选中几张照片，点击确认
3、闪退，断点定位到PhotoToolBarView的layoutsubviews的promptView。Thread 1: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value

设备：iPhoneX iOS 16.7.1

HXPhotoPicker: 4.0.8
<img width="1062" alt="截屏2023-10-27 15 26 41" src="https://github.com/SilenceLove/HXPhotoPicker/assets/18651563/b35655d9-219e-45cd-90b9-addf797c4f65">

**Comment by SilenceLove** [comment]
用最新版看看

**Comment by CJkyle** [comment]
我也是这个问题，使用版本是4.1.0
