### ISSUE TITLE
发现了一个重复打开 crash的问题

### ISSUE THREAD

**Issue by xuxueyong** [SilenceLove/HXPhotoPicker#591]
<img width="1728" alt="截屏2023-11-02 12 03 24" src="https://github.com/SilenceLove/HXPhotoPicker/assets/17976714/d338612b-5a35-46a9-be2b-9458d0ca05d6">

**Comment by xuxueyong** [comment]
我用单例去打开这个相册选择器， 在当前 controller 上面， 第一次show出， 不会crash , 关闭之后， 第二次show 出， 就会 crash

**Comment by iPermanent** [comment]
4.1.1和4.1.3 有同样的问题

**Comment by iPermanent** [comment]
<img width="1632" alt="image" src="https://github.com/SilenceLove/HXPhotoPicker/assets/1712759/63a90255-a608-4dca-83fd-e791a5324db0">
加上了一句解决了
