### ISSUE TITLE
'PKStroke' has no member 'randomSeed'

### ISSUE THREAD

**Issue by izsm** [SilenceLove/HXPhotoPicker#594]
xcode14.1报错 Value of type 'PKStroke' has no member 'randomSeed'

![WechatIMG2693](https://github.com/SilenceLove/HXPhotoPicker/assets/20026815/7d10a88d-d6ca-4ce5-814a-f48a97427d96)

**Comment by SilenceLove** [comment]
升级一下xcode吧...
