### ISSUE TITLE
PickerConfiguration使用redBook 崩溃

### ISSUE THREAD

**Issue by xiaomage1478** [SilenceLove/HXPhotoPicker#596]
![image](https://github.com/SilenceLove/HXPhotoPicker/assets/25787973/c72285a9-2f1a-4717-8148-bb22ff658989)

**Comment by BlackCatHehe** [comment]
一样

**Comment by BlackCatHehe** [comment]
@xiaomage1478 有解决吗

**Comment by xiaomage1478** [comment]
> @xiaomage1478 有解决吗

没有，还是在default的基础上修改了

**Comment by BlackCatHehe** [comment]
是一个很奇怪的问题 访问不到库里面的PhotoTools 
![CleanShot 2023-11-22 at 18 03 52@2x](https://github.com/SilenceLove/HXPhotoPicker/assets/39700053/d4efb253-acf4-43b7-af81-37964c05c30e)
@SilenceLove 这个可以辛苦看看是什么问题造成的吗

**Comment by SilenceLove** [comment]
Demo 里是正常的吧 @BlackCatHehe

**Comment by BlackCatHehe** [comment]
> Demo 里是正常的吧 @BlackCatHehe

demo是正常的， 但是demo里面是引入了整个库，我这里是只pod了lite，不知道跟这个有关系没有

**Comment by SilenceLove** [comment]
@BlackCatHehe  我重新创建了一个项目试了一下是没问题的

**Comment by SilenceLove** [comment]
如果外部使用了 `async`需要添加`@MainActor`
