### ISSUE TITLE
先用苹果自带相机录个长视频，然后用我们这个框架选择视频，选择时候的视频变成了横屏的 

### ISSUE THREAD

**Issue by ggguyo** [SilenceLove/HXPhotoPicker#598]
先用苹果自带相机录个长视频，然后用我们这个框架选择视频，选择时候的视频变成了横屏的

**Comment by SilenceLove** [comment]
视频发一下看看

**Comment by ggguyo** [comment]
可能没有表达清楚，其实就是选择一个长视频，然后进行裁剪，裁剪之后的视频变成了横了过来
https://github.com/SilenceLove/HXPhotoPicker/assets/77562197/e7025542-68ed-4efb-a90f-0c763bce50c8

**Comment by ggguyo** [comment]
我是在这个代理方法里面获取的视频，并通过 getURLs 获取url 然后就是上面视频那个横屏的结果了

<img width="1014" alt="NdYdTUZ6bXIZCuQlHyX-ZyYW" src="https://github.com/SilenceLove/HXPhotoPicker/assets/77562197/59feb76f-6439-42c6-a9f4-7bc856cf0747">

**Comment by SilenceLove** [comment]
视频可以发一份吗

**Comment by SilenceLove** [comment]
处理的那个原视频

**Comment by Rockkung** [comment]
請問這問題怎麼解決？我也遇到了

狀況錄像
https://github.com/SilenceLove/HXPhotoPicker/assets/114649407/eed8d0f6-eee4-405c-8bd1-7699cdd58882

原视频
https://github.com/SilenceLove/HXPhotoPicker/assets/114649407/01993b7c-d8ad-4107-a2b6-94f865366fbd
