### ISSUE TITLE
拍照时摄像头的黑色的问题

### ISSUE THREAD

**Issue by iPermanent** [SilenceLove/HXPhotoPicker#599]
![image](https://github.com/SilenceLove/HXPhotoPicker/assets/1712759/683c8464-0546-4dc8-a30d-d29b9aa8950a)
![image](https://github.com/SilenceLove/HXPhotoPicker/assets/1712759/cd19559b-805f-4d10-ab63-e5cef21e1a3e)
由于是客户的手机无法拿到验证，只能通过现象说明，第一张是实际显示，第二张图是相关的配置，已经打开了相机的完全访问权限的情况下还是黑屏
硬件 iPhone 11  iOS:17.0.3

**Comment by iPermanent** [comment]
补充信息   HXPhotoPicker 4.0.6.1

**Comment by SilenceLove** [comment]
`v4.1.3`版本修改为`AVCaptureVideoPreviewLayer`显示了
