### ISSUE TITLE
4.1.0使用相机拍照后，在添加照片时出错

### ISSUE THREAD

**Issue by yfh349958021** [SilenceLove/HXPhotoPicker#600]
系统环境：macOS:13.6 (22G120)
Xcode版本：15.0.1 (15A507)
swift版本：swiftlang-5.9.0
运行版本：iOS14.5+
崩溃机型：iPhone，iPad均有，具体的就不报了
HXPhotoPicker版本：HXPhotoPicker/NoLocation ->4.1.0
infoplist中所有权限已添加(照片读写，相机麦克风)
报错截图：
<img width="786" alt="image" src="https://github.com/SilenceLove/HXPhotoPicker/assets/19186834/bbd72507-9f28-4d1f-8f38-3cf0e94fd29e">

使用方法：README中快速上手中的方法一，方法二，方法三均使用过，均在拍摄照片点击完成按钮后崩溃
使用截图：
<img width="739" alt="image" src="https://github.com/SilenceLove/HXPhotoPicker/assets/19186834/bcdc1d22-0e9a-4061-a242-66c92471f6d1">

**Comment by yfh349958021** [comment]
<img width="1615" alt="image" src="https://github.com/SilenceLove/HXPhotoPicker/assets/19186834/e520f96f-6932-461b-9d95-8505214178d8">
再补充一下报错时候的截图

**Comment by yfh349958021** [comment]
<img width="1620" alt="image" src="https://github.com/SilenceLove/HXPhotoPicker/assets/19186834/5edd1c87-0221-4b5a-8a97-1b488f06fc3e">
再补充一下，xcode本身的警告

**Comment by SilenceLove** [comment]
最新版已解决
