### ISSUE TITLE
老项目中用到的HXDatePhotoToolManager文件没有了

### ISSUE THREAD

**Issue by computernot** [SilenceLove/HXPhotoPicker#602]
如题，升级之后，HXDatePhotoToolManager没有了，下面这个方法应该替换成什么？

        [self.toolManager writeSelectModelListToTempPathWithList:self.selectList requestType:HXDatePhotoToolManagerRequestTypeHD success:^(NSArray<NSURL *> *allURL, NSArray<NSURL *> *photoURL, NSArray<NSURL *> *videoURL) {

**Comment by SilenceLove** [comment]
最新版看demo里面的
