### ISSUE TITLE
Lite 4.1.1.1 崩溃

### ISSUE THREAD

**Issue by BlackCatHehe** [SilenceLove/HXPhotoPicker#603]
![CleanShot 2023-12-04 at 10 58 57@2x](https://github.com/SilenceLove/HXPhotoPicker/assets/39700053/4136b80d-4831-41e6-9ddb-e34084fd395f)
这里崩溃了，但是提现不了

**Comment by BlackCatHehe** [comment]
@SilenceLove 请问下4.1.2解决的问题跟我提的这个是同一个原因吗

**Comment by SilenceLove** [comment]
有修改
