### ISSUE TITLE
拍摄视频video Orientation问题

### ISSUE THREAD

**Issue by anddygon** [SilenceLove/HXPhotoPicker#605]
使用自定义拍摄页的时候，拍摄横屏视频，拍摄完成，回调的 output url 的视频依然是竖屏的，请问如何解决

![image](https://github.com/SilenceLove/HXPhotoPicker/assets/7263780/958997f9-f1d3-4778-8789-89023e550624)

现在拍摄时，拍摄完的视频都是左图的显示，导致上传到server后，在拉下来播放无法使用右图的样子去播放
尝试添加下面的修改也没用，很奇怪图片横屏拍摄之后，展示没问题
![image](https://github.com/SilenceLove/HXPhotoPicker/assets/7263780/c16b7d68-8950-43f5-b1a5-37f36fe142a7)

**Comment by anddygon** [comment]
大佬帮忙看看嘛

**Comment by SilenceLove** [comment]
下个版本解决

**Comment by SilenceLove** [comment]
`v4.1.3`已解决
