### ISSUE TITLE
UI 布局适配问题

### ISSUE THREAD

**Issue by xsmvp** [SilenceLove/HXPhotoPicker#606]
作者大佬你好，我在使用 swiftui 跳转到咱这个框架的时候发现，相册选择视图顶在导航栏下面去了，具体如图

![1021702400963_ pic](https://github.com/SilenceLove/HXPhotoPicker/assets/23623029/29e2b0f1-f4df-4ef5-b005-7bb736ec17b9)

定位到文件是这个
AlbumViewController
尝试修改无果，想让作者帮忙看看是框架的问题还是其他问题

系统：iOS 17
<img width="596" alt="image" src="https://github.com/SilenceLove/HXPhotoPicker/assets/23623029/512d962c-17ad-4d46-89a7-5a816d21c1d4">
SwiftUI 跳转代码

**Comment by SilenceLove** [comment]
`config.modalPresentationStyle = .fullScreen` 加上这个
