### ISSUE TITLE
swiftui使用spm导入后 无法正常使用，文件找不到

### ISSUE THREAD

**Issue by wanwu96** [SilenceLove/HXPhotoPicker#607]
<img width="700" alt="image" src="https://github.com/SilenceLove/HXPhotoPicker/assets/41659621/6b5bf248-4bd5-4b20-9f64-7d781e890835">

**Comment by wanwu96** [comment]
<img width="700" alt="image" src="https://github.com/SilenceLove/HXPhotoPicker/assets/41659621/788228e1-62d4-4aeb-8f2e-165f93165695">

**Comment by wanwu96** [comment]
<img width="700" alt="image" src="https://github.com/SilenceLove/HXPhotoPicker/assets/41659621/11c6ccab-38aa-4425-b7aa-7f6651e87738">

**Comment by SilenceLove** [comment]
`Asset` 是需要你自己创建的类，看看SwiftUI的Demo
