### ISSUE TITLE
 版本4.1.3  崩溃问题

### ISSUE THREAD

**Issue by NineCity** [SilenceLove/HXPhotoPicker#613]
大致操作是第一次安装后，选择照片权限时候点的选择部分照片，后面不知道怎么点的就崩溃了，不好复现

![image](https://github.com/SilenceLove/HXPhotoPicker/assets/19357504/428adb1e-d457-4f5d-b92a-caf6a0ee68a9)

**Comment by SilenceLove** [comment]
应该没问题了
