### ISSUE TITLE
发现一个问题, 选择资源后, fileSize计算有问题

### ISSUE THREAD

**Issue by hubin97** [SilenceLove/HXPhotoPicker#615]
1. 切换选择原图, PhotoAsset下的fileSize 应该都是计算原图的
2. 我这边计算总大小发现比作者的小10倍才匹配
```
  func updateLayout(_ assetMetas: [PhotoAsset]) {
        let totalFileSize = assetMetas.reduce(0) { partialResult, aMeta in
            return partialResult + aMeta.fileSize
        }/1000_100
        
```

**Comment by SilenceLove** [comment]
你怎么算的

**Comment by hubin97** [comment]
就是后面那段代码,  选完资源回调, 使用 PhotoAsset的 fileSize求和算的,  我看到你库里面有写1000_1000 = 1MB的, 而我使用 求和的值/1000_100  才和 选图时勾选原图后边那个计算总大小相近;  不知道是不是哪里出了问题
```
  func updateLayout(_ assetMetas: [PhotoAsset]) {
        let totalFileSize = assetMetas.reduce(0) { partialResult, aMeta in
            return partialResult + aMeta.fileSize
        }/1000_100
}
```

**Comment by SilenceLove** [comment]
你看你计算方式有没有问题吧

**Comment by hubin97** [comment]
计算应该没有问题, 就是拿的fileSize求和;
确认下, fileSize 在勾选或者不勾选原图时, 它的返回数值没有变?

**Comment by hubin97** [comment]
> 计算应该没有问题, 就是拿的fileSize求和; 确认下, fileSize 在勾选或者不勾选原图时, 它的返回数值没有变?

**Comment by SilenceLove** [comment]
没有

**Comment by hubin97** [comment]
![code](https://pic.ziyuan.wang/user/guest/2024/01/code_08a75e44942d5.jpg)
![snapt](https://pic.ziyuan.wang/user/guest/2024/01/IMG_2356_597e4fdb16862.jpg)

看着好像差了10倍

**Comment by SilenceLove** [comment]
不都是90吗

**Comment by hubin97** [comment]
> 不都是90吗

因为我除的不是  1000_1000 呀

**Comment by SilenceLove** [comment]
返回的是字节 肯定要除啊
/1000 = 1Kb
/1000000 = 1Mb

**Comment by hubin97** [comment]
> 返回的是字节 肯定要除啊 /1000 = 1Kb /1000000 = 1Mb

所以如果除1000000, 结果就差了10倍了

**Comment by SilenceLove** [comment]
你除的不就是 1000000， 1000_100=1000000



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Hubin_Huang ***@***.***&gt;
发送时间: 2024年1月4日 12:03
收件人: SilenceLove/HXPhotoPicker ***@***.***&gt;
抄送: Silence ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [SilenceLove/HXPhotoPicker] 发现一个问题, 选择资源后, fileSize计算有问题 (Issue #615)





  
返回的是字节 肯定要除啊 /1000 = 1Kb /1000000 = 1Mb
  
所以如果除1000000, 结果就差了10倍了

**Comment by hubin97** [comment]
1
