### ISSUE TITLE
iOS16.1.1，真机调试启动应用必现崩溃

### ISSUE THREAD

**Issue by YFCasually** [SilenceLove/HXPhotoPicker#616]
SDK版本4.1.3
崩溃日志如下
dyld[620]: Symbol not found: _$s9PencilKit8PKStrokeV10randomSeeds6UInt32Vvg
  Referenced from: <xxxxxxx> /private/var/containers/Bundle/Application/xxxxx/xxxxx.app/Frameworks/HXPhotoPicker.framework/HXPhotoPicker
  Expected in:     <xxxxx> /System/Library/Frameworks/PencilKit.framework/PencilKit

**Comment by SilenceLove** [comment]
xcode 升级一下吧

**Comment by YFCasually** [comment]
xcode版本15.1

**Comment by SilenceLove** [comment]
估计是系统的bug，`PKStroke`的`randomSeed`是`iOS 16.0`以上可以用。我加一个判断吧 `16.1.1`不用这个

**Comment by BinBear** [comment]
Xcode26.2 打包，这个问题还是出现，单纯判断系统不行
