### ISSUE TITLE
SwiftUI: Cannot find 'PickerConfigurationViewController' in scope

### ISSUE THREAD

**Issue by xkitty17** [SilenceLove/HXPhotoPicker#617]
Xcode Version 15.1 (15C65)
Pod安装
func makeUIViewController(context: Context) -> UINavigationController {
        let vc = **PickerConfigurationViewController**(style: **.insetGrouped**)
        vc.showOpenPickerButton = false
        vc.config = config
        vc.didDoneHandler = { config, _ in
            self.config = config
        }
        return UINavigationController.init(rootViewController: vc)
    }
这个找不到

**Comment by SilenceLove** [comment]
这是demo里面的例子
