### ISSUE TITLE
裁剪压缩问题

### ISSUE THREAD

**Issue by Hanyanrui815** [SilenceLove/HXPhotoPicker#622]
<img width="899" alt="截屏2024-01-18 15 04 11" src="https://github.com/SilenceLove/HXPhotoPicker/assets/70624334/13e12d4c-6d18-454b-9a44-266063a721a0">
为什么要压缩0.3， 这样会导致图片模糊

**Comment by SilenceLove** [comment]
这是封面图片，原始图片使用`url`
