### ISSUE TITLE
SwiftUI：selectMode为single时无法收到selectedAssetArray的更新

### ISSUE THREAD

**Issue by imsai-sh** [SilenceLove/HXPhotoPicker#629]
在真机上运行了此项目的SwiftUI示例，出现单选模式的问题。
运行示例后只修改截图中三个配置：
![WX20240226-091741](https://github.com/SilenceLove/HXPhotoPicker/assets/14907300/793cba99-4434-473b-ac34-8e0f935b1755)

设备：iPhone14pm
系统：ios17.3.1
xcode: 15.2 (15C500b)

**Comment by SilenceLove** [comment]
SwiftUI示例只适用于多选，`selectedAssetArray`主要是为了下次选择的时候选中上次选择的数据
单选的话就没必要了，直接用结果就行了
