### ISSUE TITLE
编辑视频的时候，如果视频暂停切换滤镜会有闪现的效果

### ISSUE THREAD

**Issue by LUJYM** [SilenceLove/HXPhotoPicker#633]
编辑视频的时候切换滤镜会有闪现的效果
`func adjustmentVideoFilter() {
        if !editorView.isVideoPlaying {
            guard let currentTime = isStartFilterParameterTime else {
                return
            }
            editorView.seekVideo(
                to: .init(seconds: currentTime.seconds + 0.1, preferredTimescale: 1000)
            ) { [weak self] in
                if $0 {
                    self?.editorView.seekVideo(to: currentTime)
                }
            }
        }
    }`
看起来是这里的seek导致的

**Comment by SilenceLove** [comment]
视频暂停的时候滤镜效果不会更新
优化了一点，但是不能完全避免这个问题
