### ISSUE TITLE
getImageData问题

### ISSUE THREAD

**Issue by liumengdi666** [SilenceLove/HXPhotoPicker#635]
Api里没有可以拿imageData的, getImage接口拿不到gif的图片,我需要拿imageData.
而requestImageData这个api返回的对象没有public
![image](https://github.com/SilenceLove/HXPhotoPicker/assets/12481783/f109072e-5d2b-430d-9a04-762885b7bc9a)

**Comment by SilenceLove** [comment]
获取url 一样
