### ISSUE TITLE
是否有方法可以限制某些大小的图片不给选择

### ISSUE THREAD

**Issue by JerryFans** [SilenceLove/HXPhotoPicker#642]
如题，比如设置小于300x300图片不能选择，点了就toast提示之类的。

**Comment by SilenceLove** [comment]
下个版本加上

**Comment by SilenceLove** [comment]
https://github.com/SilenceLove/HXPhotoPicker/blob/6d066bf0f5df26fd2c99c9ebedc32ad9da0fb270/Sources/HXPhotoPicker/Picker/Controller/Photo/PhotoPickerControllerProtocol.swift#L91-L100

**Comment by JerryFans** [comment]
我是要基于一个commit来切版本 才可以有这个方法么 亲， 感谢🙏
