### ISSUE TITLE
多语言问题

### ISSUE THREAD

**Issue by BYC318** [SilenceLove/HXPhotoPicker#646]
<img width="457" alt="image" src="https://github.com/SilenceLove/HXPhotoPicker/assets/43394325/04c6f1c8-6835-406e-89ff-c6a87287ffa1">
这里能统一中文做key吗？

**Comment by SilenceLove** [comment]
这样可以防止重名
你可以通过`config.textManager`修改
https://github.com/SilenceLove/HXPhotoPicker/blob/fa20e6a6e1355cad724ecfa99c20d43ce92c0132/Sources/HXPhotoPicker/Core/Util/TextManager.swift#L62-L88

**Comment by BYC318** [comment]
<img width="641" alt="image" src="https://github.com/SilenceLove/HXPhotoPicker/assets/43394325/4dc1609e-d085-4a05-beb4-5886d6f4d1db">
<img width="561" alt="image" src="https://github.com/SilenceLove/HXPhotoPicker/assets/43394325/548471f8-6c4b-47cc-a880-9ef59b09288f">
这里picker是结构体，没法这么修改文案！

**Comment by BYC318** [comment]
<img width="822" alt="image" src="https://github.com/SilenceLove/HXPhotoPicker/assets/43394325/6cbc1c69-894e-4a1a-b246-e4943b68c2ee">
