### ISSUE TITLE
能否打开指定相册

### ISSUE THREAD

**Issue by liumengdi666** [SilenceLove/HXPhotoPicker#647]
有一个需求,传入指定的相册名称,打开默认选中的是对应的相册浏览,看了下api貌似并没有对应参数,能否支持下?

**Comment by SilenceLove** [comment]
https://github.com/SilenceLove/HXPhotoPicker/blob/6d066bf0f5df26fd2c99c9ebedc32ad9da0fb270/Sources/HXPhotoPicker/Picker/Protocol/Fetch/PhotoFetchAssetCollection.swift#L45-L50
```swift
/// 实现协议里的这个方法
config.fetchAssetCollection = TestPhotoFetchAssetCollection.self

public struct TestPhotoFetchAssetCollection: PhotoFetchAssetCollection {
    public static func fetchCameraAssetCollection(_ config: PickerConfiguration, options: PHFetchOptions) -> PhotoAssetCollection? {
        if !config.allowLoadPhotoLibrary {
            return nil
        }
        if config.creationDate {
            options.sortDescriptors = [
                NSSortDescriptor(
                    key: "creationDate",
                    ascending: config.creationDate
                )
            ]
        }
        var collection: PhotoAssetCollection?
        fetchAssetCollections(options: options) { assetCollection, isCameraRoll, stop in
            if !isCameraRoll {
                collection = assetCollection
                stop.pointee = true
            }
        }
        return collection
    }
}
```

**Comment by liumengdi666** [comment]
你好, 按照上边的方式实现了,当albumShowMode为default时实现的很好, 但是我们采用albumShowMode方式为popup,有点小问题, 比如自定义相册为'xxx',  弹出后点击上边的标题展示albumList会发现显示的是'xxx',但是列表选中的却是'最近项目', 切换几次后'最近项目'又不见被替换为'xxx'了,这时列表里有2个'xxx'相册, 虽然可以修改自定义相册`collection.isSelected = true`稳定这种情况, 但是我们希望弹出相册列表时默认选中的是'xxx',同时'最近项目'也存在,这样可以实现吗?
`public static func fetchCameraAssetCollection(
        _ config: PickerConfiguration,
        options: PHFetchOptions
    ) -> PhotoAssetCollection? {
        if config.creationDate {
            options.sortDescriptors = [
                NSSortDescriptor(
                    key: "creationDate",
                    ascending: config.creationDate
                )
            ]
        }
        var collection: PhotoAssetCollection?
        fetchAssetCollections(options: options) { assetCollection, isCameraRoll, stop in
            if !isCameraRoll, assetCollection.albumName == "xxx" {
                collection = assetCollection
                stop.pointee = true
            }
        }
        if let collection {
//            collection.isSelected = true
            return collection
        }
        return DefaultPhotoFetchAssetCollection.fetchCameraAssetCollection(config, options: options)
    }`
![IMG_0216](https://github.com/SilenceLove/HXPhotoPicker/assets/12481783/f2509718-36c9-4077-8c74-48cbaa92c3cb)

**Comment by liumengdi666** [comment]
我发现可以自定义PhotoFetchData,但是在重写`fetchAssetCollections`时遇到了一些问题,
![image](https://github.com/SilenceLove/HXPhotoPicker/assets/12481783/50e425f1-4bfc-46b9-aa87-811d55874dde)
这两个属性没有public,chogn重写的时候无法使用.
我发现'最近项目'是下边这句代码替换掉的
![image](https://github.com/SilenceLove/HXPhotoPicker/assets/12481783/d4c5cf30-56dd-49cc-a034-084078f5d0c0)
所以我想重写这个方法,不知道重写这个方法是否可行,感觉重写后的select状态依然有些混乱.

**Comment by SilenceLove** [comment]
> 你好, 按照上边的方式实现了, 我们采用albumShowMode方式为popup,有点小问题, 比如自定义相册为'xxx', 弹出后点击上边的标题展示albumList会发现显示的是'xxx',但是列表选中的却是'最近项目', 切换几次后'最近项目'又不见被替换为'xxx'了,这时列表里有2个'xxx'相册, 虽然可以修改自定义相册`collection.isSelected = true`稳定这种情况, 但是我们希望弹出相册列表时默认选中的是'xxx',同时'最近项目'也存在,这样可以实现吗?
> 
> ```
>         _ config: PickerConfiguration,
>         options: PHFetchOptions
>     ) -> PhotoAssetCollection? {
>         if config.creationDate {
>             options.sortDescriptors = [
>                 NSSortDescriptor(
>                     key: "creationDate",
>                     ascending: config.creationDate
>                 )
>             ]
>         }
>         var collection: PhotoAssetCollection?
>         fetchAssetCollections(options: options) { assetCollection, isCameraRoll, stop in
>             if !isCameraRoll, assetCollection.albumName == "xxx" {
>                 collection = assetCollection
>                 stop.pointee = true
>             }
>         }
>         if let collection {
> //            collection.isSelected = true
>             return collection
>         }
>         return DefaultPhotoFetchAssetCollection.fetchCameraAssetCollection(config, options: options)
>     }```
> ![image](https://github.com/SilenceLove/HXPhotoPicker/assets/12481783/5d31afad-848d-4c9b-8fcd-b3db4aa899e4)
> ```

这个问题下个版本会修改，不会替换掉第一个相册

**Comment by liumengdi666** [comment]
试了最新的修改代码后相册已经不会被替换掉了, 然而发现有一个bug:

https://github.com/SilenceLove/HXPhotoPicker/assets/12481783/927e7131-99b0-4a49-bbb0-dc5862c44434
视频中可以看到打开自定义相册后选中状态有些错乱, 我调试了下大概知道原因:
![image](https://github.com/SilenceLove/HXPhotoPicker/assets/12481783/91f817e4-bf50-4118-98fe-67f21cfd9c0d)

`self.cameraAssetCollection`可能还没拿到的时候已经走到这个if判断里, 看起来2个queue执行完毕的先后顺序并不能确定,所以时好时坏.

**Comment by SilenceLove** [comment]
最新的代码试试
