### ISSUE TITLE
浏览图片单击事件自定义

### ISSUE THREAD

**Issue by liumengdi666** [SilenceLove/HXPhotoPicker#649]
找了一下只看到可以自定义长按事件,longPressHandler,有没有api可以自定义单击事件或者禁用它?
<img width="500" alt="WeChatae7ef9a49f323c015017b88610aea5ee" src="https://github.com/SilenceLove/HXPhotoPicker/assets/12481783/abf5855b-ca9b-4db2-a682-7c95026dbe03">

**Comment by SilenceLove** [comment]
https://github.com/SilenceLove/HXPhotoPicker/blob/4634dc654bb71504d3b93fb2c21eed2001efcab8/Sources/HXPhotoPicker/Picker/Controller/Browser/PhotoBrowser.swift#L95C5-L99C52

**Comment by liumengdi666** [comment]
So cool ~

如果外部可以控制下边这段逻辑就更好了:
![image](https://github.com/SilenceLove/HXPhotoPicker/assets/12481783/70ae082b-473f-4c92-80fb-2976c00ab7b7)
实际上因为外部拿不到`didHidden`的状态和gradualShadowImageView私有变量.

**Comment by SilenceLove** [comment]
不拦截点击事件就可以了吧

**Comment by SilenceLove** [comment]
最新代码暴露了

> So cool ~
> 
> 如果外部可以控制下边这段逻辑就更好了: ![image](https://private-user-images.githubusercontent.com/12481783/320749623-70ae082b-473f-4c92-80fb-2976c00ab7b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDg2MzAsIm5iZiI6MTcxMjY0ODMzMCwicGF0aCI6Ii8xMjQ4MTc4My8zMjA3NDk2MjMtNzBhZTA4MmItNDczZi00YzkyLTgwZmItMjk3NmMwMGFiN2I3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDA3Mzg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNWU4N2ViODc2NzA1NWE5MTJhMWRjYTJhYzNhYWRiNGFlMmRlNzk2MTBkNDkxNDJmYjNlNmMxMGJlYzQ3ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.16yJkH97ZFkXnZCEwSKEsYzDah_T74SgjJiHhxV7HVo) 实际上因为外部拿不到`didHidden`的状态和gradualShadowImageView私有变量.
