### ISSUE TITLE
自定义转场在dismiss 的时候图片会先展示原比例再填充到view上

### ISSUE THREAD

**Issue by xiiiiye** [SilenceLove/HXPhotoPicker#656]
多谢大佬提供的开源框架, 我在4.1.3的版本上发现一个自定义转场的问题, 麻烦帮忙看一下是我该如何正确使用这个转场动画

[录屏](https://github.com/SilenceLove/HXPhotoPicker/assets/13848735/22653f51-bfaf-48db-8455-9ab30d3e072d
)

我的代码如下
`let completion = userInfo["completion"] as? (_ index: Int) -> UIView`

> PhotoBrowser.show(models, pageIndex: pageIndex, config: config, transitionalImage: image) { index in
>                 completion?(index)
>             } transitionCompletion: { index in
>                 print(index)
>             }

**Comment by SilenceLove** [comment]
demo 里面有例子
https://github.com/SilenceLove/HXPhotoPicker/blob/820f18489baecf6262d222fd343af7a4ba4b201e/Swift/Classes/Controller/PhotoBrowserViewController.swift#L149C1-L160C10
