### ISSUE TITLE
相机在metal模式下，并且设置postion是front 画面错乱

### ISSUE THREAD

**Issue by Delevel1020** [SilenceLove/HXPhotoPicker#662]
![WechatIMG2895](https://github.com/SilenceLove/HXPhotoPicker/assets/43638348/9d6f0a59-3a02-4ecb-9166-eab59de3df56)

**Comment by Delevel1020** [comment]
这是demo跑起来后的画面
![WechatIMG2942](https://github.com/SilenceLove/HXPhotoPicker/assets/43638348/14308ab9-77c5-4397-b1fc-5e1c1650c0d7)

**Comment by SilenceLove** [comment]
使用普通相机吧
