### ISSUE TITLE
PrivacyInfo.xcprivacy冲突问题

### ISSUE THREAD

**Issue by liumengdi666** [SilenceLove/HXPhotoPicker#667]
[#660 ](https://github.com/SilenceLove/HXPhotoPicker/issues/660)
看了针对这个问题的提交, 这个文件不应该放resources中,如果主工程中也有xcprivacy文件,则会冲突.
`xcprivacy should be in s.resource_bundles`

**Comment by SilenceLove** [comment]
再试试
