### ISSUE TITLE
iOS9.3 iPhoneSE 在跳转到照片选择页面后，点击取消返回后不能交互，过几秒后才能交互（选好照片后点击完成也会出现同样的问题）

### ISSUE THREAD

**Issue by xiayvyan** [SilenceLove/HXPhotoPicker#67]
如Demo2，点击添加照片， present到照片选择页面，点击取消，dismiss原来页面，此时就不能交互了，需要等几秒才能交互。感觉像是主线程卡住了。我在查阅代码后发现，在HXDatePhotoViewController的dealloc方法中调用了[self stopRunning]; -->[self.cameraController stopSession];--> dispatch_async(self.videoQueue, ^{
            [self.captureSession stopRunning];
        });
只要将  [self.captureSession stopRunning]; 从self.videoQueue中移到出来调用问题就解决了。不知道这样是否有何不妥的地方？希望作者能提供更好的解决办法

**Comment by LoveZYForever** [comment]
目前好像只有你反应了这个问题,,你可以在将配置里的cameraCellShowPreview 这个属性设置成NO在列表界面不预览相机

**Comment by LoveZYForever** [comment]
其实我也不知道那里可不可以移出来  🤣🤣🤣

**Comment by imChay** [comment]
同样遇到这个问题，还是声明一下把，避免别人踩坑

**Comment by ETogether** [comment]
您好！iOS9.3.3 iphone6plus 也是出现这种问题！是不是这个是iOS9系统都会这样嘛？ 取消预览相机就可以了
