### ISSUE TITLE
新增 apple 隐私政策文件，pod install 后 source_files 缺少 PrivacyInfo.xcprivacy 文件

### ISSUE THREAD

**Issue by caosuyang** [SilenceLove/HXPhotoPicker#679]
## 简单描述

新增 apple 隐私政策文件，pod install 后源代码缺少 xcprivacy 文件

## 版本号

version： 4.2.0

## 解决办法

修改 podspec 文件中对于 文件的配置处理，如下所示：

    spec.subspec 'Resources' do |resources|
        resources.source_files   = "Sources/HXPhotoPicker/Resources/*.{xcprivacy}"
    end

**Comment by SilenceLove** [comment]
`podspec`没问题，看看是不是你哪个地方有问题
