### ISSUE TITLE
Missing an expected key: 'NSPrivacyCollectedDataTypes'

### ISSUE THREAD

**Issue by lilin87788** [SilenceLove/HXPhotoPicker#685]
Missing an expected key: 'NSPrivacyCollectedDataTypes'
xxxxx.app/HXPhotoPicker_Privacy.bundle/PrivacyInfo.xcprivacy

<img width="1270" alt="image" src="https://github.com/SilenceLove/HXPhotoPicker/assets/1483811/bb9941fc-2169-4c41-8a18-386afabdb016">

**Comment by SilenceLove** [comment]
`pod 'HXPhotoPicker', :git => "https://github.com/SilenceLove/HXPhotoPicker"`
用这个看看

**Comment by lilin87788** [comment]
好的
