### ISSUE TITLE
相册预览网络图拿不到size

### ISSUE THREAD

**Issue by liumengdi666** [SilenceLove/HXPhotoPicker#686]
使用如下代码直接创建网络图资源调用相册浏览器拿不到尺寸, 会使用默认的(200, 200), 导致图片显示跳动.
```
let networkImageURL = URL.init(string: "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fup.enterdesk.com%2Fedpic_source%2F3d%2F42%2F3e%2F3d423e3cb05d7edc35c38e3173af2a0d.jpg&refer=http%3A%2F%2Fup.enterdesk.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1674462223&t=5ccb00c0328b8ba0d522ac2e17e3a7bd")!
let networkImageAsset = PhotoAsset.init(networkImageAsset: NetworkImageAsset.init(thumbnailURL: networkImageURL, originalURL: networkImageURL)) // swiftlint:disable:this line_length

HXPhotoPicker.PhotoBrowser.show([networkImageAsset])
```
https://github.com/SilenceLove/HXPhotoPicker/assets/12481783/e0fdbe29-eb1f-42e8-8616-16e4ade89ee8

**Comment by SilenceLove** [comment]
外部自己传的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: liumengdi666 ***@***.***&gt;
发送时间: 2024年5月8日 16:18
收件人: SilenceLove/HXPhotoPicker ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [SilenceLove/HXPhotoPicker] 相册预览网络图拿不到size (Issue #686)





 
使用如下代码直接创建网络图资源调用相册浏览器拿不到尺寸, 会使用默认的(200, 200), 导致图片显示跳动.
 let networkImageURL = URL.init(string: "https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fup.enterdesk.com%2Fedpic_source%2F3d%2F42%2F3e%2F3d423e3cb05d7edc35c38e3173af2a0d.jpg&amp;refer=http%3A%2F%2Fup.enterdesk.com&amp;app=2002&amp;size=f9999,10000&amp;q=a80&amp;n=0&amp;g=0n&amp;fmt=auto?sec=1674462223&amp;t=5ccb00c0328b8ba0d522ac2e17e3a7bd")! let networkImageAsset = PhotoAsset.init(networkImageAsset: NetworkImageAsset.init(thumbnailURL: networkImageURL, originalURL: networkImageURL)) // swiftlint:disable:this line_length HXPhotoPicker.PhotoBrowser.show([networkImageAsset])  
https://github.com/SilenceLove/HXPhotoPicker/assets/12481783/e0fdbe29-eb1f-42e8-8616-16e4ade89ee8

**Comment by liumengdi666** [comment]
是的,我看到了这个参数, 但是我们现在只有网络图片的地址, 之前用的JXPhotoBrowser是支持的, 现在想统一换成HX的, 能支持这种情况吗?

**Comment by SilenceLove** [comment]
先在外面这样取一下吧，后面版本内部会加上处理这种情况
```swift
if let image = ImageCache.default.retrieveImageInMemoryCache(forKey: url.cacheKey) {
    self.imageSize = image.size
}
```
