### ISSUE TITLE
当包含编辑器，Editor库时，在iOS 16.1 系统版本下，启动闪退

### ISSUE THREAD

**Issue by RocPengPeng** [SilenceLove/HXPhotoPicker#691]
dyld[66760]: Symbol not found: _$s9PencilKit8PKStrokeV10randomSeeds6UInt32Vvg
  Referenced from: <3763EA13-2710-3B65-8D6A-B2A20FA4B7AE> /Users/z/Library/Developer/CoreSimulator/Devices/2E207C50-B65E-4656-9855-24EE74BA770E/data/Containers/Bundle/Application/E68BC8D3-A4D7-4C7F-A1CA-A94BA1810914/zzz.app/Frameworks/HXPhotoPicker.framework/HXPhotoPicker
  Expected in:     <17ED3FD5-BD32-34E0-B0D3-D01BD267FC4F> /Library/Developer/CoreSimulator/Volumes/iOS_20B72/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 16.1.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/PencilKit.framework/PencilKit

dyld`:
    0x105875a48 <+0>:  mov    x16, #0x209
    0x105875a4c <+4>:  svc    #0x80
->  0x105875a50 <+8>:  b.lo   0x105875a70               ; <+40>
    0x105875a54 <+12>: pacibsp 
    0x105875a58 <+16>: stp    x29, x30, [sp, #-0x10]!
    0x105875a5c <+20>: mov    x29, sp
    0x105875a60 <+24>: bl     0x10580ae88               ; cerror_nocancel
    0x105875a64 <+28>: mov    sp, x29
    0x105875a68 <+32>: ldp    x29, x30, [sp], #0x10
    0x105875a6c <+36>: retab  
    0x105875a70 <+40>: ret

**Comment by SilenceLove** [comment]
用最新版本

**Comment by RocPengPeng** [comment]
我用的4.2.0.3版本
pod 'HXPhotoPicker'
Installing HXPhotoPicker 4.2.0.3 (was 4.2.0.1)
启动还是报这个错，是模拟器问题吗？

这样引入不会报错
pod 'HXPhotoPicker/Picker'
pod 'HXPhotoPicker/Camera'

模拟器用的iPhone 12  16.1
