### ISSUE TITLE
单选照片，选择的照片中有gif的o时候崩溃

### ISSUE THREAD

**Issue by CHENDONGY** [SilenceLove/HXPhotoPicker#70]
当设置最大选择9张图片时，选择9张其中一张是gif图。确定之后，删除其中某一张照片出现崩溃。如果不选择到最大值，则不会崩溃

**Comment by LoveZYForever** [comment]
现在使用HXPhotoView时不支持单选。。

**Comment by CHENDONGY** [comment]
@LoveZYForever 经过测试单选照片不带gif图的时候是不会出现崩溃，只有当选择的图片当中有git格式的时候就会出现崩溃问题

**Comment by CHENDONGY** [comment]
@LoveZYForever 最终定位错误位置`_manager.configuration.saveSystemAblum = YES` 设置为YES的时候单选当选有gif图的时候删除崩溃，设置NO的时候不会出现

**Comment by LoveZYForever** [comment]
我试了一下demo
里面的，没有你说的这种情况出现啊。
你可以看一下demo4
