### ISSUE TITLE
代码功能建议

### ISSUE THREAD

**Issue by iPermanent** [SilenceLove/HXPhotoPicker#700]
目前编辑图片和视频时，下方的编辑功能在之前的版本(4.1.6)上是可以进行自定义的
config.editor.toolsView.toolOptions = [.init(imageName: "hx_editor_tools_play", type: .time),
 .init(imageName: "hx_editor_tools_graffiti", type: .graffiti),
.init(imageName: "hx_editor_photo_tools_emoji", type: .chartlet),
.init(imageName: "hx_editor_photo_tools_text", type: .text),
.init(imageName: "hx_editor_photo_crop", type: .cropSize)]
升级4.2.1后，使用同样的接口，但是编辑栏无法进行修改了
config.editor.toolsView.toolOptions = [
.init(imageType: HX.imageResource.editor.tools.video, type: .time),
.init(imageType: HX.imageResource.editor.tools.graffiti, type: .graffiti),
.init(imageType: HX.imageResource.editor.tools.chartlet, type: .chartlet),
.init(imageType: HX.imageResource.editor.tools.text, type: .text),
.init(imageType: HX.imageResource.editor.tools.cropSize, type: .cropSize)]
建议做成可配置化的，去除某些用户不必要的功能，比如视频加音乐等

**Comment by iPermanent** [comment]
此外还有个问题，就是在编辑完视频以后，不管是时长还是编辑区域，视频都会出现白色帧的闪动，复现方式可以录个游戏的横屏，然后编辑完的视频就会有白色块帧在视频里闪动

**Comment by SilenceLove** [comment]
这样修改
```swift
/// 方式一
HX.imageResource.editor.tools.text = .local("hx_editor_photo_tools_text")
/// 方式二
config.editor.toolsView.toolOptions = [
    .init(imageType: .local("hx_editor_photo_tools_text"), type: .text)
]
```

**Comment by iPermanent** [comment]
> 这样修改
> 
> ```swift
> /// 方式一
> HX.imageResource.editor.tools.text = .local("hx_editor_photo_tools_text")
> /// 方式二
> config.editor.toolsView.toolOptions = [
>     .init(imageType: .local("hx_editor_photo_tools_text"), type: .text)
> ]
> ```

我的意思是，去除掉其中的某个功能，比如不需要音乐这一项，这个代码只能设置图片，做不到去除某项功能

**Comment by SilenceLove** [comment]
`toolOptions `数组里面不添加`.music`

**Comment by iOSDeveloperShaoshuai** [comment]
能不能全部去掉 只留下完成和取消
