### ISSUE TITLE
如何获取视频的原始名称呢

### ISSUE THREAD

**Issue by nk4321** [SilenceLove/HXPhotoPicker#702]
现在获取的 url 里的视频名称并不是原始的

**Comment by SilenceLove** [comment]
可以用`PHAsset`去获取

**Comment by nk4321** [comment]
很高兴能得到你的回复。
我在HXPhotoPicker 没有寻找到相关获取PHAsset
有什么办法可以指导我一下吗

/// 获取缩略图
let thumImage = try await photoAsset.requesThumbnailImage()

/// 获取预览图
let previewImage = try await photoAsset.requestPreviewImage()

/// 获取 AVAsset
let avAsset = try await photoAsset.requestAVAsset()

/// 获取 AVPlayerItem
let playerItem = try await photoAsset.requestPlayerItem()

/// 获取 PHLivePhoto
let livePhoto = try await photoAsset.requestLivePhoto()

**Comment by nk4321** [comment]
> 可以`PHAsset`用去获取

很高兴能得到你的回复。
我在HXPhotoPicker 寻找相关获取PHAsset
有什么办法可以指导我一下吗

/// 获取缩略图
let thumImage = try await photoAsset.requesThumbnailImage()

/// 获取预览图
let previewImage = try await photoAsset.requestPreviewImage()

/// 获取 AVAsset
let avAsset = try await photoAsset.requestAVAsset()

/// 获取 AVPlayerItem
let playerItem = try await photoAsset.requestPlayerItem()

/// 获取 PHLivePhoto
let livePhoto = try await photoAsset.requestLivePhoto()

**Comment by SilenceLove** [comment]
`photoAsset.phAsset`
