### ISSUE TITLE
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file HXPhotoPicker/PhotoPreviewContentVideoView.swift, line 97 2024-06-25 16:46:19.950345+0800 996[21232:6601403] Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file HXPhotoPicker/PhotoPreviewContentVideoView.swift, line 97

### ISSUE THREAD

**Issue by jozdee** [SilenceLove/HXPhotoPicker#705]
switch photoAsset.mediaSubType {   崩溃：Thread 1: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value
引入项目后：
操作复现方式：选择视频，点击编辑进去一下，在退出或者确定都能复现

但是在demo又无法复现，麻烦作者做一下容错处理

**Comment by jozdee** [comment]
![WX20240625-175908@2x](https://github.com/SilenceLove/HXPhotoPicker/assets/10413288/2a62ecbb-c099-4df1-89de-6decf9072ad8)
使用redBookConfig 崩溃

另外使用getWXPickerConfig()样式时，只要进入编辑，即便什么编辑也不做，点击确定也会有生成进度，demo也能复现

**Comment by SilenceLove** [comment]
在主线程调用

**Comment by jozdee** [comment]
> 在主线程调用

希望大佬有时间能将SystemCameraViewController像CameraController一样暴露出去给oc来使用，因为发现在iPhone6等机型上用SystemCameraViewController获取画面的速度快很多

**Comment by Wuou** [comment]
一模一样的crash，选择照片后进入预留页面退出后直接crash。demo不会

**Comment by jozdee** [comment]
> 一模一样的crash，选择照片后进入预留页面退出后直接crash。demo不会

#  增加判断解决了，应该是上面强制解包造成的
#  guard let photoAsset = photoAsset else {
#      return
#  }

**Comment by Wuou** [comment]
> > 一模一样的crash，选择照片后进入预留页面退出后直接crash。demo不会
> 
> # 增加判断解决了，应该是上面强制解包造成的
> # guard let photoAsset = photoAsset else {
> # return
> # }

是的 我也是这么处理的。。
