### ISSUE TITLE
▿ Result<AssetURLResult, AssetError>   ▿ failure : PHAssetResource写入数据错误: Error Domain=PHPhotosErrorDomain Code=-1 "(null)"     - assetResourceWriteDataFailed : Error Domain=PHPhotosErrorDomain Code=-1 "(null)"

### ISSUE THREAD

**Issue by jozdee** [SilenceLove/HXPhotoPicker#706]
iOS17.5.1
<img width="961" alt="截屏2024-06-29 14 06 57" src="https://github.com/SilenceLove/HXPhotoPicker/assets/10413288/60257e9c-fad4-4d1d-a39e-22f403ce5a36">
导致所有图片与视频均无法正常获取

**Comment by jozdee** [comment]
这个问题麻烦作者有空帮忙看看，我这里也在调试原因中，demo又能正常

**Comment by SilenceLove** [comment]
可以往里面排查一下，这个应该是系统返回的错误。看看系统输入的是啥错误内容

**Comment by jozdee** [comment]
> 可以往里面排查一下，这个应该是系统返回的错误。看看系统输入的是啥错误内容

主要是才刚用Swift语言。

**Comment by jozdee** [comment]
找到原因了，tmp文件夹内有很多临时缓存文件， 所以项目在冷启动后直接删除了tem整个目录导致的，在iOS14、15、16均未造成任何异常，建议作者有空的时候加个缓存资源的目录是否存在的判断以增加容错

**Comment by SilenceLove** [comment]
可以是在获取的时候自己设置保存文件的路径，先这样试着看看能不能解决

**Comment by SilenceLove** [comment]
也可以在项目启动的时候判断tmp文件夹是否存在,不存在的花，重新创建一下吧。这个和库没啥关系。只要用到临时目录的地方都会有问题
