### ISSUE TITLE
关于photolist标题字体的问题

### ISSUE THREAD

**Issue by qiaqiaxian** [SilenceLove/HXPhotoPicker#707]
![1719648270](https://github.com/SilenceLove/HXPhotoPicker/assets/21219815/2fa0c6dd-030a-459d-b981-8fd2de5faa09)
先感谢大佬的项目
然后请问下这个照片列表的字体和箭头按钮大小怎么修改
看了下源码好像是在initView中写死了的

**Comment by SilenceLove** [comment]
可以自定义，实现协议`PhotoPickerNavigationTitle`
参考`AlbumTitleView`

**Comment by qiaqiaxian** [comment]
![WX20240701-124641@2x](https://github.com/SilenceLove/HXPhotoPicker/assets/21219815/7e7697f4-f490-493f-9e5a-06e039961d9a)
自定义里面 项目的extension都报错是怎么回事呢？

**Comment by SilenceLove** [comment]
要自己写方法
