### ISSUE TITLE
仅图片选择时，退出预览页闪退

### ISSUE THREAD

**Issue by Wuou** [SilenceLove/HXPhotoPicker#708]
<img width="740" alt="image" src="https://github.com/SilenceLove/HXPhotoPicker/assets/14285500/3d675b82-7447-4243-8426-949f654b3eb5">
通过排查发现，PhotoPreviewContentVideoView也会创建和销毁，但是因为只有图片，导致photoAsset为nil，photoAsset.mediaSubType这句就闪退了，建议前置解包  guard let photoAsset = photoAsset else { return }

**Comment by SilenceLove** [comment]
可以提交一个PR 我合并一下

**Comment by Wuou** [comment]
> 可以提交一个PR 我合并一下

兄弟 你那边手动改下喏  我pod的

> 可以提交一个PR 我合并一下

兄弟 你那边处理下喏 尽快提交个版本吧 不然很影响体验 我这边网不太好O.O
