### ISSUE TITLE
手动导入框架，Task报错

### ISSUE THREAD

**Issue by AbnerPei** [SilenceLove/HXPhotoPicker#712]
1. 项目需要自定义相机拍照页，发现CameraViewController不满足要求，所以就打算继承，又发现行不通，所以就手动改源码！
但是导入后就如下错误，不知怎么处理？

2. 还有 HXPICKER_ENABLE_CAMERA等编译条件，我在Xcode自己配了，不知是否正确？

![image](https://github.com/user-attachments/assets/9742dc10-9deb-4505-9001-73fdeaf13df3)

![image](https://github.com/user-attachments/assets/4f7540c2-ced8-4418-a2e5-ac97d3ab2859)

**Comment by SilenceLove** [comment]
`Task`报错和框架没关系
`HXPICKER_ENABLE_CAMERA `配置了就可以了
