### ISSUE TITLE
SwiftUIExample点击“完成”后无效

### ISSUE THREAD

**Issue by imsai-sh** [SilenceLove/HXPhotoPicker#717]
如题，点击“完成”后picker页面没有关闭。

运行的是最新master代码，commit:05d59af50677292492d6b47f4f507463b6d73202

环境：
iphone 14pm , iOS 18.0 (22A5307i)
xcode：Version 16.0 beta 4 (16A5211f)
macos: 版本15.0 Beta版(24A5279h)

**Comment by SilenceLove** [comment]
demo的问题，已更新
