### ISSUE TITLE
HEVC格式的视频保存失败- iPhone12、iOS17.2自带相机拍摄

### ISSUE THREAD

**Issue by yangjingwei1010** [SilenceLove/HXPhotoPicker#719]
![1723018661819](https://github.com/user-attachments/assets/d96d6328-11dc-4241-87b0-f514d27c6d30)

https://github.com/user-attachments/assets/787ed4d9-f6f5-4fe0-b3d1-03ba8e36262a

**Comment by SilenceLove** [comment]
![simulator_screenshot_9285B312-BD5F-408D-987D-5C609C39F18D](https://github.com/user-attachments/assets/6b09234c-35db-4315-aadb-3d97665e812f)

**Comment by yangjingwei1010** [comment]
发送视频的时候我对视频进行了压缩处理成mp4，就没问题了
