### ISSUE TITLE
关于头像裁剪问题

### ISSUE THREAD

**Issue by qiaqiaxian** [SilenceLove/HXPhotoPicker#726]
感谢大兄弟的项目

在使用的时候使用圆形遮罩裁剪头像后，可不可以设置成保存成方形图片，不是现在这种遮罩外面是白色的

**Comment by SilenceLove** [comment]
不设置圆形的直接设置成正方形的就可以了 固定比例 1:1

**Comment by qiaqiaxian** [comment]
> 不设置圆形的直接设置成正方形的就可以了 固定比例 1:1

APP显示的头像都是圆形，就是感觉裁剪的时候是方形遮罩有点奇怪，暂时不能设置吗？
先谢谢了
