### ISSUE TITLE
拍照弹出定位授权问题

### ISSUE THREAD

**Issue by Wuou** [SilenceLove/HXPhotoPicker#727]
拍照CameraViewController初始化会弹出定位授权，实际我只需要拍照授权即可，但是框架使用的宏去处理，除非修改pod项目移除宏，是否还有其他办法不用触发requestWhenInUseAuthorization？
CameraConfiguration中的allowLocation只是限制不去调用定位，但不能限制每次初始化的授权请求！
`#if HXPICKER_ENABLE_CAMERA_LOCATION
            locationManager = CLLocationManager()
            locationManager.delegate = self
            locationManager.desiredAccuracy = kCLLocationAccuracyBest
            locationManager.distanceFilter = kCLDistanceFilterNone
            locationManager.requestWhenInUseAuthorization()
            #endif`

**Comment by Wuou** [comment]
建议添加如下判断：
`#if HXPICKER_ENABLE_CAMERA_LOCATION
            if config.allowLocation {
                locationManager = CLLocationManager()
                locationManager.delegate = self
                locationManager.desiredAccuracy = kCLLocationAccuracyBest
                locationManager.distanceFilter = kCLDistanceFilterNone
                locationManager.requestWhenInUseAuthorization()
            }
            #endif`

**Comment by SilenceLove** [comment]
`config.allowLocation`设置一下看看

**Comment by Wuou** [comment]
> `config.allowLocation`设置一下看看



> `config.allowLocation`设置一下看看

设置了没用，应为config.allowLocation只是限制了startLoc，而locationManager.requestWhenInUseAuthorization()没有被限制。所以还是会弹出授权框

**Comment by jozdee** [comment]
这个相机加载画面太慢了，能否把选择照片里面的系统相机放出来呢？

**Comment by SilenceLove** [comment]
> 这个相机加载画面太慢了，能否把选择照片里面的系统相机放出来呢？

```swift
/// 自定义相机控制器
public var cameraViewController: CameraViewControllerProtocol.Type = CameraViewController.self
```
遵守协议`CameraViewControllerProtocol` 自己实现相机界面

**Comment by Wuou** [comment]
定位判断这里还没发布吗，我重新拉取的4.2.3.2，判断还没加上
