### ISSUE TITLE
图片预览出现图片旋转问题

### ISSUE THREAD

**Issue by yangjingwei1010** [SilenceLove/HXPhotoPicker#730]
图片预览有时候会出现图片旋转90度的问题，gif图和普通图片都可能会出现，下面截图用的官方demo也会出现这个问题。
![1726796474808](https://github.com/user-attachments/assets/1e695999-4a8d-4266-8981-7016a8da9327)
![1726796539759](https://github.com/user-attachments/assets/4980f6d5-00b9-4825-9882-4cf60ff4388a)
![1726796570270](https://github.com/user-attachments/assets/31bb7c12-7aeb-49ff-8f5f-0dd3b8177d86)

**Comment by yangjingwei1010** [comment]
点击图片进入预览页面不会出现旋转，在预览页面左右滑动的时候会出现旋转问题

**Comment by SilenceLove** [comment]
是相册选择的图片还是本地添加的图片

**Comment by yangjingwei1010** [comment]
Photo Browser进来的图片浏览, 相册选择图片的时候浏览没有问题

**Comment by SilenceLove** [comment]
可以自己把图片旋转正常再预览



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yangjingwei1010 ***@***.***&gt;
发送时间: 2024年9月24日 15:59
收件人: SilenceLove/HXPhotoPicker ***@***.***&gt;
抄送: Silence ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [SilenceLove/HXPhotoPicker] 图片预览出现图片旋转问题 (Issue #730)





 
Photo Browser进来的图片浏览, 相册选择图片的时候浏览没有问题
