### ISSUE TITLE
这种效果没有了吗？

### ISSUE THREAD

**Issue by wyhu** [SilenceLove/HXPhotoPicker#76]
<img width="80" alt="2018-01-24 12 21 40" src="https://user-images.githubusercontent.com/14191506/35316076-9305255c-010a-11e8-9698-277b48695b6a.png">

**Comment by LoveZYForever** [comment]
没有了...

**Comment by kayakayaYuan** [comment]
这种下拉的取消了啊

**Comment by SilenceLove** [comment]
下拉相册列表已加 v2.2.3
