### ISSUE TITLE
一个获取选择图片的疑问

### ISSUE THREAD

**Issue by HouWan** [SilenceLove/HXPhotoPicker#83]
我看您获取选择图片的方法是写入沙盒，但是如何确保我取的时候，顺序是我之前选择的呢？

另外，这种写入沙河的操作，我发现在低配手机上，是造成卡顿、发热的主因。不知道的有没有其他方案，既能保证图片的顺序，又能不写入沙盒。

目前我的办法是使用`HXPhotoTools`里的方法，loading，然后再排序。

**Comment by LoveZYForever** [comment]
你看最新版的demo
