### ISSUE TITLE
拍照获取照片疑问

### ISSUE THREAD

**Issue by HouWan** [SilenceLove/HXPhotoPicker#85]
您好，在拍照之后，我看模型`HXPhotoModel`里并没有`asset`这个值，是不是可以理解为拍照之后，还没有存到相册里，所以`asset`值为空，那我想取拍到的照片，怎么取呢？我目前用的是`previewPhoto`，但是这个图压缩并不理想，想取出拍照源文件，进行自己压缩，有什么办法吗？

**Comment by LoveZYForever** [comment]
HXDatePhotoToolManager

**Comment by SilenceLove** [comment]
相机拍照的都是临时的UIImage对象

**Comment by Nick-Hoper** [comment]
func photoView(_ photoView: HXPhotoView!, changeComplete allList: [HXPhotoModel]!, photos: [HXPhotoModel]!, videos: [HXPhotoModel]!, original isOriginal: Bool) {
        
        var requestType:HXDatePhotoToolManagerRequestType = HXDatePhotoToolManagerRequestTypeHD
        if isOriginal{
            requestType = HXDatePhotoToolManagerRequestTypeOriginal
        }
        self.toolManager.writeSelectModelListToTempPath(withList: allList, requestType: requestType, success: { (allURL, photoURL, videoURL) in
      
            self.imagesArray.removeAll()
            for item in photoURL!{
                let imageData = NSData.init(contentsOf: item)
                let image = UIImage.init(data: imageData! as Data)
                self.imagesArray.append(image!)
                print("self.imagesArray=\(self.imagesArray)")
            }
        }) {
            print("写入失败")
        }
    }
