### ISSUE TITLE
照片数量选择问题

### ISSUE THREAD

**Issue by TouchGuoGuo** [SilenceLove/HXPhotoPicker#91]
照片最大选择数和视频最大选择数都是必填项目 ，这两个需要设置的值不确定  ，只想要两个总和加起来等于10 怎么做 ？

**Comment by LoveZYForever** [comment]
当时没考虑过这样的情况。。。

**Comment by TouchGuoGuo** [comment]
还有一个问题就是Demo9里面 我要使用相机拍照后的照片是没有放到模型中的 希望能够解决

**Comment by SilenceLove** [comment]
已解决选择数量的问题...
