### ISSUE TITLE
iPad 点击崩溃

### ISSUE THREAD

**Issue by TheLittleBoy** [SilenceLove/HXPhotoPicker#96]
'Your application has presented a UIAlertController (<UIAlertController: 0x10105a200>) of style UIAlertControllerStyleActionSheet. The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'

当在iPad上如果没有设置如下两个属性 
alertController.popoverPresentationController.sourceView
alertController.popoverPresentationController.sourceRect
会导致程序crash。

**Comment by LoveZYForever** [comment]
了解👌
